- resources/docs/EXPERIMENTS.md
Hi,
this PR updates the link to the tutorial page on the experiments documentation site. The old reference was deleted with d45fe8d7598f5e469dd178a77b22d8fa00cc965e.
> docs: fix link to tutorial page

- resources/docs/EXPERIMENTS.md
Hi,
this PR fixes the initialization of `WordEmbeddings` in the experiments section: old attributes `ft-crawl` and `ft-german` are replaced.
Related to #26.
> GH-26 docs: fix initialization of `WordEmbeddings` in experiments section

- flair/data.py
- flair/data_fetcher.py
- flair/embeddings.py
- flair/models/text_classification_model.py
- flair/trainers/text_classification_trainer.py
- flair/training_utils.py
- tests/resources/tasks/ag_news/dev.txt
- tests/test_embeddings.py
- tests/test_text_classifier.py
- tests/test_text_classifier_trainer.py
closes #20 
- use ReduceLROnPlateau in TextClassifier
- Fix bugs in training TextClassifier on GPU
- TextClassifier now takes a DocumentEmbeddings instead of a list of TokenEmbeddings
- DocumentLSTMEmbedding now takes additional parameters to define (1) the output dimension of the reprojection of words and (2) whether only the last representation or a combination of last and first representation of the LSTM should be taken as document embedding
> GH-20: Improve text classifier

- resources/docs/TUTORIAL_TRAINING_A_MODEL.md
Hi,
this PR corrects both word and character embeddings for the AGNews text classification example. Now GloVe embeddings are used. Originally, embeddings for German are used, which are not suitable for English news articles.
> docs: use GloVe and English news embeddings for AGNews example

- flair/embeddings.py
This is an attempt at implementing https://github.com/zalandoresearch/flair/issues/5.
No extra classes were neccessary, this PR just changes the approach taken for checking if a word is OOV.
Previously, flair would store a set of all known words from the Gensim `KeyedVectors` class.
I changed this to use the `__contains__` implementation on `KeyedVectors`, which does just that, without any extra data structures. However, if the embeddings are of type `FastTextKeyedVectors`, Gensim will also use the subword-embeddings in case of an OOV (https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/keyedvectors.py#L1928).
Unfortunately, this can't currently be used with the FastText-embeddings shipped with flair, since they don't actually have any subword-embeddings, the …
> GH-5: Make use of subword embeddings if supported

- README.md
- flair/data.py
- flair/data_fetcher.py
- flair/embeddings.py
- tests/test_data.py
- Added `whitespace_after` field to Token (see #54)
- Sentence tokenizer now records `whitespace_after`
- Added method to infer `whitespace_after` field for already tokenized data
- Distringuish between `to_plain_string()` and `to_tokenized_string()` of `Sentence` - the former produces original string, the latter whitespace-tokenized string
> GH-54: token offsets

- flair/data.py
- tests/test_data.py
> GH-83: Don't create empty tokens when using whitespace tokenization.

- flair/trainers/sequence_tagger_trainer.py
Hi,
as discussed in #85 this PR sets the `save_model` parameter in `sequence_tagger_trainer` to `True` as new default.
> GH-85: Set save_model to True as default

- README.md
Hi,
this PR adds some nice status badges to the main readme. The following badges were introduces:
* PyPI version
* GitHub issues
* Contributions are welcome
* License information
* Travis CI status
It looks like:
> readme: introduce status badges

- resources/docs/TUTORIAL_BASICS.md
- resources/docs/TUTORIAL_TRAINING_A_MODEL.md
Small simplifications to tutorials:
- moved explanation on text classification data format from BASICS to TRAINING A MODEL, since the format is only used in context of training a classification model. This makes the basics section a bit lighter and the classification explanation more grouped. 
- corrected typo
> GH-8: tutorials

- flair/embeddings.py
- flair/trainers/text_classification_trainer.py
closes #108 
We could not find any memory leak. However, training a text classifier on a large data set which contains large documents/sentences using contextual string embeddings is quite expensive and can lead to out of memory issues. To avoid this, you can now
(1) disable the evaluation on the training data set
(2) use a smaller batch size for evaluation
> GH-108: Add additional training parameters.

- flair/data_fetcher.py
- flair/embeddings.py
closes #48 
- add word dropout to text classifier
- add possibility to read only documents with less than a given number of tokens for a text classification task
> GH-48: Add word dropout to text classifier

- flair/__init__.py
- flair/data.py
- flair/data_fetcher.py
- flair/trainers/language_model_trainer.py
- flair/trainers/sequence_tagger_trainer.py
- flair/trainers/text_classification_trainer.py
- flair/training_utils.py
> GH-16: Standardize logging output for sequence tagger and text classifier

- flair/data.py
- flair/embeddings.py
- flair/models/language_model.py
- flair/trainers/text_classification_trainer.py
related to #48 
- don't use locked and word dropout in text classifier per default
- fix issue in eval method in text classifier
> GH-48: Don't use Locked and Word Dropout in text classifier per default

- flair/data.py
- flair/embeddings.py
- flair/models/text_classification_model.py
- flair/trainers/sequence_tagger_trainer.py
- flair/trainers/text_classification_trainer.py
- requirements.txt
- tests/test_language_model_trainer.py
This PR adds a method for writing embeddings computed with `CharLMEmbeddings` to disk for fast reuse in and across experiments, therefore: 
- If a model is trained using CharLMEmbeddings is run over the same dataset several times (i.e. for experimenting with parameters), embeddings are only computed on the first run and then reused, thus potentially saving a lot of time.
- If embeddings are too large to fit into memory, you can set `embeddings_in_memory=False` as parameter in the `.train()` function and still reuse computed embeddings, thus again potentially saving a lot of time.
> GH-137: memory optimizations

- flair/data_fetcher.py
- flair/trainers/text_classification_trainer.py
- flair/training_utils.py
- Retain Token embeddings in memory by default in `TextClassificationTrainer`
- This allows faster training on larger datasets
- Modify length restriction in `NLPTaskDataFetcher.read_text_classification_file()` to crop documents to length instead of filtering them.
> GH-146: Retain Token embeddings in memory by default 

- flair/embeddings.py
> GH-151: Reset cache settings when saving model

- flair/trainers/sequence_tagger_trainer.py
- flair/trainers/text_classification_trainer.py
- flair/training_utils.py
- tests/test_utils.py
With the changes in GH-75, the use of the CoNLL evaluation script was removed.
Nevertheless I found it very useful for evaluation class-based predictions, and GH-75 didn't replace this functionality.
So I added this functionality into the `Metrics` object.
Please feel free to suggest any changes and improvements.
> Added class-based metrics

- flair/embeddings.py
- flair/models/sequence_tagger_model.py
- flair/trainers/sequence_tagger_trainer.py
- resources/docs/TUTORIAL_WORD_EMBEDDING.md
Closes #174 
To address serialization problems on Mac and Windows, we've reduced the size of the embeddings and pre-trained models. This has the added advantage that models can now be loaded and saved faster. 
We've also added pre-trained fasttext embeddings for a number of additional languages, which can now be instantiated using their two-letter language code, i.e.
```python
embeddings = WordEmbeddings('pt')
```
for Polish and `WordEmbeddings('ar')` for Arabic etc.
> GH-174: serialization

- flair/embeddings.py
- tests/test_embeddings.py
Closes #229 
- Add FastText embeddings for 30 languages (English, German, Dutch, Italian, French, Spanish, Swedish, Danish, Norwegian, Czech, Polish, Finnish, Bulgarian, Portuguese, Slovenian, Slovakian, Romanian, Serbian, Croatian, Catalan, Russian, Hindi, Arabic, Chinese, Japanese, Korean, Hebrew, Turkish, Persian, Indonesian)
- Each language gets a wiki and a crawl embedding and is called using the two-letter language code. (`WordEmbeddings('de') `or `WordEmbeddings('de-wiki')` to instantiate the wiki embedding for German and `WordEmbeddings('de-crawl')` to instantiate the crawl embedding)
- We add more LM embeddings from @stefan-it, namely the Dutch CharLM embeddings, callable with `CharLMEmbeddings('dutch-forward')` and `CharLMEmbeddings('dutch-backward')`
- New multilingual …
> GH-229: multilingual embeddings

- flair/embeddings.py
- flair/hyperparameter/param_selection.py
- flair/trainers/trainer.py
closes #276 
- add option to `ModelTrainer` to anneal either against test loss or dev score
- during parameter selection, never test on test data
- renamed some variables in `ModelTrainer` for clarity
> GH-276: annealing options

- flair/embeddings.py
- flair/models/sequence_tagger_model.py
Thanks to @mhham for providing us the french models!
closes #238
> GH-238: Add french models.

- requirements.txt
Hi,
today version 0.4.0 of the `pytorch-pretrained-bert` was released (see [Changelog](pytorch-pretrained-bert)) so it would be great to have the latest version of that module in the upcoming `flair` release.
> Bump version of pytorch-pretrained-bert

- README.md
Otherwise pytest could run test in the `lib` folder on all dependencies of the package. That happened to me.
Update: I just realized that I only ran into the issue, because it did do the installation with pip in a toplevel venv. This was neccessary, because the pipenv installation did not work. So this PR might not useful.
> Update the pytest command

- resources/docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md
Hi,
this PR corrects the tutorial for training an own language model. The corpus folder must be a `Path` object (which is passed to the `TextCorpus` instance).
> GH-340: use Path object for specifying corpus folder

- flair/models/language_model.py
- flair/trainers/language_model_trainer.py
- tests/test_language_model.py
- tests/test_model_integration.py
Small optimizations to the `LanguageModel` and `LanguageModelTrainer` classes: 
- lowers default dropout of the `LanguageModel` to 0.1 which will be better for most use cases (#349) 
- small improvements to `generate_text()` method: Newline character is no longer added by default and method now additionally returns average log likelihood of generated string. 
- only send mini-batches to GPU for better GPU memory usage
> GH-349: language model optimizations

- flair/data_fetcher.py
- flair/embeddings.py
- resources/docs/TUTORIAL_3_WORD_EMBEDDING.md
- resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md
- resources/docs/TUTORIAL_6_CORPUS.md
This PR adds support for the **Basque language** to Flair. Specifically: 
- @stefan-it trained Flair embeddings for Basque which we now include, load with: 
```python
forward_lm_embeddings = FlairEmbeddings('basque-forward')
backward_lm_embeddings = FlairEmbeddings('basque-backward')
```
- add a download routine for Basque Universal Dependencies, load with 
```python
corpus = NLPTaskDataFetcher.load_corpus(NLPTask.UD_BASQUE)
```
- add Basque FastText embeddings, load with: 
```python
wikipedia_embeddings = WordEmbeddings('eu-wiki')
crawl_embeddings = WordEmbeddings('eu-crawl')
```
> GH-329: Basque language support

- flair/training_utils.py
Hi,
Found one comparison of `None` done with `==` while it should be `is` instead.
Cheers, and thanks for `flair`!
Bruno
> Use is to compare None

- flair/data.py
- flair/embeddings.py
- flair/models/language_model.py
- flair/models/text_classification_model.py
- tests/test_embeddings.py
closes #367 
- `Sentence` embeddings are now vectors, same as `Token`. 
- Unit tests test for embedding length
- Make printing prettier for `Sentence` and `TaggedCorpus`
> GH-367: sentence embeddings

- flair/embeddings.py
BertEmbeddings fails when running on cuda backend on mixing GPU/CPU tensors.
The fix is simple - copy the model onto the GPU.
Should fix issue #325 
Thanks
> GH-325: Fix BERT embeddings when running using CUDA

- flair/trainers/language_model_trainer.py
If a corpus is known to be mono-lingual, then it is useful to turn off
the default behavior of randomly swapping the case of a small
percentage of lines.
This fix adds a top level parameter that by default preserves the
original behavior. The user can set this parameter to False if he or
she does not want the data randomly swapped.
> Issue #GH-381: add param to turn off case flipping in TextCorpus

- flair/embeddings.py
- resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md
This PR adds pre-computed FlairEmbeddings for Spanish. Embeddings were computed over Wikipedia by @iamyihwa (see #80 )
To load Spanish FlairEmbeddings, simply do: 
```python
embeddings_fw = FlairEmbeddings('spanish-forward')
embeddings_bw = FlairEmbeddings('spanish-backward')
embeddings_fw_fast = FlairEmbeddings('spanish-forward-fast')
embeddings_bw_fast = FlairEmbeddings('spanish-backward-fast')
```
> GH-80: added Spanish LM embeddings trained by @iamyihwa

- flair/__init__.py
- flair/data.py
- flair/embeddings.py
- flair/models/language_model.py
- flair/models/sequence_tagger_model.py
- flair/models/text_classification_model.py
- flair/trainers/language_model_trainer.py
closes #270 
- Don't use `torch.autograd.Variable` anymore
- Use `tensor = tensor.to(flair.device)` instead of `if torch.cuda.is_available(): tensor = tensor.cuda()`
> GH-270: Use new cuda semantics

- flair/data_fetcher.py
Hi,
this PR adds a data fetcher that downloads and processes the IMDB dataset.
Additionally, the training corpus for a text classification task is downsampled, when no development dataset was specified.
To test the new IMDB data fetcher, just use:
```python
from flair.data_fetcher import NLPTaskDataFetcher, NLPTask, TaggedCorpus
NLPTaskDataFetcher.download_dataset(NLPTask.IMDB)
corpus: TaggedCorpus = NLPTaskDataFetcher.load_corpus(NLPTask.IMDB)
print(corpus.obtain_statistics())
```
The output of the corpus statistics:
```json
{
"TRAIN": {
"dataset": "TRAIN",
"total_number_of_documents": 22500,
"number_of_documents_per_class": {
"pos": 11191,
"neg": 11309
},
"number_of_tokens_per_tag": {},
"number_of_tokens": {
"total": 6168036,
"min": 10,
"max": 2786,
"avg": 274.1349333333333
}
},
"TEST": …
```
> Add IMDB data fetcher

- requirements.txt
- setup.py
closes #429 
AllenNLP uses a lower version of matplotlib than the one we used in our requirements.txt. To make both compatible, we lower our matplotlib verison as well.
> GH-429: relax matplotlib requirement to make compatible with allennlp

- flair/trainers/trainer.py
Previous evaluation for text classification is incorrect. In particular, TP + FP + TN + FN doesn't equal number of sentences and TP is always same as TN. For example:
1: tp: 936 - fp: 58 - fn: 0 - tn: 936 - precision: 0.9416 - recall: 1.0000 - accuracy: 0.9699 - f1-score: 0.9699
2: tp: 0 - fp: 0 - fn: 92 - tn: 0 - precision: 0.0000 - recall: 0.0000 - accuracy: 0.0000 - f1-score: 0.0000
3: tp: 509 - fp: 464 - fn: 5 - tn: 509 - precision: 0.5231 - recall: 0.9903 - accuracy: 0.6846 - f1-score: 0.6846
Counting FN and TN is incorrect:
```
for true_value in true_values:
if true_value not in predictions:
metric.add_fn(true_value)
else:
metric.add_tn(true_value)
```
This commit fixes evaluation for text classification. Same classifier outputs:
1: tp: 936 - fp: 58 - fn: 0 - tn: 0 - precision: …
> Fixing text classification evaluation

- flair/__init__.py
Hi,
this PR adds version number to `__init__.py`, so it can be retrieved by `flair.__version__`.
I set the version number to the upcoming *0.4.1* release.
Closes #446 :)
> GH-446: introduce version number

- flair/embeddings.py
- flair/models/language_model.py
- flair/models/sequence_tagger_model.py
- flair/trainers/language_model_trainer.py
- setup.py
- tests/test_embeddings.py
- tests/test_hyperparameter.py
- tests/test_model_integration.py
- tests/test_visual.py
closes #387 
This PR adds a fix for retrieving embeddings from a character LM for long sequences. The idea is to chop long sequences into chunks and push each chunk through the LM, while always remembering the last hidden state as new initial hidden state. This lowers memory requirements (shorter sequences at once) but increases runtime (more calls to RNN).
In detail: 
- `LanugageModel.get_representation()` and `FlairEmbeddings` now have the `chars_per_chunk` parameter that defaults to 512. Lowering this parameter reduces memory but increases runtime. 
- `LanguageModelTrainer` can now shuffle sentences in each split
- Deprecated `DocumentMeanEmbeddings` removed, as well as most mentions of deprecated `CharLMEmbeddings`
- Removed slow unit tests
> GH-387: modify FlairEmbeddings to handle large texts

- flair/embeddings.py
- flair/models/sequence_tagger_model.py
- flair/models/text_classification_model.py
- flair/trainers/language_model_trainer.py
for issue #423 #37 
* `~:0(<method 'to' of 'torch._C._TensorBase' objects>)`: 	9.234 sec -> 	1.605 sec
> [WIP] initial work to improve gpu occupancy

- flair/embeddings.py
- flair/models/text_classification_model.py
- flair/visual/activations.py
- tests/test_data_fetchers.py
- tests/test_hyperparameter.py
- tests/test_model_integration.py
closes #462 
A number of smallish bug fixes. Fixes some CUDA operations and makes sure that the test IMDB dataset is used in unit tests instead of the full dataset (this was leading to timeouts).
> GH-462: fix cuda unit tests

- flair/trainers/trainer.py
@alanakbik regarding my latest PR there were two more small changes that needed to be made in order to make sure that the evaluation is not called on over `self.corpus.test` if this is an empty list.
> make sure evaluation is not performed over self.corpus.test if this doesn't contain any Sentence

- flair/embeddings.py
- requirements.txt
- setup.py
Add [bype pair embeddings](http://www.lrec-conf.org/proceedings/lrec2018/pdf/1049.pdf) to Flair.
> GH-438: added byte pair embeddings

- resources/docs/TUTORIAL_6_CORPUS.md
Hi,
this PR extends the text classification dataset section for IMDB and adds the possibility to use the recently introduced data fetcher (#410) to download and preprocess the IMDB dataset automatically.
Closes #461 :)
> GH-461: mention IMDB data fetcher in documentation

- flair/embeddings.py
the new CUDA semantics introduced an error with CharacterEmbeddings (see #482)
This PR fixes this error.
> GH-482: fix CUDA error with CharacterEmbeddings

- flair/embeddings.py
Hi,
this PR adds support for the recently released PubMed [model](https://allennlp.org/elmo) for ELMo.
Example usage:
```python
from flair.embeddings import ELMoEmbeddings
sentence = Sentence("Diabetes insipidus : The other diabetes")
embeddings = ELMoEmbeddings('pubmed')
embeddings.embed(sentence)
for token in sentence.tokens:
print(token.get_embeddings())
```
Closes #502
> GH-502: add support for pubmed ELMo model

- flair/embeddings.py
closes #504 
Workaround in which the sentence piece model is serialized as a binary that is written to the appropriate folder if missing.
> GH-504: workaround for serialization of BPEmb object

- flair/embeddings.py
@jessepeng computed a character LM over PubMed abstracts and shared the models with us. This PR adds them as FlairEmbeddings. 
Init with: 
```python
embeddings_f = FlairEmbeddings('pubmed-forward')
embeddings_b = FlairEmbeddings('pubmed-backward')
```
> Added PubMed embeddings computed by @jessepeng

- flair/embeddings.py
add other available RNN types to choose from
> GH-511: change DocumentLSTMEmbeddings to use LSTM instead of GRU

- flair/data_fetcher.py
- flair/embeddings.py
- tests/test_model_integration.py
This PR fixes a few minor issues in preparation for 0.4.1 release. 
- `DocumentLSTMEmbeddings` are marked as deprecated but not removed so that serialized models still work. The deprecation warning points to the new `DocumentRNNEmbeddings` class as class to be used instead. 
- `BytePairEmbeddings` threw an error for empty words. Now, a null vector is used for empty words instead.
- the `load_text_classification_corpus()` methods of the `NLPTaskDataFetcher` previously tokenized all corpora by default. But some text classification corpora, such as TREC_6 are already tokenized. So we added an option to turn tokenization off.
- added Turian embeddings which are very small and will hopefully speed up integration tests. Load with `WordEmbeddings('turian')`
> GH-512: Minor embedding fixes

- flair/models/language_model.py
- tests/test_language_model.py
closes #498 
to calculate perplexity using a language model do this: 
```python
from flair.embeddings import FlairEmbeddings
language_model = FlairEmbeddings('news-forward-fast').lm
grammatical = 'The company made a profit'
perplexity_gramamtical_sentence = language_model.calculate_perplexity(grammatical)
ungrammatical = 'Nook negh qapla!'
perplexity_ungramamtical_sentence = language_model.calculate_perplexity(ungrammatical)
print(f'"{grammatical}" - perplexity is {perplexity_gramamtical_sentence}')
print(f'"{ungrammatical}" - perplexity is {perplexity_ungramamtical_sentence}')
```
> GH-498: sentence perplexity

- flair/embeddings.py
Fix a typo in the [embeddings file](https://github.com/zalandoresearch/flair/blob/release-0.4.1/flair/embeddings.py#L814) in release 0.4.1
Sorry for the late detection and having to open a new PR for it 👎
> Fix typo in embeddings.py for release 0.4.1

- flair/embeddings.py
Hi,
this PR uses the correct bert model variable to check if an available model is used.
Fixes #550 .
> GH-550: Fix bert model check

- flair/file_utils.py
As explained in https://github.com/grangier/python-goose/issues/78#issuecomment-40987844 , mkstemp() opens the file, which then creates a lock on the file, so Windows is unable to delete it.
mktemp() does not do this
Fixes #548
> Fix permission error in Windows 

- flair/embeddings.py
- resources/docs/TUTORIAL_3_WORD_EMBEDDING.md
Previously all occurrences of `Komninos` were spelled as `Komnios`.
> Fix typos for Komninos embeddings

- flair/data.py
- tests/test_data.py
Fix #565 by raising a `ValueError` for an empty string.
> Fix #565 by raising an Exception for an empty String

- flair/models/text_classification_model.py
- resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md
Replaced some instances of `DocumentLSTMEmbeddings` with `DocumentRNNEmbeddings` to update the [tutorial](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#tutorial-7-training-a-model) with respect to the new release 0.4.1
> Replace instances of DocumentLSTMEmbeddings with DocumentRNNEmbeddings

- flair/embeddings.py
Hi,
this PR fixes a `expected type torch.cuda.FloatTensor but got torch.FloatTensor` error when training and testing the recently introduced `PooledFlairEmbeddings` on GPU.
Fixes #620.
> GH-620: cuda fix for PooledFlairEmbeddings

- flair/embeddings.py
Hi,
this PR finally introduces embeddings from the OpenAI GPT model. It uses the excellent [pytorch-pretrained-BERT](https://github.com/huggingface/pytorch-pretrained-BERT) library to download the GPT model, tokenize the input and extract embeddings from the subtokens.
For example the input token `puppeteer` will be tokenized into three subwords: `pupp`, `ete` and `er</w>`. I implemented four approaches to get embeddings from a token:
* Use the first subword from a token
* Use the last subword from a token
* Use the first and last subword from a token
* Use mean of all subwords
Here's a short benchmark on CoNLL-2003 NER for English, using only GPT embeddings (and no other embeddings like word embeddings):
| Pooling strategy | F1-Score
| -------------------- | -------------
| `first` …
> GH-547: introduce OpenAI GPT embeddings

- train.py
Hi,
this PR fixes the training example script. The current `train.py` example script trains a model on English Universal Dependencies using the `pos` tag type. But that tag type is not correct for Universal Dependencies, because `upos` (indicating universal part-of-speech tags) should be used instead.
See also [CoNLL-U](https://universaldependencies.org/format.html) format description.
> Small fix for training example script

- flair/data.py
- tests/test_data.py
Hi,
with this PR both string and Token objects can be passed to the `add_token` method.
This was requested in #627.
> GH-627: Extend add_token method

- flair/models/text_classification_model.py
closes #605 
Adds a softmax layer to get confidence scores for predictions in the `TextClassifier`.
> GH-605: add softmax to single label classification for confidence score

- flair/models/language_model.py
#closes 464 
The `generate_text` method still used the `.cuda()` method to put tensors on GPU instead of `.to(device)`, defaulting on cuda:0. This causes errors if run in a process on another GPU, such as cuda:1. This PR fixes this.
> GH-464: fix text generation on cuda:1

- flair/__init__.py
- flair/data_fetcher.py
- flair/embeddings.py
- flair/file_utils.py
- tests/test_data_fetchers.py
closes #507 
closes #653
You can now specify the base cache directory, i.e. the directory to where all models/embeddings/datasets get downloaded. It defaults to .flair in your home folder, but you can override this by calling 
```python
import flair
flair.cache_root = 'my/cache/directory'
```
before calling your code.
> GH-507: make cache_root a global variable

- resources/docs/TUTORIAL_8_MODEL_OPTIMIZATION.md
I think the `find_learning_rate` call should be applied to the `trainer` object instead to the `ModelTrainer` class, the latter not working in `0.4.1` anyway.
Also the `Plotter` import was missing.
> Fixed a method call and a missing import.

- requirements.txt
- setup.py
I don't see any reason why `regex` is pinned to `2018.1.10`. This is causing some issues with our other dependencies so I removed the version pin.
All tests pass locally on python 3.6
> Relax `regex` version in dependencies

- flair/data_fetcher.py
Added the max_tokens_per_doc parameter to the 'load_classification_corpus' function.
Fixed documentation regarding this parameter in the 'read_text_classification_file' function according to the real functionality.
> added the max_tokens_per_doc param to the load_classification_corpus

- flair/embeddings.py
Take custom path to a word2vec model saved on disk and load it through gensim.
In case model has been saved as a binary file load it through gensim.models.KeyedVectors.load_word2vec_format with "binary"  argument set to True
> allow loading custom word2vec models(including model saved as binary file)

- flair/embeddings.py
Hi,
as briefly discussed with @alanakbik, this PR changes the default pooling operation for the `PooledFlairEmbeddings` from `fade` to `min`.
`fade` was not even mentioned in the upcoming NAACL paper, and `min` leads to good results:
> Change default pooling operation for PooledFlairEmbeddings

- flair/data_fetcher.py
Hi,
this PR adds support for the recently introduced German HDT Universal Dependencies dataset. For more information, see #673.
By default, the new dataset fetcher will use the two training files (`train-a` and `train-b`). For that purpose these two training files are concatenated and then used for training.
Example usage:
```python
from flair.data_fetcher import NLPTaskDataFetcher, NLPTask
corpus = NLPTaskDataFetcher.load_corpus(NLPTask.UD_GERMAN_HDT)
print(corpus)
```
It then downloads the German HDT UD dataset, concatenates training files and outputs the corpus stats:
```bash
TaggedCorpus: 133932 train + 16733 dev + 16382 test sentences
```
> GH-673: add support for new German HDT Universal Dependencies dataset

- flair/models/text_classification_model.py
- tests/test_model_integration.py
**Added feature to get the confidence score of each class in case of Multi-class text classification**
Added new param  `multi_class_prob` to function `predict` to return the confidence score of all classes instead of just returning class with the highest confidence.
*Example to use this method*
```pythnon
>>> from flair.models import TextClassifier
>>> from flair.data import Sentence
>>> classifier = TextClassifier.load('en-sentiment')
>>> sentence = Sentence('I have added a new feature in flair')
>>> classifier.predict(sentence)
>>> print('Sentiment Score: ', sentence.labels)
Sentiment Score:  [POSITIVE (0.9674275517463684)]
>>> classifier.predict(sentence, multi_class_prob=True)
>>> print('Sentiment Score: ', sentence.labels)
Sentiment Score:  [POSITIVE (0.9674275517463684), NEGATIVE …
```
> Add method to find probability for each class in case of multi-class classification

- flair/data_fetcher.py
- flair/file_utils.py
- flair/models/text_regression_model.py
This PR adds dataset downloaders for the four [WASSA-17 text regression tasks](https://competitions.codalab.org/competitions/16380#learn_the_details). 
Load with: 
```python
corpus = NLPTaskDataFetcher.load_corpus(NLPTask.WASSA_JOY)
```
> GH-440: added WASSA 2017 emotion intensity task

- flair/models/sequence_tagger_model.py
- requirements.txt
- setup.py
- added `get_transition_matrix` to the `SequenceTagger` model
- added `tabulate` dependency to requirements.txt
> A simple method to print the tag transition matrix learned by the CRF

- flair/embeddings.py
Changed the call "sentence[idx]._embeddings[embedding.name]" for forward [len(sentence)-1] and backward [0] to solve the index out of range error.
> BugFix DocumentLMEmbeddings class

- flair/data.py
- flair/datasets.py
- flair/embeddings.py
- flair/models/sequence_tagger_model.py
- flair/models/text_classification_model.py
- flair/nn.py
- flair/trainers/trainer.py
- tests/test_embeddings.py
- train.py
This PR adds a number of small improvements and new features that were implemented in the course of investigating (but not yet solving) #678. 
FastText is a popular baseline for classifying text, based on learnable word embeddings that are mean-pooled. To allow Flair users to use this approach, we implemented a new word embedding type and adapted a document embedding: 
- **`OneHotEmbeddings`** - we add one-hot embeddings that are trainable on a downstream task. Instantiate by passing a corpus: 
```python
from flair.embeddings import OneHotEmbeddings
from flair.datasets import UD_ENGLISH
corpus = UD_ENGLISH()
embeddings = OneHotEmbeddings(corpus)
```
These embeddings can also be used to embed other fields (#398 #618). 
- Fine tuning options for **`DocumentPoolEmbeddings`** - we now allow …
> GH-678: Classification improvements

- flair/datasets.py
This PR adds more datasets to the new `flair.datasets` way of loading data. It adds: 
- `IMDB` dataset
- `TREC_50` dataset
It also adds the popular [20newsgroups](http://qwone.com/~jason/20Newsgroups/) classification dataset to Flair. 
Load with: 
```python
import flair.datasets
imdb_corpus = flair.datasets.IMDB()
print(imdb_corpus)
newsgroup_corpus = flair.datasets.NEWSGROUPS()
print(newsgroup_corpus) 
```
> GH-748: add more classification datasets

- setup.py
This mistake is causing issues in my own unit tests, when trying to import utils from my `tests` package Python gets confused and ends up trying to import from Flair's `tests`.
> Actually exclude tests from packaging

- flair/datasets.py
- flair/file_utils.py
- flair/models/text_regression_model.py
This PR fixes a problem with the loss function in the (still beta) `TextRegressor` and adds 4 regression datasets.
You can now train a regression model like this: 
```python
from flair.datasets import WASSA_SADNESS
corpus = WASSA_SADNESS()
print(corpus)
embeddings = OneHotEmbeddings(corpus)
document_embedding = DocumentPoolEmbeddings([embeddings], fine_tune_mode='none')
classifier = TextRegressor(document_embedding)
trainer = ModelTrainer(classifier, corpus)
trainer.train(
f"resources/taggers/test-regression",
mini_batch_size=4,
max_epochs=20,
)
```
> GH-564: regression datasets

- flair/data.py
- tests/test_data.py
Previously, we had different behavior for creating Sentences from empty strings depending on whether or not a tokanizer was used: 
```python
sentence = Sentence('', use_tokenizer=True)
sentence = Sentence('')
```
With this PR, both cases now return an empty sentence and log a warning. Addresses #327
> GH-327: log warning when creating empty sentences

- flair/data.py
- flair/embeddings.py
This PR adds pre-trained `FlairEmbeddings` for more languages, contributed by @stefan-it (details on the models in #614 ).
New languages are: Arabic, Croatian, Danish, Farsi, Finnish, Indonesian, Italian, Hebrew, Hindi and Norwegian. Furthermore the models for Bulgarian, Swedish, Slovenian were updated with models trained on more data. Load with language code, so to load a Hindi model:
```python
fw = FlairEmbeddings('hi-forward') 
bw = FlairEmbeddings('hi-backward') 
```
There are also 2 `FlairEmbeddings` models for _historical_ German, trained over articles from the _Wiener Zeitung_ and the _Hamburger Anzeiger_ respectively.  
```python
fw_hamburger_anzeiger = FlairEmbeddings('de-historic-ha-forward') 
fw_wieder_zeitung = FlairEmbeddings('de-historic-wz-forward') 
```
Closes #614
> GH-614: new language models

- flair/embeddings.py
As per the discussion in #614, we've added back in older versions of Flair embeddings for reproducability. 
Since the list of models/languages is growing quite long (and hopefully will continue to grow), we need to come up with a good versioning mechanism and model zoo overview in the near future.
> GH-614: re-added older LMs with version number

- flair/trainers/trainer.py
So that the test.tsv at the end correspond to the scores of the final_test's predictions.
> change the last test.tsv

- flair/data.py
- flair/models/sequence_tagger_model.py
Hi,
this PR is about issue https://github.com/zalandoresearch/flair/issues/745. It:
- adds the property `tags_proba_dist` to `Token`, which contains a list of `Label`. The list of labels represents the probability distribution over all possible labels for this token.
- modifies `SequenceTagger._obtain_labels` to not only return the most probable label, but in addition a complete list of all possible labels with their respective scores.
The required changes in `SequenceTagger._viterbi_decode` are taken from https://github.com/zalandoresearch/flair/pull/642.
**Disclaimer:**  This is my first PR to the flair project. I'm happy for any feedback or ideas on how to improve this.
> GH-642: Added return probability distribution over all classes

- flair/data.py
- flair/datasets.py
- flair/models/sequence_tagger_model.py
- flair/models/text_classification_model.py
- flair/models/text_regression_model.py
- flair/nn.py
- flair/trainers/trainer.py
This PR introduces a new `DataLoader` class that inherits from PyTorch `DataLoader` and contains optimizations for Flair. Specifically, in cases in which a `Dataset` is in memory, it returns direct pointers to `Sentence` objects of a dataset, allowing us to retain embeddings between epochs in training. This may greatly speed up training for datasets that fit in memory. 
It also modifies the `make_label_dictionary()` method to make use of the DataLoader, to speed up computation (i.e. closes #776), and adds a tqdm progress bar.
> GH-776: DataLoader for in-memory datasets

- flair/embeddings.py
Closes #780 
This PR replaces the `RNNBase` initialization in the `DocumentRNNEmbeddings` with explicit initializations of `LSTM` and `GRU`, addressing the bug found in #780. 
The rnn_type parameter can now only take either 'GRU' or 'LSTM' as values, but no longer 'RNN_TANH' or 'RNN_RELU' which to our knowledge were not used anyway.
> GH-780: explicit initialization of GRU and LSTM

- flair/data.py
- flair/datasets.py
Users sometimes have problems with datasets that contain empty sentences (see #33). We currently issue a warning when an empty sentence gets constructed, but leave the users to filter empty sentences by themselves. 
This PR adds a new function to the `Corpus` object, namely `filter_empty_sentences()`. By calling it, all empty sentences get removed. 
Example: 
```python
corpus = IMDB().downsample(0.001)
print(corpus)
corpus._train += SentenceDataset(Sentence(''))
print(corpus)
corpus.filter_empty_sentences()
print(corpus)
```
> GH-33: remove empty sentences

- flair/models/sequence_tagger_model.py
Closes #778 
The NER germeval model did not give good results when evaluated. This may be because it was trained a long time ago on an old Flair version and some changes since then caused the model to be less effective. We retrained the model with the standard param combination and added it to Flair. 
Results are similar to before (even slightly better at 84.85 F1), but we did not do any parameter sweep or try out any of the new embeddings, so better results are likely possible.
> GH-778: update GermEval model

- resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md
Issue #770 is probably caused by an error in Tutorial 7 in the part about resuming training. 
This pull request contains a fix to the tutorial.
> GH-770 'PosixPath' object is not subscriptable

- flair/trainers/trainer.py
closes #817 
closes #796 
This PR introduces small fixes to the ModelTrainer class. It introduces a new parameter `monitor_test` that by default is set to `False`, meaning that test set evaluation is no longer performed during training (#796). It also changes the logging behavior of the `bad_epochs` parameter to hopefully be more intuitive (#817).
> GH-817: trainer modifications

- README.md
Hi,
this PR adds the following NAACL 2019 papers to the main readme:
* [Pooled Contextualized Embeddings for Named Entity Recognition](https://www.aclweb.org/anthology/papers/N/N19/N19-1078/)
* [FLAIR: An Easy-to-Use Framework for State-of-the-Art NLP](https://www.aclweb.org/anthology/papers/N/N19/N19-4010/)
> readme: add references to new NAACL 2019 papers

- flair/datasets.py
- flair/models/text_classification_model.py
This PR adds another way for loading classification datasets, namely datasets that are in CSV format. You need to pass a column format (like in ColumnCorpus), which indicates which column(s) in the CSV holds the text and which field(s) the label(s).
```python
corpus = CSVClassificationCorpus(
data_folder='path/to/data',
column_name_map={4: "text", 1: "label_topic", 2: "label_subtopic"},
skip_header=True)
```
closes #798
> Gh 798 add csv reader

- flair/embeddings.py
Setting `cuda_device` parameter for `ELMoEmbeddings` to the specification in flair.device
Fixes #823
> Make ELMoEmbeddings read the exact flair.device specification

- flair/embeddings.py
Sometimes it is beneficial to use larger character-based word embeddings. This PR changes the constructor of CharacterEmbeddings class to allow that:
```
embedding = CharacterEmbedding(char_embedding_dim=64, hidden_size_char=64)
```
By default both embedding dimension and hidden state size will be 25, as before.
> GH-833: added parameters to CharacterEmbedding constructor to modify embedding size and hidden state size

- flair/datasets.py
- flair/models/language_model.py
This PR fixes two bugs: 
- CUDA out of memory errors were happening with `FlairEmbeddings` on large sentences due to a cat operation being performed on CUDA. Moved cat to normal memory. This may address #736 
- Error when loading sentences without labels with CSV classification dataset.
> GH-736: minor bug fixes

- flair/__init__.py
- flair/datasets.py
- flair/embeddings.py
- flair/models/sequence_tagger_model.py
- flair/trainers/trainer.py
This PR contains minor fixes on code style and redundancies. 
It also simplifies the implementation of the logging in `ModelTrainer` so that no dummy `Sentence` is required to output the log header, making it easier to add new downstream task models.
The PR also adds updated models for 'pos' and 'chunk' since the old models still used the long-deprecated `CharLMEmbeddings` class (see #797).
> GH-832: fixes in logging and code redundancies

- flair/data.py
- flair/embeddings.py
- requirements.txt
Closes #852 
Use the new `MuseCrosslingualEmbeddings()` class to embed any sentence in one of 30 languages into the same embedding space. Behind the scenes the class first does language detection of the sentence to be embedded, and then embeds it with the appropriate language embeddings. If you train a classifier or sequence labeler with (only) this class, it will automatically work across all 30 languages, though quality may widely vary. 
Here's how to embed: 
```python
embeddings = MuseCrosslingualEmbeddings()
sentence_1 = Sentence("This red shoe is new .")
sentence_2 = Sentence("Dieser rote Schuh ist rot .")
print(sentence_1.get_language_code())
print(sentence_2.get_language_code())
embeddings.embed([sentence_1, sentence_2])
cos = torch.nn.CosineSimilarity(dim=0, eps=1e-6)
for token_1, …
```
> GH-852: Add crosslingual MUSE embeddings

- flair/embeddings.py
- tests/test_embeddings.py
1) a fix for keeping the same order of sentences in the batch in DocumentRNNEmbedding, 
2) initializing the DocumentRNNEmbedding in evaluation mode, 
3) a test for 1
closes #865
> GH-865: keep the same order of sentences in the batch in DocumentRNNEmbedding

- flair/data.py
- flair/datasets.py
- flair/embeddings.py
- flair/hyperparameter/param_selection.py
- flair/models/language_model.py
- flair/models/sequence_tagger_model.py
- flair/models/text_classification_model.py
- flair/models/text_regression_model.py
- flair/nn.py
- flair/trainers/trainer.py
- flair/training_utils.py
- tests/test_model_integration.py
This PR introduces a number of changes to address memory management and slim down some interfaces. 
For **memory management**, it introduces the `embedding_storage_mode` parameter to the `ModelTrainer` class and `predict()` methods. This parameter can be one of 'none', 'cpu' and 'gpu':
- If 'none' all embeddings are deleted after usage - this has lowest memory requirements but means that embeddings need to be recomputed at each epoch of training potentially causing a slowdown. 
- If 'cpu' all embeddings are moved to CPU memory after usage. During training, this means that they only need to be moved back to GPU for the forward pass, and not recomputed so in many cases this is faster, but requires memory. 
- If 'gpu' all embeddings stay on GPU memory after computation. This eliminates …
> GH-857: Memory management and interfaces

- flair/datasets.py
Hi,
as reported in #893 the url for the TREC dataset has changed.
This PR fixes and updates the TREC dataset url.
> GH-893: update url for TREC dataset

- flair/samplers.py
- tests/test_model_integration.py
- train.py
This PR adds a set of Samplers that can be used in the ModelTrainer: 
The `ImbalancedClassificationDatasetSampler` will upsample rare classes and downsample common classes in a classification dataset. It may potentially help with imbalanced datasets. 
The two chunk samplers split a dataset into chunks and shuffle them. This preserves some ordering of the original data while also randomizing the data.
> GH-678: Data Samplers

- flair/embeddings.py
- flair/models/language_model.py
- flair/models/sequence_tagger_model.py
- tests/test_embeddings.py
- tests/test_model_integration.py
Closes #921 
This PR makes FlairEmbeddings task-trainable. This allows users to (a) fine-tune an existing language model on task data and (b) train a new model only on task data.
- You can **fine-tune an existing LM** by simply passing the `fine_tune` parameter in the `FlairEmbeddings` constructor, like this: 
```python
embeddings = FlairEmbeddings('news-foward', fine_tune=True)
```
- You can **task-train a wholly new language model** by passing an empty `LanguageModel` to the `FlairEmbeddings` constructor and the `fine_tune` parameter, like this: 
```python
language_model = LanguageModel(
Dictionary.load('chars'),
is_forward_lm=True,
hidden_size=256,
nlayers=1)
embeddings = FlairEmbeddings(language_model, fine_tune=True)
```
- Also closes #880 by fixing the embedding printout.
- This PR …
> GH-921: fine-tune FlairEmbeddings

- flair/embeddings.py
- flair/models/sequence_tagger_model.py
- flair/models/text_classification_model.py
- flair/models/text_regression_model.py
- flair/nn.py
- flair/samplers.py
- flair/trainers/trainer.py
This PR continues refactoring work from #891 to make interfaces more general and allow for 
- additional atomic types of data points (currently only `Token` and `Sentence`) 
- more diverse downstream tasks (currently only `SequenceTagger`, `TextClassifier` and `TextRegressor`)
The PR also includes `embeddings_storage_mode` as a default parameter in the `.evaluate()` routine, and adds the `step` paramter to the `ExpandingChunkSampler` to control the number of epochs before chunk size is increased.
> GH-891: memory storage

- flair/trainers/language_model_trainer.py
- flair/trainers/trainer.py
In response to https://github.com/zalandoresearch/flair/issues/324, this PR makes use of APEX (https://github.com/NVIDIA/apex) to provide automatic mixed precision training to Flair.
Automatic mixed precision training makes use of both FP32 and FP16 precisions where appropriate. FP16 operations can leverage the Tensor cores on NVIDIA GPUs (Volta, Turing or newer architectures) for much improved throughput.
Automatic mixed precision training can be enabled via an appropriate flag passed to the trainer:
```
trainer: ModelTrainer = ModelTrainer(tagger, corpus)
trainer.train('resources/taggers/example-ner',
learning_rate=0.1,
mini_batch_size=32,
max_epochs=150,
apex=True)
```
**How mixed precision works**
Mixed precision is the use of both float16 and …
> Automatic mixed precision

- flair/datasets.py
Closes #940 
Fixes the problem that in certain column formats, notably WNUT-17, lines that begin with a hash tag are not in fact comments, but words that begin with a hash tag.
> GH-940: Hashtags in corpus

- flair/trainers/language_model_trainer.py
Closes #960 
You can now set the number of workers in the `LanguageModelTrainer`, like so: 
```python
trainer = LanguageModelTrainer(language_model, corpus)
trainer.train(
"resources/LMs/example-lm",
sequence_length=256,
num_workers=12,
)
```
> GH-960: make num workers a parameter

- flair/embeddings.py
- requirements.txt
- tests/test_transformer_embeddings.py
Hi,
this PR updates the old `pytorch-pretrained-BERT` library to the latest version of `pytorch-transformers` to support various new Transformer-based architectures for embeddings.
A total of 7 (new/updated) embeddings can be used in Flair now:
```python
from flair.embeddings import (
BertEmbeddings,
OpenAIGPTEmbeddings,
OpenAIGPT2Embeddings,
TransformerXLEmbeddings,
XLNetEmbeddings,
XLMEmbeddings,
RoBERTaEmbeddings,
)
bert_embeddings = BertEmbeddings()
gpt1_embeddings = OpenAIGPTEmbeddings()
gpt2_embeddings = OpenAIGPT2Embeddings()
txl_embeddings = TransformerXLEmbeddings()
xlnet_embeddings = XLNetEmbeddings()
xlm_embeddings = XLMEmbeddings()
roberta_embeddings = RoBERTaEmbeddings()
```
Detailed benchmarks on the downsampled CoNLL-2003 NER dataset for English can be found in #873 . This …
> GH-873: PyTorch-Transformers update

- flair/datasets.py
- resources/docs/TUTORIAL_6_CORPUS.md
Proposed solution to #966: add `fmtparams` to `CSVClassificationCorpus`
> GH-966 : better handling of CSV files

- flair/embeddings.py
- resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md
- tests/test_transformer_embeddings.py
Hi,
this PR adds the possibility to pass a model path to the PyTorch-Transformer based embeddings.
This is highly needed when Flair users want to use own trained models, like e.g. an own trained XLNet model.
The argument name is changed from `model` to `pretrained_model_name_or_path` (as it is named in `pytorch-transformers`).
> PyTorch-Transformers: add possibility to pass model path to embeddings

- flair/models/sequence_tagger_model.py
- flair/trainers/trainer.py
- requirements.txt
Adds a number of simplifications and bug fixes for the `SequenceTagger`: 
- Fixes `SequenceTagger` with `use_rnn=False` which previously threw shape error
- `SequenceTagger` no longer sorts sentences by length during forward pass since as of torch 1.1. `pack_padded_sequence` no longer requires sorting
- bumpts min torch version to 1.1 so that `pack_padded_sequence` with `enforce_sorted=False` works
-  removes unneeded code which somehow was still in there
- minor cleanup in logging
> Simplified sequence tagger

- flair/embeddings.py
- requirements.txt
- resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md
- tests/test_transformer_embeddings.py
Hi,
this PR updates the `pytorch-transformers` version to *1.1.0*. With the new `pytorch-tranformers` release, RoBERTa was integrated. 
So this PR removes the old RoBERTa implementation, that downloads and uses the model from `torch.hub` and replaces it with the `pytorch-transformers` implementation.
I made a comparison between the `torch.hub` and the `pytorch-transformers` implementations and found no difference on the full CoNLL-2003 NER corpus for English (F-Score of 92.12 could be achieved).
The PR also updates the documentation and unit tests for RoBERTa.
> GH-1000: PyTorch-Transformers update

- flair/datasets.py
There is a mistake inside `_download_wikiner` for `WIKINER_GERMAN` where it downloads `en` instead of `de`.
> Fix download URL for German WikiNER in datasets

- flair/embeddings.py
When allennlp is installed, but there is an issue with its installation (for example, the version of `protobuf` installed is too old), Flair produces the unhelpful error message "The library "allennlp" is not installed! To use ELMoEmbeddings, please first install with "pip install allennlp". These changes limit the scope of errors caught when loading `allennlp` in `embeddings.py` to only include `ModuleNotFoundError`s. This allows errors in actually loading the installed `allennlp` module to be displayed to the user.
Let me know if this PR needs any changes, or if Python 2 compatibility is needed. I made the PR without creating an issue since it's such a small change, but I'd be happy to discuss implementation details or anything else 😊
Thanks for making Flair! 😄
> Show allennlp import errors when installed

- flair/training_utils.py
I fixed [issue#718](https://github.com/zalandoresearch/flair/issues/718), I think the problem is that the log file is not opened with 'utf-8'.
> Fixed logging unicode encoding error.

- flair/embeddings.py
Hi,
the loading/saving logic for Flair models changed quite a while ago, so it is no longer possible to use another pickle framework. The `ELMoTransformerEmbeddings` could only be loaded and saved using `dill`.
This PR temporarily deprecates the `ELMoTransformerEmbeddings` implementation until a better solution is found!
> embeddings: deprecate ELMoTransformerEmbeddings

- resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md
Hi,
this PR fixes the number of layers for several XLM models (sync with latest PyTorch-Transformers doc) and some broken hyperlinks :)
> Documentation: minor fixes

- flair/models/language_model.py
Hello, about [issue #718](https://github.com/zalandoresearch/flair/issues/718), I did more tests.
On my Ubuntu computer, if terminal is not working with utf-8, it may get same problem.
Therefore, I make function `generate_text` output text encode to utf-8 in `language_model.py`.
And then, it will work well at runtime, but the log file will been written a lot of unicodes,
like below,
`(b'\n \xca\x95\xe6\x99\x82  y \xe7\xaa\xa0  \xe5\x85\xb1\xe5\x9c\x8b \xe9\x80\xa0 \xe5\x9b\x9b \xe8\xaa\x9e \xf0\x90\xad\xae \xe9\xab\x98\xe5\xad\xb8\xe6\x96\xbc \xe7\xb4\x80 \xe7\xbd\xbe \xe5\x8c\x97 \xe5\x85\x8b \xe9\x80\x8d\xe5\x85\x8b ah\xe5\x8f\x83 ..., 7.52521240234375)`
If you want to write correct word in log file.
You should do below,
```
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
```
If I find a …
> Fixed unicode error when terminal encoding is not utf-8

- flair/models/sequence_tagger_model.py
PR #1016 has introduced a new parameter to avoid computing scores for each tag and accelerating inference.
Now, when `all_tag_prob=False` during NER inference, predictions are not saved in `Token.tags`... so it is like nothing happened.
It is because of the `zip()` function taking multiple lists but if they have different sizes, the length of the shortest is taken as reference. When `all_tag_prob` is `False`, `all_tags` list is empty, so `zip` function acts like all of its parameters/lists are empty, and no iteration happens in the for loop saving results in `Token` objects.
It is a tricky bug as when you test the same sentence with `all_tag_prob=True` and then `all_tag_prob=False` the inference is working... I have not understood why.
The fix is to simply divide operations in 2 parts …
> [NER] fix inference bug introduced by #1016 (tags are not saved in token object)

- flair/embeddings.py
Hi,
this PR adds support for the large ELMo model, that was trained on 5.5B tokens.
It can be used with:
```python
from flair.embeddings import ELMoEmbeddings
embeddings = ELMoEmbeddings(model = "large")
s = Sentence("Berlin and Munich .")
embeddings.embed(s)
```
Results for ELMo on the complete CoNLL-2003 dataset (English, NER):
| Model | Dev | Test
| -------- | ----- | -----------
| ELMo (original) | 95.39 | 92.11
| ELMo (large, 5.5B tokens) | 95.68 | **92.15**
(notice: target branch for this PR is `GH-563-prepare-release-0-4-3`)
> Embeddings: add support for large ELMo model

- flair/data.py
Sometimes, `start_pos` in `Token` is set to None.
This is for instance the case when loading a `Corpus` in columnar format.
In those cases `while t.start_pos != pos` from `to_original_text` method is always True.
This fix manages this case.
Another solution would be to just throw an Exception. Let me know what you prefer. In this case it may be good to forbid to have `start_pos` being `None` in any case and to rewrite `Corpus` class. May be to put in another PR
> [Sentence] Fix infinite loop bug

- flair/embeddings.py
- resources/docs/embeddings/TRANSFOMER_EMBEDDINGS.md
Hi,
this PR adds support for `DistilBERT`, a distilled version of BERT.
The following example shows how to use it in Flair:
```python
from flair.embeddings import BertEmbeddings
embeddings = BertEmbeddings("distilbert-base-uncased")
s = Sentence("Berlin and Munich are nice cities .")
embeddings.embed(s)
for token in s.tokens:
print(token.embedding)
print(token.embedding.shape)
```
Please also refer to this great [blog post](https://medium.com/huggingface/distilbert-8cf3380435b5) about distillation 🤗 🤗
I made [some experiments](https://github.com/stefan-it/flair-experiments/blob/master/conll2003-ner-english/README.md) on the full CoNLL-2003 corpus. `DistilBERT` (with this PR-ready version) is only -0.35% behind the BERT (base, uncased) model.
**Notice**: to …
> GH-1041: add support for DistilBERT

- flair/models/language_model.py
- flair/models/sequence_tagger_model.py
- flair/training_utils.py
Viterbi seems to be the bottle neck of the inference part when GPU is used with CRF.
Here we simply move the computation of this part from GPU to CPU as the operations are not GPU optimized.
On my 2080TI with I7 (6 real cores), on the same data / same model, I went from 1mn 33s to 63 seconds inference time.
I have not made any test on other hardware but I expect perf improvement to be similar.
Moreover, this open the door to more optimizations as it removes the "lock" on GPU (we can easily do a better job at multithreading the process than Pytorch is currently doing), plus the same performance boost can probably be reproduced on the training part.
> [NER] improve inference perf by > 40% on GPU when CRF is used

- flair/embeddings.py
- flair/models/sequence_tagger_model.py
Hi, 
transpose_() is in-place version of transpose()
https://pytorch.org/docs/stable/tensors.html#torch.Tensor.transpose
You don't need asign althogh it makes no errors.
I reccomend use transpose() as like other files in flair.
> Fix transpose_() to transpose()

- flair/models/sequence_tagger_model.py
- tests/test_model_integration.py
Like PR #1038, this is an optimization of the Viterbi decoding.
On my French dataset, using the same setup than #1038 , I went from 63 seconds to 45 seconds (`all_tag_prob` set to False).
This time, no easy trick but careful rewriting of Viterbi decoding using Numpy only and lots of vectorization.  It appeared than Pytorch Tensor is both slightly slower on CPU and offers less opportunities of vectorization and broadcasting.
2 interesting points:
- this optimization will also benefit to users inferring on CPU only
- the decrease in processing time is much stronger when `all_tag_prob` is set to True
FYI, I tried to parallelize with Ray and Numba.
Ray adds too much overhead compared to the time to process one Sentence and batching the minibatch introduces too much complexity for very small …
> Another 28% decrease in inference time in NER on GPU when CRF is used

- flair/__init__.py
about [issue#1059](https://github.com/zalandoresearch/flair/issues/1059)，I think this problem is changing the root logging in `flair/__init__.py`.
I think set logging.config should not change root logging and only use `logging.getLogger("name of module")`, like this `logging.getLogger("flair")`.
and in my testing,
issue#1059 is fixed, in my computer.
Maybe I removed setting root logging in `flair/__init__.py` is too rash, we can talk about better solution for this issue.
> fixed issue with changing the root logging

- flair/datasets.py
- flair/models/sequence_tagger_model.py
- flair/models/similarity_learning_model.py
- flair/models/text_classification_model.py
When CRF is not used, data were slow down by a for loop.
In this little refactoring, this part have been vectorized.
I kept everything on Pytorch Tensor.
As always, I am interested in your timings on V100 :-)
On my 2080 TI, without refactoring on French data with a model trained without CRF, before I got 63 seconds, and after modification I get 43 seconds.
> Decrease inference time of 30% when not using CRF for seq tagging

- flair/embeddings.py
- flair/models/sequence_tagger_model.py
- flair/nn.py
Closes #1073 
This PR changes `WordDropout` and `LockedDropout` to be robust to `batch_first` mode. For `LockedDropout` this means adding a boolean parameter `batch_first` to the constructor that by default is set to `True`. 
The `WordDropout` is now implemented differently as the previous version was a 'lcoked' word dropout that would always drop the same index words across a mini-batch. Now, words are dropped fully at random. Some initial experiments show that this improves downstream task training. 
The PR also removes the transpose operations in the `SequenceTagger` and the `DocumentRNNEmbeddings` and removes the sorting logic from the `DocumentRNNEmbeddings`.
> GH-1073: batch first

- flair/data.py
- flair/embeddings.py
- flair/training_utils.py
This PR makes minor modifications to the `.to()` method of the `DataPoint` base class and all implementing classes, namely adding the option of moving a data point tensor to pinned memory. Pinning a tensor is a one-time cost but then allows all subsequents GPU tensor copy operations to work faster. When training a model with `embeddings_storage_mode = 'cpu'`, we at each epoch move tensors from CPU to GPU, so this PR increases overall training speed (closes #1079).  
This PR also adds a check if the `.to()` operation is even necessary (not needed if a tensor is already on the relevant device), leading to a small increase in training speed.
> GH-1079: Increase CPU training speed by pinning tensors

- flair/data.py
- flair/embeddings.py
- flair/models/sequence_tagger_model.py
- flair/visual/ner_html.py
- tests/test_visual.py
Set an embedding LRU cache of Tensor of word embeddings.
This approach avoid to convert most used Gensim embeddings to Pytorch Tensor and even more important to avoid to transfer from computer RAM to GPU Ram (this is a slow operation).
Because of zipf law, the effect of such caching approach are magnified.
LRU cache is set to 10000 because it s very small and still provide most of the performance boost compared to loading all embeddings in GPU Ram. A 1000 embedding LRU cache is slightly less performant on my own dataset.
A second little optimization is to replace a call of `unsqueeze` on each token followed by a `cat` by a single call of `stack`.
Time to process 100 French documents decreased from 33s to 26s with this PR.
For what it worths, Spacy takes exactly the same time (26s) on my …
> Set a LRU cache for word embeddings for a decrease of 20% of inference time

- flair/embeddings.py
fix a bug about "embedding_length" of CharacterEmbedding class (#1083)
> GH-1083: fix CharacterEmbeddings

- flair/data.py
- flair/embeddings.py
- flair/models/sequence_tagger_model.py
Instead of concatenating token representations at the token level (row approach) and then perform the sentence tokenization, we make the process lazy by retrieving each token representation before concat, reorganize them in nested lists and perform the concat per column (all Word embeddings are concatenated in one operation, then all LM are concatenated in one op), then columns (each column being a kind of representation) are concatenated together.
The idea is because there are much more tokens per sentence than different kind of representation per token, there are less concatenation operations performed.
On Conll2003, 40 -> 36s.
GPU use whole time over 70% (when it reaches 100 there may be some improvements remaining, but the main bottleneck will be the model itself).
Let me know if your …
> Reduce the number of concatenation for 10% inference time reduction

- resources/docs/TUTORIAL_2_TAGGING.md
Changing German -> English as the subsequent sentences are in English.
> Fixing a typo in Tutorial 2

- flair/data.py
close https://github.com/zalandoresearch/flair/issues/1104
Provide a constant 1s improvement on conll 2003. (26s -> 25s, I am now using batch of 256, because since I don't know when, it matters on inference speed, AFAIK on the last released version it didn't on my GPU)
The best thing is that it makes the global variable more useful :-)
> Little optimization on device check

- flair/models/sequence_tagger_model.py
closes #1100 
Adds the option of choosing `rnn_type` when initializing the `SequenceTagger`.
> GH-1100: add option to set rnn_type to SequenceTagger

- flair/embeddings.py
closes #1092 by adding a number to each embedding name to keep ordering fixed across different setups.
> GH-1092: simple mechanism to keep embedding order in StackedEmbeddings

- flair/trainers/trainer.py
Fixes the step problem in the learning rate finder.
closes #986 
closes #982
closes #1108 
```python
trainer: ModelTrainer = ModelTrainer(tagger, corpus)
learning_rate_tsv = trainer.find_learning_rate(
'resources/taggers/example-ner',
'learning_rate.tsv',
)
```
> GH-986: fix batch step in learning rate finder

- flair/models/language_model.py
This optimization is based on non blocking memory transfer on flair LM embeddings plus some small change in operation order so memory transfer goes during the time GPU is computing stuff.
It really works only when there are several chunks.
I can't measure any change on CONNL03 times (there are max 2 chunks on first batches with chunk size setup to 512) but on my French dataset with long sentences I have up to 8 chunks (plus many 3 chunks batches) and I can measure a constant 1 second decrease, which is significant as the full process takes 13 seconds (14 before), so a 7% decrease.
Of course impact of this optimization would increase with chunk size decreasing (because it would create more chunks) but it would impact model accuracy, so... I didn't measured it.
More importantly, the main …
> lazyness for a small optimization

- resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md
Changed two spots in Tutorial 7 to more accurately reflect what the example model is intended to do (NER vs sentence classification).
> Changing text to reflect model type

- flair/models/language_model.py
- flair/models/sequence_tagger_model.py
Reorganize embeddings + add some padding such a way we have only one call to concat (and no stack operation). Padding is preallocated to limit memory allocation. Get a constant 1 second inference time reduction on CONLL 2003 on 2080TI (25 -> 24s).
Had no measurable effect on my French dataset.
Good thing, the code is easier to read :-)
Nb: not related but I made a mistake in my measures... unfortunately memory transfer is not the main remaining bottleneck, I measured some synchronization operation which was happening before memory transfer. now I am using `;CUDA_LAUNCH_BLOCKING=1 ` before using cProfile instead of trying to be smart and calling synchronize manually here and there... Another thing, little functions called million of times appears slower than they are with the profiler...
> Another strong reduce of concatenation for a small optimization (-4% inference time)

- flair/embeddings.py
Simple optimization.
Brings a constant 1s inference time on French data (characterized by very long sentences == many tokens per Sentence) -> from 13 to 12s
No measurable effect on Connl 2003.
> Reduce detach calls on Flair embeddings 

- flair/models/sequence_tagger_model.py
- flair/trainers/trainer.py
The paper [Don't Decay the Learning Rate, Increase the Batch Size](https://arxiv.org/abs/1711.00489) makes the case for increasing the batch size over time instead of annealing the learning rate. 
This PR adds the possibility to have arbitrarily large mini-batch sizes with an accumulating gradient strategy (closes #1072). It introduces the parameter `mini_batch_chunk_size` that you can set to break down large mini-batches into smaller chunks for processing purposes. 
So let's say you want to have a mini-batch size of 128, but your memory cannot handle more than 32 samples at a time. Then you can train like this: 
```python
trainer = ModelTrainer(tagger, corpus)
trainer.train(
"path/to/experiment/folder",
mini_batch_size=128,
mini_batch_chunk_size=32,
)
```
Because we now can arbitrarly …
> GH-1072: Batch-growth annealing

- flair/__init__.py
The directory `.flair` is created in the home directory, which is currently determined with `~` and `os.path.expanduser()`.
The [`home()`](https://github.com/python/cpython/blob/3368f3c6ae4140a0883e19350e672fd09c9db616/Lib/pathlib.py#L252-L281) classmethod of a `pathlib.Path` object determines the home directory via the `$HOME` environment variable --- which can easily be modified (makes sense, for example, on an Elastic Beanstalk instance where there is no user and no home folder).
However, I think `pathlib` is widely used in this beautiful library, so it would even make sense for consistency reasons :)
> Use $HOME instead of ~ for cache_root

- flair/datasets.py
- flair/models/sequence_tagger_model.py
- resources/docs/TUTORIAL_2_TAGGING.md
Add a new kind of dataset for strings and a dataloader to load them. That way new user wanted to make test doesn't need to understand how to build a Sentence. Plus it's more convenient to use in general for advanced users.
Has no impact on speed, however multiprocessing (to tokenize during GPU is working) makes things slower so it's kept disabled.
> Accept string as input in NER predict

- flair/embeddings.py
This PR adds the multilingual Flair embeddings trained by @stefan-it for 300 (!!!) languages. See #1099 for more info on these embeddings and [this repo](https://github.com/stefan-it/flair-lms#multilingual-flair-embeddings) for more details.
It replaces the old multilingual Flair embeddings trained for 6 languages. Load them with: 
```python
embeddings_fw = FlairEmbeddings('multi-forward')
embeddings_bw = FlairEmbeddings('multi-backward')
```
Closes #1099
> GH-1099: add multilingual Flair by @stefan-it

- flair/data.py
- flair/models/language_model.py
- flair/models/sequence_tagger_model.py
Optimize the way padding is done by reducing the number of dictionary call.
Remove the conversion to UTF-8, and take care of old models in old format.
In the future, the conversion may be removed safely.
close https://github.com/zalandoresearch/flair/issues/1133
@alanakbik finally I did both, change in dictionary deserialization and change inside the class itself.
CONNL 2003 from 24s to 23s (-4%)
French dataset from 12s to 11s (-8%)
> Optimize character to index conversion for a 4% decrease on CONNL 2003

- flair/data.py
- flair/models/sequence_tagger_model.py
When run with CPU storage on a computer with CUDA / GPU, embeddings may not be on the right storage during training.
I don't know why, but it was not crashing on my own train task (French dataset)
`get_embedding` uses `get_each_embedding` now to get the same security.
`get_subembedding` has been deleted because it is not used in the project and would require to generalize get_embedding, implying more complexity.
The real issue I just realized is that Travis was not catching this bug because it doesn't run integration tests on GPU, and in this case it was a device storage issue. I don't know how to improve that.
> fix get_each_embedding when storage embedding is set to CPU

- flair/data.py
This PR adds the two multilingual character dictionaries computed by @stefan-it. 
Load with 
```python
dictionary = Dictionary.load('chars-large')
print(len(dictionary.idx2item))
dictionary = Dictionary.load('chars-xl')
print(len(dictionary.idx2item))
```
Closes #804 - big thanks to @stefan-it!
> GH-804: add two multilingual character dictionaries

- flair/datasets.py
- flair/embeddings.py
This PR makes some small modifications to `DocumentRNNEmbeddings` and the `ClassificationDataset`. 
The `DocumentRNNEmbeddings` are modified to have the same dropout logic as the SequenceTagger, consisting of dropout, locked dropout and word dropout. The `ClassificationDataset` now automatically samples a test set if only a train dataset is provided.
> Classification changes

- flair/samplers.py
- flair/trainers/trainer.py
This PR adds a `FlairSampler` interface to better enable passing custom samplers to the `ModelTrainer`. 
For instance, if you want to always shuffle your dataset in chunks of 5 to 10 sentences, you provide a sampler like this: 
```python
trainer: ModelTrainer = ModelTrainer(tagger, corpus)
trainer.train('path/to/experiment/folder',
max_epochs=150,
sampler=ChunkSampler(block_size=5, plus_window=5)
)
```
> Sampler refactor

- resources/docs/embeddings/FLAIR_EMBEDDINGS.md
Hi,
this PR adds a description and affilication for the multi-forward embeddings, that were trained on the [JW300 corpus](http://opus.nlpl.eu/JW300.php).
> embeddings: add affiliation for multi-forward (JW300) embeddings

- flair/embeddings.py
- requirements.txt
- resources/docs/embeddings/TRANSFORMER_EMBEDDINGS.md
- tests/test_transformer_embeddings.py
Hi,
the latest version 2.0.0 of `transformers`, formerly known as `pytorch-transformers` and `pytorch-pretrained-bert`, has been released today 🎉
See changelog [here](https://github.com/huggingface/transformers/releases/tag/v2.0.0).
No breaking API changes.
This PR updates imports and documentation.
Flair-related improvements:
* [RoBERTa/GPT2 tokenization](https://github.com/huggingface/transformers/issues/1196)
> GH-1156: PyTorch-Transformers -> Transformers

- resources/docs/embeddings/TRANSFORMER_EMBEDDINGS.md
Hi,
with the latest `transformers` version it is also possible to use the large GPT-2 model in Flair, see #1166  
This PR adds the large GPT-2 model to the documentation.
> GH-1166: add large GPT-2 model to documentation

- flair/models/sequence_tagger_model.py
This PR adds support for Danish POS and NER thanks to @AmaliePauli! 
Use like this: 
```python
sentence = Sentence("København er en fantastisk by .")
ner_tagger = SequenceTagger.load('da-ner')
ner_tagger.predict(sentence)
print(sentence.to_tagged_string())
pos_tagger = SequenceTagger.load('da-pos')
pos_tagger.predict(sentence)
print(sentence.to_tagged_string())
```
Closes #1176
> GH-1176: add NER and POS for Danish by @AmaliePauli

- flair/data.py
- flair/datasets.py
- flair/embeddings.py
fixed [issue1131,](https://github.com/zalandoresearch/flair/issues/1131)
This is because in embedding.py, token.text is an empty string.
The empty string in token.text is because the training data contains [C1 control characters](https://en.wikipedia.org/wiki/C0_and_C1_control_codes).
So, I added a condition to check if token.text is not empty and make C1 control char to correct char.
about C1 control char fixed [stackoverflow ref](https://stackoverflow.com/a/6625625)
> fixed string index out of range in embeddings.py

- flair/embeddings.py
> GH-1190 Fix OneHotEmbeddings

- flair/datasets.py
This PR introduces the option for reading entire documents into one Sentence object for sequence labeling. This option is now supported for `CONLL_03`, `CONLL_03_GERMAN` and `CONLL_03_DUTCH` datasets which indicate document boundaries.
Here's how to train a model on CoNLL-03 on the document level: 
```python
corpus = CONLL_03(in_memory=True, document_as_sequence=True)
tag_type = 'ner'
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
tagger: SequenceTagger = SequenceTagger(
hidden_size=256,
embeddings=WordEmbeddings('glove'),
tag_dictionary=tag_dictionary,
tag_type=tag_type,
)
trainer: ModelTrainer = ModelTrainer(tagger, corpus)
trainer.train(
'path/to/your/experiment',
mini_batch_size=2,
)
```
> GH-1193: Document-level sequence labeling

- flair/datasets.py
This is my second pull request ever on GitHub. I hope it works this time!
I have implemented a MongoDataset class in Flair for reading text classification data from a Mongo database collection using queries.
The following simple example shows how the MongoDataset class could be used:
query = {'Län': "Stockholms län"}
kwargs = {
'host': 'localhost',
'port': 27017,
'database': 'rosenberg',
'collection': 'book',
'text_field': 'Beskrivning',
'categories_field': ['Län', 'Härad', 'Tingslag', 'Församling', 'Plats']
}
train_dataset: MongoDataset = MongoDataset(query, **kwargs)
> MongoDataset for reading text classification data from a Mongo database

- flair/trainers/trainer.py
PR implements option to evaluate on the subset of train split via parameters of trainer function:
* `eval_on_train_fraction`: The fraction of train data to do the evaluation on.  If 0. the evaluation is not performed on fraction of training data. If 'dev' the size is determined from dev set size.
* `eval_on_train_shuffle`: If `True` the train data fraction is determined on the start of training and kept fixed during training, otherwise it's sampled at beginning of each epoch.
> GH-1198: Added option to evaluate on the (subset of) train split.

- .travis.yml
- Pipfile
- flair/data.py
- requirements.txt
- tests/test_data.py
This PR introduces support for Japanese tokenizer.
Japanese is a language that needs to segment a sentence into words.
It is done by several morphological analyzers such as MeCab, Kytea, Sudachi, and so on.
Users may want to use a different analyzer to compare analyzers and
select which tokenizer to use. (researcher may want to do this)
In this case, users have to pre-tokenize whole sentences for each analyzer
to feed into `flair.data.Sentence`, which is a little bit of cost consuming.
Currently, I'm developing `tiny_tokenizer` (https://github.com/himkt/tiny_tokenizer),
which is a wrapper of these morphological analyzers.
`tiny_tokenizer` unifies an interface to create `Tokenizer` and tokenize API.
Introducing `tiny_tokenizer`, we can deal with various morphological analyzers.
This is the …
> Add Japanese tokenizer

- flair/data.py
Fix [issue#1188](https://github.com/zalandoresearch/flair/issues/1188)
This issue is about tokenizer of segtok library.
In segtok, `someword`+ `n't`, e.g. `don't`, `didn't`...
It will be tokenized as `someword` and `n't`.
However, if user has split it, it will insert empty between `someword` and `n't`.
Example:
"do n't" -> "do", "", "n't"
"did n't" -> "did", "", "n't"
**To Reproduce**
```python
from flair.data import segtok_tokenizer
text = r'do n’t'
tokens = segtok_tokenizer(text)
print(tokens) #[Token: do, Token: , Token: n’t]
```
This commit fix this problem.
> Fix tokenizer insert empty token to sentence object

- flair/embeddings.py
Add BPEmbSerializable back in, otherwise some serialized models no longer work. This needs to be removed in 5.0.
> Add BPEmbSerializable back in for serialized models

- flair/embeddings.py
I tried to make a pull request before, but failed twice, since I couldn't do a proper merge from my master. Thus, I killed my fork and created a new one. Hopefully it will work better this time.
I have added hash embeddings using the hashing trick, see for example https://en.wikipedia.org/wiki/Feature_hashing#Feature_vectorization_using_hashing_trick
This code snippet explains how the suggested feature could be used:
from flair.embeddings import HashEmbeddings
word_embedding = HashEmbeddings()
sentence = corpus.train[0]
word_embedding.embed(sentence)
for token in sentence:
print(token)
print(token.embedding)
> Added hash embeddings with hashing trick

- .travis.yml
- flair/data.py
- flair/datasets.py
- flair/embeddings.py
- flair/models/sequence_tagger_model.py
- flair/models/similarity_learning_model.py
- flair/trainers/trainer.py
- flair/visual/training_curves.py
- requirements.txt
- tests/test_data.py
- tests/test_transformer_embeddings.py
We want to keep list of dependencies of Flair generally small to avoid errors like #1245. 
This PR removes some dependencies that are each only used for one particular feature, namely: 
- `ipython` and `ipython-genutils`, only used for visualization settings in iPython notebooks 
- `tiny_tokenizer`, used for Japanese tokenization (replaced with instructions for how to install for all users who want to use Japanese tokenizers)
- `pymongo`, used for MongoDB datasets (replaced with instructions for how to install for all users who want to use MongoDB datasets)
It also temporarily pins the version of `python-dateutil` which comes in through the `bpemb` and `transformers` dependencies and currently breaks if its version exceeds 0.2.8 (see …
> GH-1245: slim down dependency tree

- flair/embeddings.py
- requirements.txt
This fixes the problem of having `torchvision` in `requirements.txt`. Now it is loaded only when needed.
> GH-1298: removed torchvision from requirements

- flair/embeddings.py
- requirements.txt
- resources/docs/embeddings/TRANSFORMER_EMBEDDINGS.md
- tests/test_transformer_embeddings.py
Hi,
this PR adds support for the recently proposed French language model: CamemBERT.
Thanks to the awesome 🤗/Transformers library, CamemBERT can be used in Flair like in this example:
```python
from flair.embeddings import CamembertEmbeddings
embedding = CamembertEmbeddings()
sentence = Sentence("J'aime le camembert !")
embedding.embed(sentence)
for token in sentence.tokens:
print(token.embedding)
```
PR comes with:
I'll add an evaluation on WikiNER soon. Closes #1276.
> Add support for CamemBERT embeddings

- .travis.yml
- README.md
- flair/visual/training_curves.py
- requirements.txt
- setup.py
- tests/test_embeddings.py
- tests/test_hyperparameter.py
- tests/test_language_model.py
- tests/test_model_integration.py
Relax requirements so that installation on Google Colab works without having to restart the runtime. Also removes tkinter requirement since this does not work on systems that don't have it.
This PR temporarily removes black formatting requirement from travis to simplify PRs and see how this affects formatting.
> relax version requirements for Colab installation

- flair/trainers/trainer.py
Now logs after multiples of `modulo` batches rather than 1, 1+`modulo`, etc
Prevents samples/sec being too large by factor of `modulo` for batch_no 0 and division by zero crash if 0th batch is too quick.
> Fix off-by-one error in progress logging 

- flair/embeddings.py
- requirements.txt
- resources/docs/embeddings/TRANSFORMER_EMBEDDINGS.md
Hi,
this PR updates the 🤗/Transformers library to the latest 2.3 version 😊
Changes:
* Support for ALBERT models 
* Support for XLM-RoBERTa, a large multi-lingual language model trained on 2.5T text
* Tokenizer fixes
* Documentation updates (for maintainability: list of all pretrained models is replaced by a link to the Hugging Face documentation)
**Note**: Results with XLM-R could be worse than fine-tuned models with Transformers library (tested with CoNLL-2003 for English, performance diff: 1.16%)
> Transformers 2.3 update

- flair/embeddings.py
Issue #1270 reports a CUDA out of memory issue that appeared for PooledFlairEmbeddings in 0.4.4. The likely reason is that the new version stored the embedding memory on CUDA instead of normal memory. 
This PR fixes this so that embedding memory is stored on regular memory.
> GH-1270: fix memory issue in PooledFlairEmbeddings

- flair/embeddings.py
Another attempt at solving #1270 - memory pools are explicitly sent to CPU so that the pools do not eat up CUDA memory.
> GH-1270: explicitly send pools to CPU memory

- flair/file_utils.py
Use "rb" rather than "r+b" and specify access=mmap.ACCESS_READ
I would like to be able to read model files on a read-only share but current code crashes with permissions problems - this fixes for me
> Make load_big_file work with read-only file

- flair/models/language_model.py
fixed [issue #1358 ](https://github.com/flairNLP/flair/issues/1358), [issue #1359 ](https://github.com/flairNLP/flair/issues/1359).
[1.4.0 RNN](https://pytorch.org/docs/stable/_modules/torch/nn/modules/rnn.html)
[1.3.1 RNN](https://pytorch.org/docs/1.3.1/_modules/torch/nn/modules/rnn.html)
The problem is that torch's RNN has a new attribute, _flat_weights_names in 1.4.0.
So I checked the version and if the version is 1.4.0, try set _flat_weights_names attribute for RNN base layer.
I only tried using the "ner-fast" and "ner" model on Windows.
Maybe you can help me try more model on Unix.
If there are problems with other models, please let me know.
I will try to fix it.
> fixed new RNN format for torch 1.4.0

- flair/data.py
- tests/test_data.py
I change the name of the library used in flair for Japanese tokenizer.
The name of the library is `tiny_tokenizer`, which is renamed to `konoha`.
GitHub repo: [here](https://github.com/himkt/konoha)
Since I didn't introduce any breaking changes,
flair should work well by simple renaming.
> Rename tiny_tokenizer to konoha

- flair/datasets.py
Set `whitespace_after` in `UniversalDependenciesDataset`, so `to_plain_string` method is returning original sentence.
> set whitespace_after in UniversalDependenciesDataset

- flair/models/sequence_tagger_model.py
- flair/models/text_classification_model.py
- flair/trainers/trainer.py
- flair/training_utils.py
Add possibility for including class weights in cross-entropy loss (when not using CRF) and using F-Beta as the evaluation metric
> GH-1344: Prioritizing classes

- flair/embeddings.py
#1266 
Currently we call `.cpu()` and `detach()` in for loop on a per-token basis.  AFAIK, this is redundant because when we assign the embedding to the token, we will allocate it to the right device/detach it as necessary.
As I outlined in the issue and the associated [gist](https://gist.github.com/shoarora/a8aa6ac39ee814b667907ced4bfda6c9), this will dramatically improve runtime, as we'll move to `cpu()` _after_ we've aggregated all the desired embeddings.  
I didn't receive confirmation on my issue that this functionality works the way that I understand it.  Hopefully, I'm not missing a key piece of the implementation that actually makes this required.
> GH-1266 Remove redundant cpu() and detach() calls

- flair/data.py
- flair/datasets.py
This PR does some small refactorings on `flair.datasets` for easier code legibility and fewer redundancies. All in all, this PR removes about 100 lines of code.
- Moves the default sampling logic from all corpora classes to the parent `Corpus` class. You can now instantiate a `Corpus` only with a train file which will trigger the sampling. 
- Moves the default logic for identifying train, dev and test files into a dedicated method to avoid duplicates in code.
> Refactor datasets for code legibility

- flair/embeddings.py
- flair/models/language_model.py
- replace +cpu part of the version with empty string during access
> GH-1388: fix issue where flair was crashing for cpu only version of pytorch

- flair/datasets.py
When loading a "not-in-memory" corpus we don't need to construct the whole sentence, because we will read the sentence when necessary in `get_item`.
> GH-1414: Improve performance for loading not-in-memory corpus

- flair/embeddings.py
Torch concatenate throws error if we try to concatenate "GPU" tensors with "CPU" tensors. This is happening in  Line 3151. `word_embeddings_tensor = torch.cat(word_embeddings, 0).to(flair.device)` 
throws ERROR, when some entries are in GPU (embeddings of elements) and some (Padding zeros) in CPU. Above change will bring all components in "word_embedings" list to common space (Flair Device).
> Padding entry conversion from CPU to flair_device to avoid CUDA embedding errors

- requirements.txt
Prevents urllib3 being downgraded in my environment (nothing in flair depends on urllib3)
At least I don't think it's needed... have I missed something? The line was added in https://github.com/flairNLP/flair/commit/3336f8f1fa93204a43fb513fc76c80b3a96ae6c5
> Remove urllib3 from requirements.txt

- flair/embeddings.py
- resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md
- resources/docs/embeddings/ONE_HOT_EMBEDDINGS.md
Adds documentation on how to use OneHotEmbeddings. Closes #1400
> GH-1400: onehot documentation

- flair/embeddings.py
- resources/docs/embeddings/ELMO_EMBEDDINGS.md
Add explanation that ELMo concatenates top 3 layers to make word embedding (see #647)
> GH-647: add ELMo layer documentation

- flair/data.py
- flair/datasets.py
- flair/models/sequence_tagger_model.py
- flair/models/text_classification_model.py
- flair/samplers.py
- tests/test_data.py
- tests/test_model_integration.py
- tests/test_text_classifier.py
- tests/test_text_regressor.py
- tests/test_visual.py
This PR refactors the `DataPoint` class and classes that inherit from it (`Token`, `Sentence`, `Image`, `Span`, etc.) so that all have the same methods for adding and accessing labels. 
- `DataPoint` base class now defined labeling methods (closes #1449) 
- Labels can no longer be passed to `Sentence` constructor, so instead of:
```python
sentence_1 = Sentence("this is great", labels=[Label("POSITIVE")])
```
you should now do: 
```python
sentence_1 = Sentence("this is great")
sentence_1.add_label('sentiment', 'POSITIVE')
```
or: 
```python
sentence_1 = Sentence("this is great").add_label('sentiment', 'POSITIVE')
```
Note that Sentence labels now have a `label_type` (in the example that's 'sentiment').
- The `Corpus` method `_get_class_to_count` is renamed to `_count_sentence_labels`
- The …
> GH-1449: labeling logic is part of DataPoint

- flair/data.py
- flair/datasets.py
- flair/models/text_classification_model.py
This PR adds 6 SentEval classification datasets to Flair. Closes #1453 
Load for instance like this: 
```python
from flair.datasets import SENTEVAL_SST_BINARY
corpus = SENTEVAL_SST_BINARY()
print(corpus)
```
Datasets are: 
- flair.datasets.SENTEVAL_CR
- flair.datasets.SENTEVAL_MR
- flair.datasets.SENTEVAL_SUBJ
- flair.datasets.SENTEVAL_MPQA
- flair.datasets.SENTEVAL_SST_BINARY
- flair.datasets.SENTEVAL_SST_GRANULAR
> GH-1453: SentEval classification datasets

- flair/embeddings.py
To load use 'ml-forward' (Forward Model) and 'ml-backward' (Backward Model).
> #1456: Add Malayalam flair embeddings models

- flair/data.py
The `DataPoint` refactoring caused the BIOES encoding to no longer work correctly in the `ColumnCorpus`. This PR fixed this again.
> GH-1449: fix BIOES encoding error caused by refactoring

- flair/datasets.py
Two fixes to the `CSVClassificationCorpus` and `ClassificationCorpus`:
- The `CSVlassificationCorpus` had an error when `in_memory=False`, fixed now (closes #1498) 
- Adds the ability to set `encoding` for `ClassificationCorpus` and `CSVClassiicationCorpus` (see #1496). For instance, to load the [Kaggle spam classification dataset](https://www.kaggle.com/uciml/sms-spam-collection-dataset/data), you can now do: 
```python
corpus = CSVClassificationCorpus(
Path('fath/to/your/data/folder'),
train_file='spam.csv',
column_name_map={0: 'label', 1: 'text'},
encoding='latin-1',
skip_header=True,
)
```
> GH-1498: classification datasets

- flair/embeddings.py
- resources/docs/embeddings/FLAIR_EMBEDDINGS.md
Adds the historical German language models trained by @redewiedergabe over 100 million tokens. Closes #1502 
Load the language models with:
```python
embeddings_forward = FlairEmbeddings('de-historic-rw-forward')
embeddings_backward = FlairEmbeddings('de-historic-rw-backward')
print(embeddings_forward.lm.generate_text())
```
> GH-1502: add language models by @redewiedergabe

- flair/datasets.py
- flair/embeddings.py
- flair/models/sequence_tagger_model.py
- flair/trainers/trainer.py
- flair/training_utils.py
- requirements.txt
- tests/test_data_fetchers.py
Sources for the simplified BertEmbeddings class.
> GH-1492: added new BERT embeddings implementation

- flair/models/sequence_tagger_model.py
This PR adds the taggers for historical German speech and thought created by the @redewiedergabe project. 
closes #1531
> GH-1531: add taggers for historical German speech and thought 

- flair/data.py
This PR fixes the issue #1529 . The problem is that we may get stuck in an infinite loop when the span `start_pos` indices of `Token` are incorrect, within the `to_original_text` method.
The solution is to simply stay in the `while` loop only if `start_pos` is **greater than** the `pos` counter.
> To avoid an infinite loop we check the value is greater, not only different

- flair/embeddings.py
- flair/models/language_model.py
- flair/trainers/language_model_trainer.py
Previously, text files used to train a `LanguageModel` were split at newlines and shuffled at each epoch. This is problematic if text files contain documents that span several lines. Closes #1538 
With this PR, you now have the option of specifying a document_delimiter when training a LanguageModel. Say, you have a corpus of textual lists and use "[SEP]" to mark boundaries between two lists, like this: 
```
Colors:
- blue
- green
- red
[SEP]
Cities:
- Berlin
- Munich
[SEP]
...
```
Then you can now train a language model by setting the `document_delimiter` in the `TextCorpus` and `LanguageModel` objects. This will make sure only documents as a whole will get shuffled during training (i.e. the lists in the above example): 
```python
delimiter = '[SEP]'
corpus = TextCorpus( …
```
> GH-1538: option to specify document delimiter for language model training

- flair/embeddings.py
This PR addresses a number of issues found with TransformerWordEmbeddings in #1494 :
- Adds handling for unknown tokens
- Improve tokenizer type checks fo RoBERTa so that correct tokenizer is used
- Deactivates dropout if transformer used in a feature based approach
- Add "all" as shorthand option to use all layers in transformer
- Add option for trainable ScalarMix (this part still needs further work)
> GH-1494: transformer errors

- flair/data.py
- flair/datasets/document_classification.py
- flair/trainers/trainer.py
This PR adds two new sentiment datasets to Flair, namely `AMAZON_REVIEWS`, a very large corpus of Amazon reviews with sentiment labels, and `SENTIMENT_140`, a corpus of tweets labeled with sentiment. See #1503 
There are also a number of improvements for the `ClassificationCorpus` and `ClassificationDataset` classes: 
- It is now possible to select from three memory modes ('full', 'partial' and 'disk'). Use full if the entire dataset and all objects fit into memory. Use 'partial' if it doesn't and use 'disk' if even 'partial' does not fit. 
- It is also now possible to provide "name maps" to rename labels in datasets. For instance, some sentiment analysis datasets use '0' and '1' as labels, while some others use 'POSITIVE' and 'NEGATIVE'. By providing name maps you can rename labels so …
> GH-1503: Sentiment Datasets

- flair/embeddings.py
- resources/docs/embeddings/ELMO_EMBEDDINGS.md
Addresses #647 by adding different ways to combine ELMo layers. Besides the default/current behavior of concatenating the 3 ELMo layers, the user can also get only the topmost layer, or an average of the 3 layers. These combining strategies are the same provided by [AllenNLP's ELMo CLI](https://github.com/allenai/allennlp/blob/d709e59ff3f54e137ea473d411056f68c197c266/allennlp/commands/elmo.py#L31).
> GH-647: add different ways to combine ELMo layers

- flair/embeddings.py
- resources/docs/embeddings/FLAIR_EMBEDDINGS.md
Hi,
this PR adds the recently trained Flair embeddings on historic newspapers for German/English/French provided by the [CLEF HIPE shared task](https://impresso.github.io/CLEF-HIPE-2020/).
From the task organizers:
> The amount for our our indomain training differs largely between languages:
> - French taken from Swiss and Luxembourgish newspapers: 20G
> - English taken from Chronicling America material: 1.1G
> - German taken from Swiss and Luxembourgish newspapers: 8.5G
Technical details:
> Technical details: The embedding size for characters is 2048. We use flair 0.4.5 to compute the embeddings using a context of 250 characters, a batchsize of 400-600 (depending on the GPUs memory), 1 hidden layer, dropout of 0.1.
The new Flair embeddings can be used as shown in the following example: …
> Add CLEF HIPE Flair Embeddings

- flair/datasets/document_classification.py
Change AmazonReviews dataset so that by default it uses only POSITIVE and NEGATIVE.
> GH-1503: change Amazon reviews sentiment preset

- flair/__init__.py
- flair/trainers/trainer.py
- flair/training_utils.py
Add new scheduler that uses dev score as main metric to anneal against, but additionally uses dev loss in case two epochs have the same dev score.
Closes #1403
> GH-1403: anneal against score and loss

- flair/embeddings.py
This PR adds the option to choose which hidden state to use in FlairEmbeddings: either the state at the end of each word, or the state at the whitespace after. Default is the state at the whitespace after. 
You can change the default like this:
```python
embeddings = FlairEmbeddings('news-forward', with_whitespace=False)
```
This configuration seems to be better for syntactic tasks. For POS tagging, it seems that you should set `with_whitespace=False`. For instance, on UD_ENGLISH POS-tagging, we get **96.56 +- 0.03** with whitespace and **96.72 +- 0.04** without, averaged over three runs. 
See the discussion in #1362 for more details.
> GH-1362: Add option for hidden state position in FlairEmbeddings

- flair/datasets/sequence_labeling.py
- tests/resources/tasks/column_corpus_options/eng.testa
- tests/resources/tasks/column_corpus_options/eng.testb
- tests/resources/tasks/column_corpus_options/eng.train
- tests/resources/tasks/column_with_whitespaces/eng.testa
- tests/resources/tasks/column_with_whitespaces/eng.testb
- tests/resources/tasks/column_with_whitespaces/eng.train
- tests/test_data.py
- tests/test_datasets.py
Closes #1580 (attempt 2, see #1581 )
The `ColumnCorpus` currently assumes that there is always a whitespace between two tokens. This PR adds the option of specifying a special "space-after" column. If that column has a "-" it means that no whitespace follows this token. 
For instance, the following sentence in column format: 
```console
It O +
is O +
a O +
French B-LOC -
- O -
speaking O +
town O -
. O +
```
First column is the token, second the NER tag and third the whitespace after information. After the PR, you can read the corpus like this: 
```python
corpus = ColumnCorpus('path/to/corpus', column_format={0: 'text', 1: 'ner', 2: 'space-after'})
for sentence in corpus.get_all_sentences():
print(sentence.to_tokenized_string())
print(sentence.to_plain_string())
```
If the corpus only …
> GH-1580: True whitespaces in ColumnCorpus (version 2)

- flair/embeddings.py
Some parameters of SkalarMix were not initialized on flair.device, causing the bug reported in #1567 
This PR fixes this and closes #1567
> GH-1567: init skalar mix on flair.device

- flair/datasets/__init__.py
- flair/datasets/sequence_labeling.py
Hi,
this PR adds support for the BIOfid dataset:
> The Specialized Information Service Biodiversity Research (BIOfid) has been launched to mobilize valuable biological data from printed literature hidden in German libraries for over the past 250 years. In this project, we annotate German texts converted by OCR from historical scientific literature on the biodiversity of plants, birds, moths and butterflies. Our work enables the automatic extraction of biological information previously buried in the mass of papers and volumes. For this purpose, we generated training data for the tasks of Named Entity Recognition (NER) and Taxa Recognition (TR) in biological documents. We use this data to train a number of leading machine learning tools and create a gold standard for TR in biodiversity …
> datasets: add support for BIOfid dataset

- flair/data.py
- flair/embeddings/token.py
Additional fix for zero-width spaces, see #1600
> GH-1600: fix zero width spaces

- flair/embeddings/document.py
- flair/embeddings/token.py
There are some weird errors in transformer tokenizers when training/saving a model on one machine and using it on another. See #1610. This PR changes de-serialization so that tokenizer is always re-loaded when loading a model.
> GH-1610: transformer tokenizer is re-loaded upon de-serialization

- flair/models/text_classification_model.py
This PR adds new sentiment models for English to Flair and closes #1503 
The new models are trained over a combined corpus of sentiment dataset, including Amazon product reviews. So they should be applicable to more domains than the old sentiment models that were only trained with movie reviews. 
There are two new models, a transformer-based model you can load like this: 
```python
classifier = TextClassifier.load('sentiment')
sentence = Sentence("enormously entertaining for moviegoers of any age .")
classifier.predict(sentence)
```
And a faster, slightly less accurate model based on RNNs you can load like this:
```python
classifier = TextClassifier.load('sentiment-fast')
sentence = Sentence("enormously entertaining for moviegoers of any age .") …
```
> New sentiment models

- flair/models/sequence_tagger_model.py
This PR adds fine-grained POS models for English and updates the German one. 
For English you now have the option between 'pos' and 'upos' models for fine-grained and universal dependencies respectively. Load like this: 
```python
tagger = SequenceTagger.load('pos')
sentence = Sentence("The grass is green")
print(sentence.to_tagged_string())
tagger = SequenceTagger.load('pos-fast')
sentence = Sentence("The grass is green")
print(sentence.to_tagged_string())
tagger = SequenceTagger.load('upos')
sentence = Sentence("The grass is green")
print(sentence.to_tagged_string())
tagger = SequenceTagger.load('upos-fast')
sentence = Sentence("The grass is green")
print(sentence.to_tagged_string()) …
```
> GH-1623: add fine-grained POS models

- flair/models/sequence_tagger_model.py
Adds `use_dropout` parameter to serialization and so closes #1628
> GH-1628: serialize dropout

- flair/data.py
- flair/embeddings/base.py
- flair/embeddings/document.py
- flair/embeddings/token.py
- flair/models/sequence_tagger_model.py
- flair/models/text_classification_model.py
- flair/models/text_regression_model.py
- flair/nn.py
- flair/trainers/trainer.py
- tests/test_hyperparameter.py
- tests/test_text_classifier.py
This PR makes a number of refactorings to the evaluation routines in Flair. In short: whenever possible, we now use the evaluation methods of sklearn (instead of our own implementations which kept getting issues). This applies to text classification and (most) sequence tagging. 
A notable exception is "span-F1" which is used to evaluate NER because there is no good way of counting true negatives. After this PR, our implementation should now exactly mirror the original `conlleval` script of the CoNLL-02 challenge. In addition to using our reimplementation, an output file is now automatically generated that can be directly used with the `conlleval` script. 
In more detail, this PR makes the following changes: 
- `Span` is now a list of `Token` and can now be iterated like a sentence
- …
> Refactor evaluation

- flair/embeddings/document.py
As discussed in #1645 there is some confusion regarding the fine-tuning layer that is initialized by default for the `DocumentPoolEmbeddings`. This PR turns this off by default (no fine-tuning) and adds some explanations to the method signature.
> GH-1645: change default fine-tuning in DocumentPoolEmbeddings to "none"

- flair/models/sequence_tagger_model.py
This PR makes the reprojection layer optional in SequenceTagger. You can control this behavior through the `reproject_embeddings` parameter. If you set it to `True`, embeddings are reprojected via linear map to identical size. If set to `False`, no reprojection happens. If you set this parameter to an integer, the linear map maps embedding vectors to vectors of this size. 
```python
tagger = SequenceTagger(
hidden_size=256,
[...]
reproject_embeddings=True,
)
tagger = SequenceTagger(
hidden_size=256,
[...]
reproject_embeddings=False,
)
tagger = SequenceTagger(
hidden_size=256,
[...]
reproject_embeddings=128,
)
```
> Make reprojection layer optional

- flair/datasets/__init__.py
- flair/datasets/sequence_labeling.py
This PR adds SENTIMENT_140 and AMAZON_REVIEWS to the datasets.__init__.py so that they can be loaded like this: 
```python
corpus = flair.datasets.SENTIMENT_140()
```
Also rearranges datasets in alphabetical order in the code.
Closes #1664
> GH-1664: add new datasets to __init__.py

- flair/nn.py
> GH-1604: deserialize to CPU and move to GPU to avoid error #1604

- flair/embeddings/token.py
try catch block around tokenizer.from_pretrained in order to avoid bug
closes #1685
> #1685 deserialization of tokenizer always gets loaded from huggingface

- flair/models/sequence_tagger_model.py
This PR adds two new models for Dutch NER and so closes #1365 
The new default model is a BERT-based RNN model with the highest accuracy: 
```python
tagger = SequenceTagger.load('nl-ner')
sentence = Sentence('Ik hou van Amsterdam')
```
You can also load a Flair-based RNN model (might be faster on some setups): 
```python
tagger = SequenceTagger.load('nl-ner-rnn')
```
> GH-1365: add two new dutch NER models

- flair/embeddings/base.py
Hello, 
This is a simple MR, because during the embed function you keep checking for all tokens to see if someone needs a embedding. This MR just change the loop to stop as soon it find one
> Short-circuit the embedding loop

- flair/embeddings/token.py
Made this PR to address issues #1618 and #1634 . Replaced the lambda functions in ELMoEmbeddings class (in token.py) with three instance methods. Also added lines inside _add_embeddings_internal to check that if embedding_mode_fn exists, if not, assign it to be the embedding mode function for all layers to prevent "AttributeError: 'ELMoEmbeddings' object has no attribute 'embedding_mode_fn'".
> resolve issues caused by embedding mode and lambda functions in ELMoEmbeddings in Release 0.5

- flair/data.py
The old condition assigned False to whitespace_after when there is actually a whitespace after the token.
> fix condition to assign whitespace_after attribute in the build_spacy_tokenizer wraper

- flair/datasets/document_classification.py
- flair/models/text_classification_model.py
Adds `memory_mode` presets to classification corpora. All small corpora get `memory_mode = 'full'` by default, all large corpora get `memory_mode = 'partial'`.
> Memory mode presets for classification corpora

- flair/models/text_classification_model.py
- tests/test_text_classifier.py
Fixes #1709 so that all label probabilities are output in TextClassifier.
> GH-1709: fix error in returning multiple classes

- flair/embeddings/document.py
- flair/embeddings/token.py
- requirements.txt
Hi,
this PR updates the awesome 🤗 Transformers to latest 3.0.0 version, see release noted [here](https://github.com/huggingface/transformers/releases/tag/v3.0.0).
In version >= 3.0.0 the `prepare_for_model` method was removed, `encode_plus` should be used instead, see #1726 .
This PR fixes it :) I couldn't see any performance degradation when training one epoch for CoNLL-2003 in comparison to the `prepare_for_model` method.
> 🤗 Transformers: Update to latest 3.0.0 version

- flair/embeddings/token.py
Hi,
this PR updates the installation instructions for `allennlp` library in `ELMoEmbeddings`.
Versions >= *0.9.2* no longer support `allennlp.commands.elmo`, so `ELMoEmbeddings` can't be used then.
Fixes #1729.
> ELMoEmbeddings: pin 0.9.0 of allennlp

- flair/embeddings/document.py
- flair/models/language_model.py
We currently do a torch version check to fix a backwards compatibility error with torch versions smaller than 1.4.0. See #1360 
However, this version check causes some errors with some torch version strings. This PR removes the explicit version check and so closes #1744.
> GH-1744: remove torch version checks

- flair/data.py
- flair/models/text_classification_model.py
Fixes errors in `TextClassifier` if not `label_type` is passed. Closes #1748
> GH-1748: fix TextClassifier evaluation if no label_type is passed

- flair/embeddings/token.py
- requirements.txt
- resources/docs/embeddings/BYTE_PAIR_EMBEDDINGS.md
Now, we can load custom BPEmb into BytePairEmbeddings class since bpemb package has been upgraded to 0.3.2.
> Adapt BytePairEmbeddings class to new version of bpemb

- flair/trainers/trainer.py
This PR adds support for the One Cycle policy described by Smith in https://arxiv.org/pdf/1803.09820.pdf .
It is based on the PyTorch implementation: https://pytorch.org/docs/stable/optim.html#torch.optim.lr_scheduler.OneCycleLR .
I added only the strictly needed parameters to the trainer (max_lr, total_steps, cycle_momentum) and left the others to default values, as they usually work well, but if one wants to experiment with them we need to add them all to the trainer interface.
In experiments on private datasets, I have seen a behavior that seems similar to the one described in the paper (very fast convergence and good regularization).
I tried also to reproduce this example https://github.com/flairNLP/flair/blob/master/resources/docs/EXPERIMENTS.md#wnut-17-emerging-entity-detection-engli …
> Add one-cycle policy

- flair/embeddings/token.py
- flair/models/sequence_tagger_model.py
- resources/docs/TUTORIAL_2_TAGGING.md
@LucasFerroHAILab shared a model for POS tagging on Portuguese Clinical Texts with us. You can now load the model with: 
```python
tagger = SequenceTagger.load('pt-pos-clinical')
sentence = Sentence('O vírus Covid causa fortes dores .')
```
The model was trained on PUCPR, with an accuracy of 92.39. You can find all information in [their repo](https://github.com/HAILab-PUCPR/portuguese-clinical-pos-tagger) and their paper [Defining a state-of-the-art POS-tagging environment for Brazilian Portuguese clinical texts](https://link.springer.com/article/10.1007/s42600-020-00067-7). Please cite the paper when using the model. 
Thanks @LucasFerroHAILab for sharing the model!
> Add Portuguese Clinical POS model by @LucasFerroHAILab

- flair/tokenization.py
- requirements.txt
- tests/test_data.py
Related: #1296
Hello all! I'm the author of #1267 
Recently, I updated konoha adding supports for new tokenizers.
In this PR, I add supports for two Japanese tokenizers to flair.tokenization.JapaneseTokenizer; [Janome](https://github.com/mocobeta/janome) and [SudachiPy](https://github.com/WorksApplications/SudachiPy).
These tokenizers work without building any external software outside `pip install`.
So I'm wondering if I can add support for built-in Japanese tokenization to flair.
(Of course, it's not a strong opinion. I'd like feedback from the flair team!)
I attach examples for using JapaneseTokenizer in some cases:
```
> python …
```
> Add supports for additional Japanese tokenizers.

- flair/embeddings/token.py
- train.py
This PR addresses errors that occur when training a model with byte pair embeddings on one machine and loading this model on another. Also addresses the problem that the cache dir could not be overwritten. See #1563 and #1483
Closes #1563 
Closes #1483
I tested this on a setup with two linux machines and it seems to work, though cross-OS tests were not done.
> BytePairEmbedding serialization

- flair/embeddings/token.py
Fixes #1753 by checking the device when deserializing and moving the ELMo objects as needed. Tested in my local setup.
> GH-1753: Fix issues with loading models that use ELMoEmbeddings

- flair/embeddings/document.py
Previously, the `TransformerDocumentEmbeddings` truncated all text to 512 subtokens. But some transformer models can handle longer text. With this PR, the max number of subtokens is read from the transformer model and it is only truncated accordingly. 
Closes #1774
> GH-1774: get max subtokens from transformer model

- flair/data.py
- tests/test_data.py
The Sentence object now executes tokenization by default, e.g.: 
```python
sentence = Sentence("I love Berlin.")
sentence = Sentence("I love Berlin.", use_tokenizer=False)
sentence = Sentence("I love Berlin.", use_tokenizer=False)
```
Closes #1768
> GH-1768: turn on tokenizer by default in Sentence object

- flair/datasets/sequence_labeling.py
Hi,
the GermEval 2014 shared task site was recently updated and the url for download instructions is now outdated.
This PR fixes the url :)
> datasets: update url for GermEval 2014 instructions

- README.md
This add a link to a repo I in response to a question I had in [issue 1770](https://github.com/flairNLP/flair/issues/1770).
It adds two examples:
1. Training on GCP AI platform by making use of custom containers.
2. Serving predictions on GCP Cloud Run by making use of a Docker container and FastAPI.
> GH-1770: Added a link to a repo with examples of Flair on GCP

- requirements.txt
I'm really sorry but I added the change that made the installation fail if `poetry` is used.
This failure is related to the issue (python-poetry/poetry#2676).
This PR stops using `extras_require` in `requirements.txt` and add dependencies explicitly.
`poetry add flair` fails with the following message.
```
poetry add flair
...
[SolverProblemError]
Because no versions of flair match >0.6,<0.7
and flair (0.6) depends on konoha (>=4.0.0,<5.0.0), flair (>=0.6,<0.7) requires konoha (>=4.0.0,<5.0.0).
And because no versions of konoha match >=4.0.0,<4.6.1 || >4.6.1,<5.0.0
and konoha (4.6.1) depends on janome (>=0.3.10,<0.4.0), flair (>=0.6,<0.7) requires janome (>=0.3.10,<0.4.0).
So, because no versions of janome match >=0.3.10,<0.4.0
and test depends on flair (^0.6), version solving failed.
``` …
> [Hotfix] Stop using extras_require

- flair/embeddings/document.py
Found a typo when going over the docstring.
> DocumentEmbeddings: Fix typo in doc string

- flair/models/sequence_tagger_model.py
In the current master branch, this fails:
```
SequenceTagger.load("upos-fast")
```
I think I figured out the typo and updated the link correctly.
> fix upos-fast link

- flair/embeddings/token.py
- flair/models/text_classification_model.py
Closes #1840. Fixes URL of MUSE embeddings.
Also closes #1841 by fixing the sentiment model to have the new transformers attributes.
> GH-1840: move MUSE embeddings to HU server

- flair/embeddings/document.py
- flair/embeddings/token.py
Switch transformer serialization to not serialize tokenizers since this was causing problems for some embeddings such as XLM. 
See #1827
> GH-1827: fix deserialization issues in transformer tokenizers

- flair/models/sequence_tagger_model.py
Add legal NER model for German. Trained using the German legal NER dataset available [here](https://github.com/elenanereiss/Legal-Entity-Recognition) that can be loaded in Flair with the `LER_GERMAN` corpus object.
Uses German Flair and FastText embeddings and gets **96.35** F1 score.
Use like this: 
```python
tagger = SequenceTagger.load('de-ler')
text = "vom 6. August 2020. Alle Beschwerdeführer befinden sich derzeit gemeinsam im Urlaub auf der Insel Mallorca , die vom Robert-Koch-Institut als Risikogebiet eingestuft wird. Sie wollen am 29. August 2020 wieder nach Deutschland einreisen, ohne sich gemäß § 1 Abs. 1 bis Abs. 3 der Verordnung zur Testpflicht von Einreisenden aus Risikogebieten auf das SARS-CoV-2-Virus testen zu lassen. Die Verordnung sei wegen eines Verstoßes der ihr …
```
> GH-1871: add Legal NER model

- flair/models/sequence_tagger_model.py
This PR updates the Dutch NER model to work with the new transformers version.
> GH-1687: correct Dutch NER model

- flair/datasets/__init__.py
- flair/datasets/sequence_labeling.py
I have added the UP datasets for English and Spanish (Spanish times)
Interestingly, the frame data was in column 10 and not in 9 in the English dataset, so it was a bit different from they other ones
But they should all work
> UP-datasets for English and Spanish added

- flair/datasets/__init__.py
- flair/datasets/sequence_labeling.py
**NER Dataset**
Embeddings used:
- GloVe Word Embeddings
- Flair Embeddings (ar-forward, ar-backward)
Initial model delivers following results:
0.8421	- 	0.8268	-	0.8344
Results:
- F1-score (micro) 0.8344
- F1-score (macro) 0.7901
By class:
LOC        tp: 369 - fp: 48 - fn: 37 - precision: 0.8849 - recall: 0.9089 - f1-score: 0.8967
MISC       tp: 62 - fp: 22 - fn: 37 - precision: 0.7381 - recall: 0.6263 - f1-score: 0.6776
ORG        tp: 131 - fp: 32 - fn: 64 - precision: 0.8037 - recall: 0.6718 - f1-score: 0.7318
PERS       tp: 302 - fp: 60 - fn: 43 - precision: 0.8343 - recall: 0.8754 - f1-score: 0.8543
This example "الجامعة الألمانية بالقاهرة " (German University in Cairo) demonstrates a partially correct tagging. The model only understands Cairo as a LOC, but not the whole entity as a …
> Add ANERcorp for MSA training

- flair/data.py
- flair/models/sequence_tagger_model.py
- tests/test_hyperparameter.py
- tests/test_sequence_tagger.py
> GH-1934: add handling for micro-average precision and recall

- flair/datasets/__init__.py
- flair/datasets/treebanks.py
Added support for UD_Levvi from UD, based on the original splits. (see previous PR)
Merged with the current upstream changes and tested.
The upstream changes now allow for operation without a dev set file, creating a dev set on the fly based on the training set file.
> Adding support for the UD_Livvi dataset

- flair/datasets/treebanks.py
> Added support for UD_NAIJA

- flair/datasets/__init__.py
- flair/datasets/sequence_labeling.py
- resources/docs/TUTORIAL_6_CORPUS.md
This implementation appropriately prepares and loads the aforementioned dataset. 
I could also add commit the testing function for the pipenv testing, if needed. 
Edit: typo
> Adding WNUT_2020_NER dataset support

- flair/datasets/__init__.py
- flair/datasets/treebanks.py
Added support for UD_NORTH_SAMI. This dataset does not define a dev split.
> Added support for UD_NORTH_SAMI

- flair/datasets/__init__.py
- flair/datasets/treebanks.py
This is my solution for the current "Semester Projekt Gruppe 5" task.
Kind regards
Martin Vogel
> Adding afrikaans support to flair nlp project

- flair/datasets/__init__.py
- flair/datasets/treebanks.py
I'm not  sure if additional formating is needed, this loads the corpus without additional reformatings of the source files.
> Support for UD_OLD_FRENCH added

- flair/__init__.py
Hi,
this PR adds the possibility to set a seed via wrapping the Hugging Face Transformers library helper method.
By specifying a seed with:
```python
import flair
flair.set_seed(42)
```
more reproducable experiments are possible. The wrapped `set_seed` method sets seeds for `random`, `numpy` and `torch`. More details [here](https://github.com/huggingface/transformers/blob/08f534d2da47875a4b7eb1c125cfa7f0f3b79642/src/transformers/trainer_utils.py#L29-L48).
> global: add possibility to set flair seed

- flair/datasets/treebanks.py
This PR addresses the problem of multi-word tokens and whitespace offsets in the Universal Dependencies datasets and closes #1980. 
In particular, it introduces the  `split_multiwords` constructor argument to all UD corpora which by default is set to `True`. It controls the handling of multiwords that are split into different tokens such as "am" in German, split to "an" and "dem"; or "aux" in French, split into "a" and "les". If set to `True`, they are split as in UD. If set to `False`, we keep the original multiword as a single token. 
Example: 
```python
corpus_split = UD_GERMAN(split_multiwords=True)
print(corpus_split.dev[179].to_plain_string())
corpus_unsplit = UD_GERMAN(split_multiwords=False)
print(corpus_unsplit.dev[179].to_plain_string())  
```
This prints 
~~~
Ein Hotel zu dem …
> GH-1980: add handling for UD multi-word tokens

- flair/models/sequence_tagger_model.py
- requirements.txt
Hi,
this PR allows to use trained sequence tagging from the Hugging Face model hub :hugs: 
It is only needed to specify the namespace, like `stefan-it/flair-ner-conll03` and a model will be downloaded (incl. caching) that can be used in Flair!
Naming convention is, that the model file on the model hub is named `model.bin`.
The following code snippet shows how to use this new feature:
```python
tagger: SequenceTagger = SequenceTagger.load("stefan-it/flair-ner-conll03")
```
It is also possible to pass a specific commit or branch name via `@`-syntax: `stefan-it/flair-ner-conll03@main`.
On the Hugging Face model hub itself, it is also possible to add a `README` file, that gives more details about a trained model: …
> models: add support for Hugging Face model hub

- flair/models/text_classification_model.py
- requirements.txt
- resources/docs/TUTORIAL_10_TRAINING_ZERO_SHOT_MODEL.md
- tests/test_tars.py
This PR adds a pretrained TARS model (closes #1977). Load and use for zero-shot like this: 
```python
tars = TARSClassifier.load('tars-base')
sentence = flair.data.Sentence("I am so glad you liked it!")
classes = ["happy", "sad"]
#4. Predict for these classes
tars.predict_zero_shot(sentence, classes)
```
It also adapts the single label prediction logic so that confidence must be above threshold 0.5 (@kishaloyhalder does this make sense?), a convenience function to predict all TARS tasks at once, a convenience method to pass just one label as string instead of a list and updates the TARS tutorial.
> GH-1827: Pretrained TARS model and small fixes

- flair/models/sequence_tagger_model.py
Hi,
as discussed with the Hugging Face team, it is better to call the model `pytorch_model.bin` instead of `model.bin` on the Hugging Face model hub.
This PR renames the expected model filename :hugs:
> models: change default name for Flair models on Hugging Face model hub

- .github/workflows/ci.yml
- requirements.txt
Hi,
this PR uses GitHub Actions for running our (future) tests.
CI pipeline is only triggered, when creating a new PR in order to save credits.
The CI steps are mainly copied from (old) Travis CI configuration: Python 3.6 is again used (we could also define a build matrix for other Python versions).
> ci: introduce GitHub Actions

- flair/datasets/sequence_labeling.py
#1985 
Test: 
corpus = EUROPARL_NER_GERMAN(label_name_map={'LOC': '**location test a-b-c**', 'PPER': '**person test a-b-c**'})
print(corpus.test[83])
Output:
Sentence: "In Wien gab es eine große Konferenz ."   [− Tokens: 8  − Token-Labels: "In <in/APPR/I-PC> Wien <Wien/NE/I-PC/**S-location test a b c**> gab <geben/VVFIN/I-VC> es <es/**person test a b c**/I-NC> eine <ein/ART/B-NC> große <groß/ADJA/I-NC> Konferenz <Konferenz/NN/I-NC> . <./$.>"]
As you can see, my implementation replaces "-" with " " because e.g. the methods iob2 and iob_iobes in data.py run into problems when tags contain "-".
> Tag name map

- .github/workflows/ci.yml
- requirements.txt
Hi,
`numpy` in upcoming versions just dropped Python 3.6 support, see [here](https://github.com/numpy/numpy/pull/17895).
As we have a lot of users that are using Python 3.6, we restrict the `numpy` version to < 1.20.0.
You can of course use newer `numpy` versions, when you have Python >= 3.7. This PR also fixes our current failing CI builds.
----
Thanks to the awesome `scikit-learn` contributors for their help and very usefuls hints, see [here](https://github.com/scikit-learn/scikit-learn/pull/18956)!
> pip: restrict numpy version to < 1.20 for Python 3.6

- flair/data.py
- flair/datasets/sequence_labeling.py
- flair/embeddings/token.py
- flair/models/sequence_tagger_model.py
- resources/docs/embeddings/TRANSFORMER_EMBEDDINGS.md
- tests/test_embeddings.py
Various refactorings of FLERT approach: 
1. `Sentence` objects now have `next_sentence()` and `previous_sentence()` methods that are set automatically if loaded through `ColumnCorpus`. This is a pointer system to navigate through sentences in a corpus: 
```python
corpus = MIT_MOVIE_NER_SIMPLE(in_memory=False)
sentence = corpus.test[123]
print(sentence.previous_sentence())
print(sentence.next_sentence())
print(sentence.next_sentence().next_sentence())
```
This allows dynamic computation of contexts in the embedding classes. 
2.  `Sentence` objects now have the `is_document_boundary` field which is set through the `ColumnCorpus`. In some datasets, there are sentences like "-DOCSTART-" that just indicate document boundaries. This is now recorded as a boolean in the object.
3. …
> GH-2015: refactor FLERT

- flair/models/sequence_tagger_model.py
Usually, in WSD evaluation wrong predictions are ignored if the gold data states no sense for a token. This was not considered yet in Flair but this PR adds the wsd_evaluation flag to the evaluate function to make this kind of evaluation possible.
> Improve evaluation for wsd task

- flair/data.py
- flair/datasets/base.py
- flair/datasets/sequence_labeling.py
- flair/trainers/trainer.py
Closes #2033 
For various reasons, we might want to have a `Corpus` that does not define all three splits (train/dev/test). For instance, we might want to train a model over the entire dataset and not hold out any data for validation/evaluation. 
This PR adds several ways of doing so.
1. If a dataset has predefined splits, like most NLP datasets, you can pass the arguments `train_with_test` and `train_with_dev` to the `ModelTrainer`. This causes the trainer to train over all three splits (and do no evaluation):
```python
trainer.train(f"path/to/your/folder",
learning_rate=0.1,
mini_batch_size=16,
train_with_dev=True,
train_with_test=True,
)
```
2. You can also now create a Corpus with fewer splits without having all three splits automatically sampled. Pass `sample_missing_splits=False` as …
> GH-2033: More options for splits in corpora and training

- flair/datasets/sequence_labeling.py
- flair/embeddings/token.py
- flair/models/sequence_tagger_model.py
This PR improves serialization of the `TransformerWordEmbeddings` class such that you can now train a model with one version of the transformers library and load it with another version. Previously, if you trained a model with transformers 3.5.1 and loaded it with 3.1.01, or trained with 3.5.1 and loaded with 4.1.1, or other version mismatches, there would either be errors or bad predictions. 
Closes #1747 (I believe)
This PR is in preparation for updating Flair to transformers 4. 
**Migration guide:** If you have a model that uses `TransformerWordEmbeddings` you can save it in the new version-independent format by loading the model with the same transformers version you used to train it, and then saving it again. The newly saved model is then version-independent: 
```python
tagger = …
```
> GH-2035: Improve transformer serialization and prepare transformers 4 integration

- flair/embeddings/token.py
- flair/file_utils.py
- requirements.txt
functools lru_cache doesn't follow self object's lifetime, thus the memory leak. replaced with methodtools.
closes GH-2013.
> Memory leak word embeddings

- flair/embeddings/document.py
- flair/embeddings/token.py
- flair/file_utils.py
- flair/models/sequence_tagger_model.py
- flair/models/text_classification_model.py
- requirements.txt
- tests/test_embeddings.py
This PR updates the transformers dependency to version 4 or higher. To enable this, it adapts the serialization logic of the `TransformerDocumentEmbeddings` class. 
**Migration guide:** If you have a model that uses `TransformerDocumentEmbeddings` you can save it in the new version-independent format by loading the model with the same transformers version you used to train it, and then saving it again. The newly saved model is then version-independent: 
```python
classifier = TextClassifier.load('path/to/old-model.pt')
classifier.save('path/to/new-model.pt')
```
The PR also refactors the serialization logic and fixes an error in detecting offests when using fast tokenizers.
> GH-2035: Update to transformers 4

- requirements.txt
Fixed #2049 
[Link](https://colab.research.google.com/drive/1LIxvkBnYAwP62f6kiNyErBTXJCm7PHEn?usp=sharing). As mentioned in this notebook, the version below 1.5.0 gave `unpickling error`
> GH-2049 Changed the torch version in requirements.txt: Torch>=1.5.0

- flair/models/text_regression_model.py
Closes #2056  
This PR does a quick fix of two problems in the regression model: 
- the predict() method was unable to set labels and threw errors (see #2056) 
- predicted labels had no label name 
Now, you can set a label name either in the predict method or during instantiation of the regression model you want to train. So the full code for training a regression model and using it to predict is: 
```python
corpus = WASSA_JOY()
embeddings = DocumentPoolEmbeddings([WordEmbeddings('glove')], fine_tune_mode='linear')
model = TextRegressor(embeddings, label_name='happiness')
output_folder = 'resources/taggers/regression_test/'
trainer = ModelTrainer(model, corpus)
trainer.train(
output_folder,
mini_batch_size=16,
max_epochs=10,
)
model = TextRegressor.load(output_folder + 'best-model.pt') …
```
> GH-2056: fix regression prediction errors

- flair/datasets/document_classification.py
Some CSV classification datasets contain a value that means "no class". This PR extends the CSVClassificationDataset so that it is possible to specify which value should be skipped using the `no_class_label` argument. 
For instance: 
```python
corpus = CSVClassificationCorpus(
data_folder='resources/tasks/code/',
train_file='java_io.csv',
skip_header=True,
column_name_map={3: 'text', 4: 'label', 5: 'label', 6: 'label', 7: 'label', 8: 'label', 9: 'label'},
no_class_label='NONE',
)
```
This causes all entries of NONE in one of the label columns to be skipped.
> Add possibility to specify empty label name to CSV corpora

- flair/data.py
- tests/test_data.py
Closes #2069 
Newlines and tabs can now become Tokens in a Sentence: 
```python
sentence: Sentence = Sentence(["I", "\t", "ich", "\n", "you", "\t", "du", "\n"], use_tokenizer=True)
for token in sentence:
print(token)
```
> GH-2069: allow newlines as Tokens in a Sentence

- flair/models/sequence_tagger_model.py
- requirements.txt
Hi,
with this PR, some improvements in the Hugging Face model hub logic are done:
* We use the shiny new client library `huggingface-hub` for downloading Flair-specific models
* Additionally, we pass a Flair-specific user agent information (`flair` and the used version) to the Hugging Face infrastructure
Notice: the new Hugging Face model hub feature is a secret (hidden) feature now. Expect an official announcement in the next upcoming *0.8* version.
Thanks to the Hugging Face team for their great support and providing the hosting infrastructure :heart:
> HF model hub improvements

- flair/models/sequence_tagger_model.py
is set to different dimension than length of embeddings.
> Fix linear input dimension if the reproject 

- flair/embeddings/__init__.py
- flair/embeddings/document.py
This PR adds DocumentTFIDFEmbeddings in a way described in issue #2085. 
Closes #2085.
> Added the DocumentTFIDFEmbeddings

- flair/models/sequence_tagger_model.py
for compatibility with huggingface_hub>=0.0.2
we handle datasets now using the same git-based system so that first param is now named repo_id not model_id 😇
> huggingface_hub: drop the first param name

- flair/models/similarity_learning_model.py
The evaluate method does not have a similar function signature as other models, which is causing errors when training it.
> Fix the evaluate() method in the SimilarityLearner class

- flair/models/sequence_tagger_model.py
This PR adds mappings of common sequence tagger model keys to the corresponding models in the HF model hub. Closes #2103 
So now if you load the default NER tagger with: 
```python
tagger = SequenceTagger.load('ner')
```
the key 'ner' will get remapped to 'flair/ner-english'. So it becomes identical to calling 
```python
tagger = SequenceTagger.load('flair/ner-english')
```
The latter is the way you can load [any Flair model from the HF hub](https://huggingface.co/models?filter=flair).
> GH-2103: Mappings to HF model hub

- flair/datasets/__init__.py
- flair/datasets/text_text.py
- flair/models/__init__.py
- flair/models/text_classification_model.py
Datasets and Corpus for Data involving Pairs of sentences/paragraphs (DataPairDataset and DataPairCorpus) and a Classifier that can dead with this kind of Data (BiCrossClassifier).
> Recognizing textual entailment

- flair/models/sequence_tagger_model.py
This PR adds our new very powerful and very slow FLERT models for NER for four languages. Closes #2116 
Load for instance with: 
```python
tagger = SequenceTagger.load("ner-large")
sentence = Sentence("George Washington went to Washington")
print('The following NER tags are found:')
for entity in sentence.get_spans('ner'):
print(entity)
```
> GH-2116: Add FLERT models

- flair/__init__.py
- requirements.txt
- setup.py
Hotfix for #2137 by limiting torch version to maximum 1.7.1. 
(A bigger fix to enable Flair for torch 1.8.0 is in the works.)
> GH-2137: hotfix for torch 1.8.0 error

- flair/datasets/__init__.py
- flair/datasets/sequence_labeling.py
Adding support for the [Reddit Entity Linking Dataset](https://arxiv.org/abs/2101.01228). 
Only gold annotations were considered. The dataset contains both the post titles and the comment threads. It is transformed into a CoNLL-like column format for consistency with other Flair Datasets.
> Adding the Reddit Entity Linking Dataset

- flair/embeddings/__init__.py
- flair/embeddings/document.py
- flair/models/text_classification_model.py
- tests/test_embeddings.py
I have implemented a simple CNN document embeddings based on Kim's CNN model.
Tests on TREC_6 give worse results than using RNN.
However, I am not sure if all code copied from `DocumentRNNEmbeddings` make sense in CNN.
> add DocumentCNNEmbeddings

- flair/datasets/document_classification.py
- flair/datasets/sequence_labeling.py
- flair/trainers/trainer.py
You can now load a data pair object with the CSV classification corpus, in case you want to train a classifier for sentence pair. 
Example: 
```python
import torch
from flair.data import Corpus
from flair.datasets import CSVClassificationCorpus
from flair.embeddings import TransformerDocumentEmbeddings
corpus = CSVClassificationCorpus("path/to/your/dataset",
train_file="what.csv",
column_name_map={0: "text", 1: "pair", 2: "label_entailment"},
skip_header=True,
in_memory=False,
max_chars_per_doc=50,
)
label_dictionary = corpus.make_label_dictionary()
from flair.models import TextPairClassifier, TextClassifier
tagger = TextClassifier(
document_embeddings=TransformerDocumentEmbeddings(),
label_dictionary=label_dictionary,
)
trainer = …
```
> Add option to load text pairs with CSVClassificationCorpus

- flair/embeddings/token.py
This PR fixes: https://github.com/flairNLP/flair/issues/2140.
The [documentation](https://github.com/flairNLP/flair/blob/master/resources/docs/embeddings/FLAIR_EMBEDDINGS.md) suggests that the CPU friendly mix of corpora Flair embedding models should be referenced as `multi-X-fast`, but they were defined as `multi-v0-X-fast` in the `PRETRAINED_MODEL_ARCHIVE_MAP` dict [here](https://github.com/flairNLP/flair/blob/69d7c7d523b9111956d6fecd781d0b4654a4b13a/flair/embeddings/token.py#L412).
This issue resulted in errors when loading the model using the ID mentioned in the documentation. This PR fixes this.
> Fix references to multi-X-fast Flair embedding models

- flair/__init__.py
- flair/embeddings/token.py
- flair/models/language_model.py
- requirements.txt
- setup.py
This PR addresses the problems in the language model serialization and so addresses #2137 (for a full fix, all models need to be updated on the model hub). 
To make your models trained with an older torch run with torch 1.8.0 you need to load the models with torch <1.8.0 and save them again. This newly saved model is then capable of running with any torch version: 
```python
tagger = SequenceTagger.load('your/model.pt')
tagger.save('your/model/updated.pt')
```
It also rearranges the requirements to allow torch 1.8.0 again and also remove the numpy requirement (fixes #2138).
> GH-2137: fix serialization bugs and prepare Flair 0.8.1 release

- flair/datasets/__init__.py
- flair/datasets/sequence_labeling.py
- resources/docs/TUTORIAL_6_CORPUS.md
Added a japanese NER Corpus for usage in FlairNLP.
> Japanese ner

- flair/models/sequence_tagger_model.py
- flair/models/similarity_learning_model.py
- flair/models/text_classification_model.py
- flair/models/text_regression_model.py
- flair/trainers/trainer.py
- flair/training_utils.py
Allow different metric than micro f1 as main score (calculated in the eval method of models), which is used for monitoring model performance on dev data during training, saving of best model and learning rate scheduling
> Gh 2117 more flexibility on main metric

- resources/docs/embeddings/CLASSIC_WORD_EMBEDDINGS.md
This PR fixes https://github.com/flairNLP/flair/issues/2159 .
The ID for Slovene embeddings in the doc is incorrect and raises an error if passed to the `WordEmbeddings` constructor. This PR fixes it.
I also checked other pars of Flair documentation for references to Slovene and they seem to be correct.
> GH-2159: Fixing ID for Slovene word embeddings in the doc

- flair/models/sequence_tagger_model.py
- flair/trainers/trainer.py
This PR makes small refactorings to `ModelTrainer` and `SequenceTagger`: 
- removed global variable `main_score_type` (was set outside __init__) and warning in `ModelTrainer`
- better separation of the two evaluation methods in `SequenceTagger` and better auto-detection of span_F1 evaluation
> Small refactorings in ModelTrainer and SequenceTagger evaluation logic

- flair/datasets/__init__.py
- flair/datasets/sequence_labeling.py
Draft of a Modern Standard Arabic dataset from 28 Wikipedia articles used in https://www.aclweb.org/anthology/W19-4607/
> Add AQMAR NER modified corpus

- flair/models/text_classification_model.py
In the evaluate method of models, give the option to return the predictions obtained on the eval data
> Gh 2118 return predictions during evaluation

- flair/embeddings/token.py
If you execute the following snippet exception `OverflowError: int too big to convert` is thrown:
```python
from flair.embeddings import TransformerWordEmbeddings
model = TransformerWordEmbeddings("xlnet-large-cased", "all", "mean", layer_mean=False)
model.embed(Sentence("This is a test that will not work"))
```
This happens because both XLNet and Transformer-XL do not have a max sequence length and `tokenizer.model_max_length` comes with a very big integer.
> Fix XLNet and Transformer-XL Execution

- flair/trainers/trainer.py
This PR fixes #2169  .
We are removing the log_handler here but not closing the handler leading to ResourceWarning: unclosed file <_io.BufferedReader name='training.log. Hence we are not able to programatically access the training.log (For ex - Unable to upload the file to s3 using botocore)
> GH-2169 - Close log_handler after training is complete.

- flair/datasets/__init__.py
- flair/datasets/sequence_labeling.py
Added support for the Amharic NER dataset to sequence_labeling.py
Source: https://github.com/masakhane-io/masakhane-ner/tree/main/data/amh
Encoding is set to utf-8 since the dataset uses characters from the Ethiopic unicode block.
(Introduction to NLP @ HU Berlin)
> Added NER support for Amharic

- flair/datasets/sequence_labeling.py
It adds entity mappings, removes sentences with metadata and adds questions/answers counts.
It fixes #2228.
**Expected Results:**
```py
from flair.data import Corpus
from flair.datasets import STACKOVERFLOW_NER
corpus: Corpus = STACKOVERFLOW_NER()
print(corpus)
```
Corpus: 9263 train + 2896 dev + 3108 test sentences
```py
corpus.train[0:3]
```
[Sentence: "If I would have 2 tables"   [− Tokens: 6  − Token-Labels: "If I would have 2 tables <S-Data_Structure>"],
Sentence: "How do I get this result"   [− Tokens: 6],
Sentence: "The following query needs to be adjusted , but I dont know how"   [− Tokens: 13]]
**Notes:**
It would be nicer to extend the parameter `comment_symbol` in the `ColumnCorpus` class or create one similar that accepts also a`list`. In this case, the new parameter would …
> Stackoverflow NER dataset cleaning

- flair/datasets/__init__.py
- flair/datasets/sequence_labeling.py
NER Support for Yoruba (Introduction task for NLP lecture)
> Added NER Support for Yoruba

- flair/datasets/sequence_labeling.py
Added the corpus IGBO_NER for named entity recognition in the language Igbo to the flair framework.
> IGBO_NER addition to FlairNLP

- flair/datasets/__init__.py
- flair/datasets/treebanks.py
I added the Irish dataset from Universal Dependencies (https://github.com/UniversalDependencies/UD_Irish-IDT/tree/master)  for part-of-speech tagging.
> added irish dataset to treebanks

- flair/datasets/sequence_labeling.py
Swahili language is a lingua franca of the African Great Lakes region and other parts of East and Southern Africa. The dataset can be used for Named-entity recognition (NER) task.
> added object that downloads the files for corpus with  Swahili language

- flair/datasets/sequence_labeling.py
In ColumnDataset, labels can be remapped to other labels. With this PR, we enable also mapping to 'O', i.e. excluding labels. 
For instance, to load CoNLL-03 without MISC, do: 
```python
corpus = CONLL_03(
label_name_map={'MISC': 'O'}
)
print(corpus.make_label_dictionary('ner'))
print(corpus.train[0].to_tagged_string('ner'))
```
> Add handling for mapping labels to 'O'

- flair/__init__.py
- flair/data_fetcher.py
- flair/datasets/biomedical.py
- flair/datasets/document_classification.py
- flair/datasets/sequence_labeling.py
- flair/datasets/text_text.py
- flair/datasets/treebanks.py
- flair/embeddings/token.py
- flair/file_utils.py
- flair/inference_utils.py
- flair/models/sequence_tagger_model.py
- tests/test_datasets.py
- tests/test_datasets_biomedical.py
This PR solves the bug #2207 and also removes all Path construction and being replaced by one in the modules init file.
This PR introduces a huge diff, but without logic changes.  So should be easily reviewable.
> Moving Path construction of flair.cache_root

- flair/trainers/language_model_trainer.py
Hey there, this is the PR related to [this issue](https://github.com/flairNLP/flair/issues/2202) I raised earlier. I split the PR in 4 commits:
- remove the unused `TextDataset.tokenize` method, which was used nowhere in the code
- merge the `TextDataset.charsplit` into `TextDataset.__getitem__` as it was ugly to have these separated, and again the method `TextDataset.charsplit` was not used elsewhere
- apply the random case changes before expanding the vocab and counting the tokens, so as to remove two potential errors:
- a case change which modified a sentence length (happens on rare tokens), which would lead to text shifting and a corrupt input - this was not caught due to this statement: `if token >= tokens: break`
- a case change which led to a character being added to the vocab but …
> Lm dataset improve

- flair/embeddings/token.py
- flair/models/sequence_tagger_model.py
- flair/models/tars_tagger_model.py
- flair/nn.py
- flair/trainers/trainer.py
First version of TARS few-shot sequence tagger. Train like this:
```python
corpus = WNUT_17(label_name_map={
"location": "location name",
"corporation": "corporation name",
"person": "person name",
"creative-work": "name of song, movie, book or other creative work",
"product": "name of product or consumer good",
"group": "name of music band, sports team or non-corporate organization",
}
)
dictionary = corpus.make_label_dictionary('ner')
print(dictionary)
tars_tagger = TARSTagger(
'ner_wnut',
dictionary,
tag_type='ner',
embeddings='bert-base-uncased',
num_negative_labels_to_sample=1,
prefix=True,
)
trainer = ModelTrainer(tars_tagger, corpus)
trainer.train('resources/taggers/few-shot-sequence-tagger',
learning_rate=0.02,
mini_batch_size=16,
mini_batch_chunk_size=1,
max_epochs=20, …
```
> First version of Zero-Shot Sequence Labeler

- tests/test_datasets.py
One dev sentence has apparently disappeared from the UD English treebank, breaking one of our unit tests. This PR changes the test so it runs again.
> UD English treebank - fix unit test for changes statistics

- flair/datasets/sequence_labeling.py
It contains:
- Add banned sentences parameter as mentioned in #2229
- Use the new parameter to load the `STACKOVERFLOW_NER` corpus.
- Ignore tags that were excluded in the paper using `label_name_map`. There was an error when mapping to `O` tag, which was fixed with #2254.
Using the `comment_symbol` was not feasible as it applies at a line level. The new one has to be applied once there is a full sentence.
> Add banned sentences parameter in SequenceTagger 

- resources/docs/TUTORIAL_2_TAGGING.md
The extra unnecessary space led to wrongly think that the input sentences must already be tokenized.
Moreover, there were already other sample sentences that did not include that extra space.
> Remove space before '.' in sample sentences

- flair/tokenization.py
- requirements.txt
This PR fixes GH-2311.
My fix requires a sentence lookahead when iterating over the plain sentences straight from the segtok library.
This is probably not the best solution. I appreciate any feedback.
> GH-2311: Fix SegtokSentenceSplitter Incorrect Sentence Position Attributes

- flair/embeddings/token.py
- resources/docs/embeddings/FLAIR_EMBEDDINGS.md
This PR adds support for Flair embeddings trained over Spanish clinical text. Big thanks to @matirojasg for contributing these! 
Call like so: 
```python
forward_embeddings = FlairEmbeddings("es-clinical-forward")
backward_embeddings = FlairEmbeddings("es-clinical-backward")
```
> GH-2292: add support for Spanish clinical Flair embeddings

- flair/data.py
- flair/datasets/document_classification.py
- flair/datasets/text_text.py
- flair/embeddings/document.py
- flair/models/__init__.py
- flair/models/diagnosis/distance_prediction_model.py
- flair/models/pairwise_classification_model.py
- flair/models/relation_extractor_model.py
- flair/models/sandbox/simple_sequence_tagger_model.py
- flair/models/tars_model.py
- flair/models/tars_tagger_model.py
- flair/models/text_classification_model.py
- flair/nn/__init__.py
- flair/nn/dropout.py
- flair/nn/model.py
- tests/test_data.py
- tests/test_tars.py
- tests/test_text_classifier.py
- tests/test_text_regressor.py
As we are now adding many more types of models to Flair (see #2333) we are refactoring the logic of Flair model classes to remove many redundancies and make the code hopefully easier to read. 
This PR is the second step in this refactoring process and mainly adds the new `DefaultClassifier` base class to Flair. It contains all logic that is shared by models that do classification, so that these models use the same (1) evaluation code, (2) prediction code and (3) loss computation code. Any Flair model that inherits from `DefaultClassifier` now only has to implement the `forward_pass()` method - all the rest is then supplied by the parent class. 
With this refactoring, the `TextClassifier`, the `RelationExtractor`, the `TextPairClassifier` and the `SimpleSequenceTagger` now inherits from …
> Major refactoring of Model classes (Step 2)

- flair/data.py
- flair/datasets/relation_extraction.py
- flair/models/relation_extractor_model.py
- flair/nn/model.py
Some changes and bug fixes in the course of supporting DrugProd in Flair:
- The Dictionary object no longer gives a default return value if the key is not present, gives error instead
- The Corpus downsampling logic checks first if a split is present
- Sentence splitter in DrugProd is set to Sektok by default
- GENE-N and GENE-Y are mapped to GENE
- Fix errors that occur if the forward pass has no candidates to label
- Fix prediction of no label
> Adaptations for DrugProd Relation Extraction task

- flair/datasets/__init__.py
- flair/datasets/document_classification.py
- flair/datasets/text_text.py
- resources/docs/TUTORIAL_6_CORPUS.md
Following datasets from GLUE were added:
- Text classification: CoLA and SST2 (which already exists as SENTEVAL_SST_BINARY so I just checked that train/dev/test splits are kept in original form and not sampled)
- Text-pair classification: MNLI, QNLI, QQP, MRPC, WNLI
The only missing dataset is Semantic Textual Similarity STS-B, which is a text-pair regression task and would probably require a TextPairRegressor model.
> Added text classification datasets from Glue benchmark 

- flair/nn/model.py
> Add per-label thresholds

- flair/models/pairwise_classification_model.py
- flair/models/text_classification_model.py
- flair/nn/model.py
> Serialize multi_label_threshold for classification models

- flair/embeddings/token.py
- flair/models/sequence_tagger_model.py
- flair/nn/model.py
The `TransformerWordEmbeddings` is currently a bottleneck on Flair's speed. This PR changes the implementation such that mini-batching is used in the class. 
Depending on the mini-batch size used this PR results in significant speed ups for model training - in my experiments I've seen speed-ups between x2 and 6x (the higher the mini batch size, the greater the speed up).
> Improve speed of TransformerWordEmbeddings

- flair/embeddings/token.py
- flair/models/entity_linker_model.py
- tests/test_embeddings.py
- tests/test_models.py
Minor improvements and big fixes.
> Small speedups

- flair/embeddings/token.py
- tests/test_embeddings.py
closes https://github.com/flairNLP/flair/issues/2416
> forward lang ids in TransformerWordEmbeddings

- flair/models/text_regression_model.py
The refactoring to Flair 0.9 unfortunately broke our `TextRegressor` model. This PR makes the model operational again. 
(A future PR should extract a regression interface similar to what we did with the classification interface, so that regression could be applied to any type of model. Then, we can finally take regression out of "beta".)
Closes #2422
> GH-2422: fix regression model

- flair/embeddings/token.py
Previously, we constructed our own attention masks and padded tensors for the forward pass through the transformer model. But the tokenizer interface of the transformer library already can take care of this, so this PR removes our implementation and replaces it with a call to the tokenizer interface.
(Functionality-wise there is no difference, just a few lines of code less.)
> Small simplification of TransformerWordEmbeddings

- flair/models/tars_model.py
Closes #2426 by adding the possibility to set confidence thresholds on multi-label prediction in TARS, and setting whether a problem is single-label or multi-label:
```python
from flair.models import TARSClassifier
tars: TARSClassifier = TARSClassifier.load('tars-base')
tars.switch_to_task('GO_EMOTIONS')
sentence = Sentence("I am happy and sad")
tars.predict(sentence)
tars.predict(sentence, label_threshold=0.01)
tars.predict(sentence, label_threshold=0.01, multi_label=False)
```
> GH-2426: multi-label tars

- flair/optim.py
- flair/trainers/trainer.py
Hi,
as suggested in [#2396](https://github.com/flairNLP/flair/issues/2396), a linear learning rate schedule can work nicely when tuning transformer models. One way to add this is to create a `LinearSchedulerWithWarmup` class that can be passed to `trainer.train()` together with the number of warmup steps as a fraction (`warmup_fraction=0.1` by default). The learning rate linearly increases from zero during warmup and decays for the rest of the training. Here’s an example:
```python
from flair.optim import LinearSchedulerWithWarmup
trainer = ModelTrainer(...,optimizer=AdamW)
trainer.train(learning_rate=2e-5,
mini_batch_size=16,
max_epochs=10,
scheduler=LinearSchedulerWithWarmup,
warmup_fraction=0.1) # warmup for 0.1 of total train steps (1 epoch) 
```
Note on using other schedulers than …
> Linear scheduler with warmup

- flair/trainers/trainer.py
Fixes a bug caused by references to `self.epoch` in `ModelTrainer`. Thanks @stefan-it for noticing this!
> Remove references to self.epoch

- flair/data.py
First check for token labels, then sentence labels.
> Minor change is label dictionary creation

- flair/models/sequence_tagger_model.py
- flair/nn/model.py
- flair/trainers/trainer.py
- flair/training_utils.py
- tests/test_sequence_tagger.py
- tests/test_text_classifier.py
This PR modifies the ModelTrainer so that it automatically stores all training parameters as a "model card" in a Flair model. This allows you to: 
- print all parameters with which a model was trained
- resume training any Flair model since the optimizer and scheduler are now stored by default
**Model cards**
When you train any Flair model, a model card will now automatically be saved. The following example trains a small POS-tagger and prints the model card in the end: 
```python
corpus = UD_ENGLISH().downsample(0.01)
tag_type = "pos"
tag_dictionary = corpus.make_label_dictionary(tag_type)
tagger = SequenceTagger(hidden_size=256,
embeddings=WordEmbeddings("glove"),
tag_dictionary=tag_dictionary,
tag_type=tag_type)
trainer = ModelTrainer(tagger, corpus)
path = …
```
> Automatic "Model Cards" for Flair models, and default ability to resume training

- flair/nn/model.py
- flair/trainers/trainer.py
Some optimizers have gigantic state dictionaries, so saving them by default turns out not to be a good idea. This PR makes checkpointing optional again.
> Make checkpointing optional

- flair/models/tars_model.py
- flair/nn/model.py
- flair/trainers/trainer.py
This PR fixes a few bugs: 
- a bug in TARS prediction if no label is predicted, but the sentence already has labels
- a bug in clearing previous labels in the predict() method of the DefaultClassifier
- loss summation in DefaultClassifier
> Small bug fixes in TARS and simple sequence tagger

- flair/data.py
With https://github.com/flairNLP/flair/issues/1529 there was already a fix for a potential endless loop in the `Sentence` class. Now we also got trapped in the same situation, but within `Span` class this time.
> GH-1529 fix infinite loop in Span::to_original_text

- flair/embeddings/token.py
Hi,
special architectures such as the recently introduced [FNet](https://arxiv.org/abs/2105.03824) do not provide an `attention_mask` for the model forward pass.
This would cause the following error, that can be reproduced with the official NER example script:
```bash
$ cd examples/ner
$ python3 run_ner.py --dataset_name WNUT_17 --model_name_or_path google/fnet-base --output_dir wnut-fnet-base-baseline --num_epochs 1 
```
Outputs:
```bash
Traceback (most recent call last):                                                                                                              
File "run_ner.py", line 186, in <module>                                                                                                      
main() …
```
> embeddings: fix attention mask for special Transformer architectures

- flair/embeddings/token.py
This PR reworks the `WordEmbeddings` to add a few features:
- embeddings are stored as a torch Embedding instead of a gensim keyedvector. That way it will never come to version issues, if gensim doesn't ensure backwards compatibility (happened to me a few times over the last 2 years)
- embeddings can be put on gpu, if wanted. For that, `WordEmbeddings('<name>', force_cpu=False)` can be used
- embeddings can be fine-tuned. For that, `FordEmbeddings('<name>', fine_tune=True)` can be used.
- the lru_cache will store indices per word instead of vector lookups. This is because the lookups shouldn't take long if calculating all indices at once (especially if using gpu). However, the regex operations and multiple lookups will remain cached.
- lru_cache is increased, as it takes …
> allow finetuning of word-embeddings

- flair/models/relation_extractor_model.py
This PR adds a few relation extraction models, trained over a modified version of TACRED. Two models are added: `relations` and `relations-fast`.
To use these models, you also need an entity tagger. The tagger identifies entities, then the relation extractor possible entities. For instance use this code: 
```python
from flair.models import RelationExtractor, SequenceTagger
sentence = Sentence("George was born in Washington")
tagger = SequenceTagger.load('ner-fast')
entities = sentence.get_labels('ner')
for entity in entities:
print(entity)
extractor: RelationExtractor = RelationExtractor.load('relations-fast')
extractor.predict(sentence)
relations = sentence.get_labels('relation')
for relation in relations:
print(relation)
```
> Add pretrained relation extraction models

- flair/embeddings/token.py
a few changes to the OneHotEmbeddings:
- allows creating OneHotEmbeddings by a Dictionary directly, in case you don't want to gather it from a corpus.
- still allows creating OneHotEmbeddings by a Corpus, using `OneHotEmbeddings.from_corpus(..)` 
- should fix https://github.com/flairNLP/flair/issues/2489 as the instance_parameters cover the Dictionary and not the Corpus -> it won't store the whole dataset and therefore reduces model size.
- allows usage of "stable embeddings" -> https://arxiv.org/abs/2110.02861 which seem to "reduce gradient variance that comes from the highly non-uniform distribution of input tokens"
- makes the `_add_embeddings_internal` method more beautiful, by removing nested loops (iterates over all tokens instead of all sentences and their tokens) and removing …
> refactor onehot embeddings

- flair/embeddings/token.py
- requirements.txt
We previously pinned gensim to be version 3.8 max, but this causes errors if installing with Python 3.9. This PR removes this version requirement and makes Flair compatible with gensim 4+.
> Compatibility with gensim 4 and Python 3.9

- flair/embeddings/document.py
- flair/embeddings/token.py
fixes and closes gh-2210, gh-2305, gh-2476, gh-2500
> default handling when Tokenizer's model_max_length is not set

- resources/docs/KOR_docs/README.md
- resources/docs/KOR_docs/TUTORIAL_10_TRAINING_ZERO_SHOT_MODEL.md
- resources/docs/KOR_docs/TUTORIAL_1_BASICS.md
- resources/docs/KOR_docs/TUTORIAL_2_TAGGING.md
- resources/docs/KOR_docs/TUTORIAL_3_WORD_EMBEDDING.md
- resources/docs/KOR_docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md
- resources/docs/KOR_docs/TUTORIAL_5_DOCUMENT_EMBEDDINGS.md
- resources/docs/KOR_docs/TUTORIAL_6_CORPUS.md
- resources/docs/KOR_docs/TUTORIAL_7_TRAINING_A_MODEL.md
- resources/docs/KOR_docs/TUTORIAL_8_MODEL_OPTIMIZATION.md
- resources/docs/KOR_docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md
Hello, we are juniors majoring in software at Gachon University in Korea.
We have translated the tutorials into Korean.
We Created Korean version Tutorials (1~10) and README.md
Please response our pull request.
> Add korean Flair Tutorials

- flair/models/__init__.py
- flair/models/dependency_parser_model.py
- flair/visual/tree_printer.py
- requirements.txt
This PR adds dependency parser model based on [Deep biaffine attention for neural dependency parsing](https://arxiv.org/pdf/1611.01734.pdf). The main model in paper uses a static word embedding and POS tags vector as input, while it only uses StackedEmbeddings. 
The first trained model can be downloaded from [here](https://drive.google.com/file/d/1knTksQjnflvpWz-EC7St_7ox99GG5AIJ/view?usp=sharing). It was trained with Glove and Flair embeddings on flair.datasets.UD_ENGLISH dataset. If I understand correctly, the UD_ENGLISH dataset in flair library, only contains the "EWT" version, not the other ones mentioned in [this](https://universaldependencies.org). In the end, the following results were obtained:
**UAS : 0.9032 - LAS : 0.9243**
In the near future, I will train the model on PTB …
> Dependency parser

- flair/embeddings/token.py
The `TransformersWordEmbeddings ` forward pass was not put within the `gradient_context`. Hence the forward pass was not encapsulated within the `torch.no_grad()` in case `fine_tuning = False` is set  . This fix improves GPU memory management and speed.
> Updated token.py for gradient calculations

- flair/models/dependency_parser_model.py
This PR makes two changes to the `DependencyParser`: 
- fixes #2575 by converting loss tensors to floats before printing
- adds the option of not using an rnn (set `use_rnn=False` when instantiating)
> Dependency parser experiments

- flair/embeddings/base.py
apparently the logic of the Transformers tokenizers is that if the sequence lenght exceeds a very large number, it counts as infinitive. 
this includes models like DebertaV3 but also XLNetModel.
For TransfoXLModel I couldn't test if this logic is valid, as I didn't find any model when searching for it in the HF modelhub
> long sequence transformers of any kind

- flair/__init__.py
- flair/data.py
- flair/embeddings/base.py
- flair/embeddings/document.py
- flair/embeddings/token.py
- flair/models/sequence_tagger_model.py
- flair/trainers/trainer.py
- flair/training_utils.py
Refactoring of embedding logic for data points: 
- removes the global variable `embedding_storage_mode`
- moves up `set_embedding()` and `to()` from the data point classes (`Sentence`, `Token`, etc.) to their parent `DataPoint`
- allows dynamic embedding names to be passed to `store_embeddings` for small speed up
- the `set_embedding()` method no longer transfers embeddings to `flair.device` (only when getting this is done now)
- `DocumentPoolEmbeddings` class can now be instantiated only with a single embedding
> Refactor embedding logic for data points

- flair/embeddings/base.py
- tests/test_embeddings.py
Solves https://github.com/flairNLP/flair/issues/2614
context:
The slow variant of tokenizers relies on sentencepiece which are saved in the respective files defined in `vocab_files_names`, when a fast tokenizer is created and will be saved, it creates a `tokenizer.json` file which basically contains all information, however it still tries to persist the `vocab_file_names` even if they are not required anymore. It cannot recreate the `vocab_file_names` without rebuilding the sentencepiece objects, so it rather tries to copy the file, if one is specified.
Excluding those files makes those not be specified → it won't try to copy the file
> fix reloading fast tokenizers

- flair/hyperparameter/__init__.py
- flair/hyperparameter/param_selection.py
- flair/hyperparameter/parameter.py
- flair/trainers/trainer.py
- pyproject.toml
- requirements.txt
- resources/docs/KOR_docs/TUTORIAL_8_MODEL_OPTIMIZATION.md
- resources/docs/TUTORIAL_8_MODEL_OPTIMIZATION.md
- tests/test_hyperparameter.py
This PR reintroduces hyperparameter tuning in Flair
closes #2632
A number of small changes was required so I split this PR into appropriately named commits where each commit is an isolated change to the code base. For example, there is a separate commit that reverts the deletion or hyperparameter tuning in Flair - this helps us quickly see which code changes are new and which simply reintroduce the old code.
The changes and their corresponding commits include:
1. [Revert "Removes hyperparameter features"](https://github.com/flairNLP/flair/commit/c9591b9482afcd3971497fe88afb14bc394bd516)[](https://github.com/tadejmagajna)  Reverts the removal of all hyperparameter runing code
2. [Updating the param selection docs for the v0.10 syntax](https://github.com/flairNLP/flair/commit/32ebc4c13ddfceb …
> Reintroduce hyperparameter tuning

- flair/models/language_model.py
close: #2503
close: #2554
There are already similar special treatments like https://github.com/flairNLP/flair/blob/master/flair/embeddings/token.py#L724 and https://github.com/flairNLP/flair/blob/master/flair/models/language_model.py#L190, but we will still need this for pre-trained `SequenceTagger` or alike to be pickle-able (for Dill and/or multiprocessing).
> fix: patch the missing `document_delmiter` for `lm.__get_state__()`

- flair/datasets/sequence_labeling.py
- tests/test_datasets.py
Hi,
this PR adds support for v2.0 of the HIPE-2022 dataset.
The following changes were introduced:
* Version number is now part of the (internal, chached) dataset path. Now, `~/.flair/datasets/ner_hipe_2022` gets the version number appended, e.g. `~/.flair/datasets/ner_hipe_2022/v2.0`.
* The branch name argument is added to the `NER_HIPE_2022` constructor. It is now possible to specify the desired branch name for the HIPE upstream data repo.
* New splits (train and dev) for German, English and French for the AJMC dataset are introduced with the v2.0.
* SONAR Dev split is updated.
* NewsEye German train split is filtered (removal of unannotated documents).
* Extensive tests for label dictionary (all datasets/languages/splits) added.
PR in the HIPE upstream data repo: …
> Add support for v2.0 of HIPE-2022 data

- resources/docs/embeddings/ONE_HOT_EMBEDDINGS.md
Changed the documentation on OneHotEmbeddings to reflect changes in the master version. Specifically, to use `OneHotEmbeddings.from_corpus()` instead of `OneHotEmbeddings()`.
> Changed the documentation on OneHotEmbeddings

- README.md
- flair/__init__.py
- flair/data.py
- flair/datasets/sequence_labeling.py
- flair/models/relation_extractor_model.py
- flair/models/sequence_tagger_model.py
- flair/models/sequence_tagger_utils/bioes.py
- flair/nn/model.py
- resources/docs/TUTORIAL_10_TRAINING_ZERO_SHOT_MODEL.md
- resources/docs/TUTORIAL_1_BASICS.md
- resources/docs/TUTORIAL_2_TAGGING.md
- resources/docs/TUTORIAL_6_CORPUS.md
- resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md
- setup.py
- tests/test_datasets.py
- tests/test_hyperparameter.py
- tests/test_labels.py
- tests/test_sentence.py
This PR makes final changes for the upcoming release: 
- bumps Flair version numbers
- changes and unifies printout logic across all DataPoint classes
- updates pre-trained RE model
- fixes error in BIOES tags introduced by refactor
- a few extra unit tests
> GH-2689: Documentation and printout changes for release

- resources/docs/HUNFLAIR.md
- resources/docs/HUNFLAIR_TUTORIAL_1_TAGGING.md
- resources/docs/TUTORIAL_2_TAGGING.md
There are a number of minor issues that have accumulated in tutorials over time, especially as part of the changes introduced in the recent 0.11 release.
This PR fixes:
- missing `from flair.data import Sentence` in _TUTORIAL_2_TAGGING.md_
- minor Python indentation fixes in _TUTORIAL_2_TAGGING.md_
- usage of `get_spans()` that now needs a `type` parameter
- updates to new `Sentence` and `Span` string representations
> Minor fixes to tutorials

- flair/tokenization.py
Fixes #2710 
Makes sure the words are added to the correct list variable and that strings (not SpaCy Token objects) are returned.
> Fix the SciSpacyTokenizer.tokenize() bug

- flair/datasets/sequence_labeling.py
Hi,
this PR adds the possibility to use a custom preprocessing function for the HIPE-2022.
This would e.g. allow to use custom de-hyphenation or label normalization extensions defined in the preprocessing function.
> datasets: add possibility to use custom preprocessing function for HIPE-2022

- flair/datasets/relation_extraction.py
- flair/datasets/sequence_labeling.py
This PR adds the option to ignore selected labels in any dataset that inherits from `ColumnCorpus` (i.e. nearly all datasets in Flair).
You can use the label_name_map to achieve this, by mapping all labels you don't want to learn to 'O'. The following snippet shows how to rename and ignore WNUT 17 labels so that it looks like the NER classes from CoNLL-03: 
```python
from flair.datasets import WNUT_17
corpus = WNUT_17(in_memory=False)
print(corpus.make_label_dictionary('ner'))
corpus = WNUT_17(in_memory=False, label_name_map={
'person': 'PER',
'location': 'LOC',
'group': 'ORG',
'corporation': 'ORG',
})
print(corpus.make_label_dictionary('ner'))
corpus = WNUT_17(in_memory=False, label_name_map={
'person': 'PER',
'location': 'LOC',
'group': 'ORG',
'corporation': 'ORG',
'product': 'O', …
```
> GH-2717: Add option to ignore labels in dataset

- flair/datasets/sequence_labeling.py
- tests/test_datasets.py
Hi,
this PR adds support for latest version 2.1 of HIPE-2022 dataset.
It mainly fixes a label correction in the HIPE-2020 French data (training split), and some adjustments in AJMC, see [release notes](https://github.com/hipe-eval/HIPE-2022-data/releases/tag/v2.1).
Closes #2734
> datasets: add support for version 2.1 of HIPE-2022

- flair/embeddings/token.py
As reported in #2742, there was a problem with getting the `embedding_length` from the `PooledFlairEmbeddings`.
The `@proberty` decorator was missing above the `embedding_length` method of the PooledFlairEmbedding class.
I added it in token.py (line 868), so now it's:
```
@property
def embedding_length(self) -> int:
return self.__embedding_length
```
This should resolve the problem in #2742.
> #2742 added missing property decorator in PooledFlairEmbeddings

- flair/data.py
- flair/datasets/biomedical.py
- flair/datasets/sequence_labeling.py
- flair/datasets/treebanks.py
- flair/embeddings/token.py
- tests/test_datasets.py
- tests/test_tokenize_sentence.py
Related to the issue #2720.
One quick question, I do not fully understand the purpose of lines 789-791 in data.py:
```python
if token.start_position == 0 and len(self) > 0:
token.start_pos = len(self.to_original_text()) + self[-1].whitespace_after
token.end_pos = token.start_pos + len(token.text)
```
Why are you taking the length of the sentence (since self refers to the sentence here) to get start_pos parameter?
> GH-2720: handle consecutive whitespaces

- requirements.txt
The dependency and the pin were added in https://github.com/flairNLP/flair/pull/2312/files. more-itertools is a pretty stable library and the one function that is used has been present for the last 6 major versions.
> Remove unnecessary more-itertools pin

- .github/workflows/ci.yml
- flair/__init__.py
- flair/file_utils.py
cache models/datasets that are used in pytest. This should speed up tests on all parts that involve downloading flair or huggingface specific models/embeddings/datasets.
If at some point the cache leads to incorrect tests (e.g. a model is updated without getting a new name), the cache can be reset by updating `key: cache-v1` to `key: cache-v<n>` (n being an incremental number) such that the next pass downloads all models again. The old cache key will then be available for one more week and then be automatically deleted.
This PR also fixes a small bug, where cached paths have repeated folder structure if the cached path (e.g. setting the cache folder to `cache/flair` lead to the structure being `cache/flair/cache/flair/embeddings/...` instead of `cache/flair`
comparing the last two test …
> github actions cache

- flair/embeddings/__init__.py
- flair/embeddings/legacy.py
Closes #2763 
The recent transformers update (4.19.0, see https://github.com/huggingface/transformers/pull/17049) removed the sacremoses dependency which was required by a legacy embedding class in Flair (marked as deprecated since Flair 0.4.5). This PR fixes the issue by removing the legacy class. 
(All other legacy embeddings in Flair should be removed as well before the next bigger release to avoid such problems in the future.)
> GH-2763: remove legacy TransformerXLEmbeddings class

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- flair/models/clustering.py
- tests/test_embeddings.py
The transformers library has discontinued support for python 3.6 and we will likely soon as well. For now, this PR switches unit testing to python 3.7 so that errors like #2765 are caught earlier.
> GH-2765: Test with Python 3.7

- flair/datasets/relation_extraction.py
Hello,
I found a wrong boolean check-in in `relation extraction conll04 loading` scripts in line [375](https://github.com/flairNLP/flair/blob/f44e7e14e7b9cc9abb517d4488ad368684d3d395/flair/datasets/relation_extraction.py#L375)
I have removed the wrong boolean from the line and it seems fine now.
Please check the details and if possible merge this pull request.
Thanks and regards
Sagor
> remove wrong boolean check for loading datasets RE_ENGLISH_CONLL04

- flair/trainers/trainer.py
The train() method of trainer.py accepts an eval_on_train_fraction parameter, with either a float or "dev" literal string value (see docstring). This commit adds the "dev" literal option to the type hint.
> more precise type hint for eval_on_train_fraction

- flair/datasets/__init__.py
- flair/datasets/base.py
- tests/test_corpus_dictionary.py
With 0.11, SentenceDataset was renamed to FlairDatapointDataset. There was
no deprecation or fall-back, this code adds the deprecation fallback with
a message to guide users to the new class name.
Alternatively, the deprecation could also be removed, allowing the
SentenceDataset class to continue without warning.
> Add deprecation warning for SentenceDataset rename

- flair/data.py
- tests/test_corpus_dictionary.py
Fixes some cases where .get_tag() was still being called on tokens.
Removed Sentence.__copy__ method, which was not working for multiple
reasons (not only get_tag). We could fix __copy__, is it used?
> Fix left-over cases of token.get_tag(), which was renamed

- flair/datasets/sequence_labeling.py
- tests/test_datasets.py
The current JsonlDataset does not set "O" labels on sentence tokens that are not explicitly labeled otherwise, but it claims to do so in the source code. This fixes the code to actually set "O" on each token.
> JsonlDataset: Fix code that claims to set "O" labels to actually set them

- resources/docs/TUTORIAL_6_CORPUS.md
Hi,
this PR mentions the recently added HIPE-2022 dataset (c.f. #2675 or #2684) in the corpus tutorial.
> docs: mention HIPE-2022 in corpus tutorial

- flair/datasets/sequence_labeling.py
- tests/test_datasets.py
Hi,
this PR adds test data for the HIPE-2022 shared task.
Test data for all datasets were recently released, see their release notes: https://github.com/hipe-eval/HIPE-2022-data/releases/tag/v2.1-test-all-unmasked
> GH-2786: Add test data for HIPE-2022

- flair/models/sequence_tagger_model.py
- requirements.txt
The newest release of the huggingface hub releases a new way of downloading models with additional features such as lazy loading and  git-aware cache file layouting.
I suppose there is no good reason to use older versions, so I added a pin of the version to force upgrades
> update hf-hub version

- examples/ner/run_ner.py
- flair/data.py
- resources/docs/HUNFLAIR_TUTORIAL_2_TRAINING.md
- resources/docs/KOR_docs/TUTORIAL_7_TRAINING_A_MODEL.md
- resources/docs/KOR_docs/TUTORIAL_8_MODEL_OPTIMIZATION.md
- resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md
- resources/docs/TUTORIAL_8_MODEL_OPTIMIZATION.md
- tests/test_models.py
- tests/test_sequence_tagger.py
The `<unk>` token is a common practice to have a mechanism to add labels that are not common enough for training. This mainly relates to classification and basically simulates an "others" category.
However, for NER, we have a different mechanism with the `O-tag`, hence I don't think `<unk>` has any practical use.
Using `<unk>` for NER can lead to down-weighting the overall score when the NER-model is not trained long enough (random apperances of `<unk>` still happen. See (https://github.com/flairNLP/flair/issues/2762 and https://github.com/flairNLP/flair/issues/2761) and can break pipelines, that do not expect entities marked as `unk` (https://github.com/flairNLP/flair/issues/2224).
I propose making the `<unk>` optional, per default `True`, but allow disableling it for all ner-tasks. As …
> make `add_unk` optional and don't use it for ner

- requirements.txt
fixes https://github.com/flairNLP/flair/issues/2833
As flair doesn't use sentencepiece itself, but lets transformers use it indirectly, I propose to let the transformers package handle that dependency. 
This has two advantages:
a) we can use a more broad range of sentencepiece versions
b) if there are any new versions that break something, the transformers guys will handle it
Note: relies on https://github.com/flairNLP/flair/pull/2827 to be merged first for passing tests
> use transformers sentencepiece requirement

- flair/data.py
- tests/test_sentence.py
Currently there is a bug when calling set_label on a Token or Span, this will also call set_label on the surrounding sentence. This will remove any other labels in this label_type, from the point of view of the Sentence.
```
>>> from flair.data import Sentence
>>> s = Sentence("one two three")
>>> s[0].set_label("ner", "B-Number")
>>> s
Sentence: "one two three" → ["one"/B-Number]
>>> s[1].set_label("ner", "I-Number")
>>> s
Sentence: "one two three" → ["two"/I-Number]
```
> Do not remove other labels of sentence for set_label on Token and Span

- flair/models/sequence_tagger_model.py
Replace `logging.warn` (deprecated in [Python 2.7, 2011](https://github.com/python/cpython/commit/04d5bc00a219860c69ea17eaa633d3ab9917409f)) with `logging.warning` (added in [Python 2.3, 2003](https://github.com/python/cpython/commit/6fa635df7aa88ae9fd8b41ae42743341316c90f7)).
* https://docs.python.org/3/library/logging.html#logging.Logger.warning
* https://github.com/python/cpython/issues/57444
> Replace deprecated logging.warn with logging.warning

- flair/embeddings/base.py
Torch now gives a signature to `torch.split` returning a `List[Tensor]` which broke mypy since `normed_weights`, a `Tensor`, was being assigned a `List[Tensor]`. This PR fixes this by introducing a new variable.
> Rename variable to fix mypy issue

- requirements-dev.txt
As long as https://github.com/tholo/pytest-flake8/pull/88 is not merged, flake8 need to be set to version 4.
i suggest this PR as a temporary fix until the plugins are up to date again.
> pin flake8 to v4

- flair/trainers/trainer.py
This PR adds a parameter to set a factor on the learning rate of the decoder, if fine-tuning a model. 
Usage: 
```python
trainer.fine_tune(f"path/to/output/folder",
mini_batch_size=4,
learning_rate=5e-5,
decoder_lr_factor=10,
)
```
> Convenience method for learning rate factor

- pyproject.toml
I have absolutely no idea why this is necessary, but the old way of ignoring types withing the `legacy.py` file doesn't work anymore.
> use a different way for mypy to ignore the legacy embeddings when typechecking

- flair/embeddings/transformer.py
- tests/test_embeddings.py
Hi,
this PR fixes a fast tokenizer reload bug when using the BigScience Bloom Model.
I got the following error message when fine-tuning a Bloom Model for NER:
```bash
Traceback (most recent call last):                                                                                              
File "run_ner.py", line 160, in <module>                                                                                  
main()                                                                                                                  
File "run_ner.py", line 140, in main                                                                                                                                                                                    
trainer.fine_tune( …
```
> Fast tokenizer reload fix pt.2: Bloom model

- flair/datasets/sequence_labeling.py
- tests/test_datasets.py
since some refactoring, NER labels will be added as span labels instead of following the BIO or BIOES tagging shemas.
This PR updates the JsonlCorpus to follow the newer way of labels and therefore recreates compatibility for JsonlCorpus for Ner trainings
> Make JsonlCorpus create span labels

- flair/datasets/text_text.py
- flair/file_utils.py
- flair/models/entity_linker_model.py
- flair/models/lemmatizer_model.py
- flair/models/multitask_model.py
- flair/models/pairwise_classification_model.py
- flair/models/relation_extractor_model.py
- flair/models/sequence_tagger_model.py
- flair/models/tars_model.py
- flair/models/text_classification_model.py
- flair/models/text_regression_model.py
- flair/models/word_tagger_model.py
- flair/nn/decoder.py
- flair/nn/model.py
- tests/test_entity_linker.py
- tests/test_relation_classifier.py
- tests/test_text_regressor.py
First PR about https://github.com/flairNLP/flair/issues/2640: refactoring models, such that each model has a `_prepare_tensors` and a `forward` method, where one extracts all tensors out of the data points and the latter only does tensor computations.
That way, JIT tracing and ONNX conversation of the models should be possible.
**Notice:** this is not expected to give a huge speedup, as most computation is within the embeddings, which won't be affected. Due to that, the ONNX conversion is also not documented. 
This PR also adds unit scaling for model downloads when a non-huggingface model is downloaded.
This PR also fixes a bug, that relation extraction models without weight_dict set can be loaded.
This PR also fixes an encoding error, if glue-mnli is loaded on a windows machine
This PR …
> GH-2640: tensor forward

- pyproject.toml
fixes the testing issues on the current master.
To answer https://github.com/flairNLP/flair/pull/2897#issuecomment-1233082553 :
All the senteval datasets download and unpack a zip file. This zip file contains a very old python 2.7 file which doesn't comply with the isort-flake8-mypy and python3 standards.
As the cache folder is set into the model repo and the tests collect for any file in the repo, hence also that old one.
This PR specifies for pytest where to search for tests, therefore randomly existing files won't be added anymore.
> specify test paths

- flair/models/lemmatizer_model.py
- flair/models/multitask_model.py
- flair/models/sequence_tagger_utils/viterbi.py
- flair/models/tars_model.py
- flair/models/text_regression_model.py
- flair/nn/model.py
- flair/trainers/trainer.py
Closes #2928 by making sure that all losses are summed over all points, instead of averaged. Also changes the forward_loss signature to always return a tuple consisting of the loss and the number of points.
> GH-2928: Unify loss reduction

- flair/data.py
- flair/file_utils.py
Closes #2972 
The `.text` property of the `Sentence` and `Span` object currently print a whitespace tokenized version of the string. This PR changes this so that `.text` will print the untokenized string instead. 
```python
sentence = Sentence("George   Washington was here")
entity = sentence.get_span(0, 2)
print(entity)
print(entity.text)
```
This now prints: 
```console
Sentence: "George   Washington was here"
Span[0:2]: "George   Washington"
George   Washington
```
Before, it printed: 
```console
Sentence: "George Washington was here"
Span[0:2]: "George Washington"
George Washington
```
> GH-2972: Change output of .text to original string

- flair/data.py
- flair/embeddings/token.py
Small code optimizations: list comprehensions, remove `torch.cat` calls. Especially the latter leads to significant improvements in runtime if only using a single embedding.
Reduces training time in my training script from 10,643 to 8,248 ms.
> Small speed optimizations

- flair/data.py
- flair/nn/model.py
- flair/trainers/trainer.py
- requirements-dev.txt
This PR changes the printout such that time-elapsed (in seconds) is printed during an epoch. 
Before: 
```console
2022-09-03 21:40:57,619 ----------------------------------------------------------------------------------------------------
2022-09-03 21:41:01,344 epoch 1 - iter 122/1227 - loss 0.93329908 - samples/sec: 131.96 - lr: 0.000030
2022-09-03 21:41:04,131 epoch 1 - iter 244/1227 - loss 0.74046559 - samples/sec: 176.79 - lr: 0.000030
2022-09-03 21:41:06,914 epoch 1 - iter 366/1227 - loss 0.64291181 - samples/sec: 177.01 - lr: 0.000030
2022-09-03 21:41:10,129 epoch 1 - iter 488/1227 - loss 0.60704054 - samples/sec: 153.07 - lr: 0.000030
```
After: 
```console
2022-11-08 11:14:26,681 ---------------------------------------------------------------------------------------------------- …
```
> Add time elapsed to training printout

- flair/models/relation_classifier_model.py
This PR removes the leftovers (in the code and docstrings) from #2748 of the relation classifier remainder logic.
> Remove Leftovers of the Relation Classifier Remainder Logic

- flair/data.py
- flair/datasets/biomedical.py
- flair/datasets/entity_linking.py
- flair/datasets/relation_extraction.py
- flair/datasets/sequence_labeling.py
- flair/models/regexp_tagger.py
- tests/test_datasets.py
- tests/test_sentence.py
- tests/test_tokenize_sentence.py
This PR refactors the Token and Sentence positional properties inherited from the DataPoint to replace the `self.start_pos` and `self.end_pos` attributes.
For the Sentence, both variants of accessing positional information behaved differently, resulting in inconsistent results where they appropriately should have been aliases. These are the inconsistencies:
1. Initializing the Sentence with `str`, i.e. untokenized input.
- We allow the user to set an offset `start_position` in the init but this is not respected in the `start_position` property. It always returns zero. The inconsistency is also that in `start_pos` the start position offset is included. 
**Suggestion**: Only use and expose the property inherited from the DataPoint. Having multiple attributes doing the same thing with …
> Refactor Token and Sentence Positional Properties

- flair/data.py
- flair/datasets/biomedical.py
- flair/datasets/entity_linking.py
- flair/datasets/relation_extraction.py
- flair/splitter.py
- flair/tokenization.py
- tests/test_datasets_biomedical.py
- tests/test_tokenize_sentence.py
When initializing a `Sentence` object, with `use_tokenizer=True` (set by default), it triggered an import of the `SegtokTokenizer` in the Sentence constructor. According to [this thread](https://stackoverflow.com/questions/29504313/python-what-is-the-cost-of-re-importing-modules), there is a cost of re-importing modules and since we often create large numbers of `Sentence` objects, this is unnecessary overhead. 
This PR makes the import global. To do this, it splits up the `flair.tokenization` module into tokenization (for all tokenizers) and splitter (for all sentence splitters). This way, there is no longer an import of `flair.data` in `flair.tokenization`.
> Restructure Tokenizer and Splitter modules

- flair/trainers/trainer.py
Saving `Path` objects in Pickle can lead to OS incompatibilities, as `Path` is resolved to either `PosixPath` (linux) or `WindowsPath` (windows).
As the model card saves the training parameters, calling with a path can lead that models trained on a linux docker won't be loadable on any Windows machine (and reversed).
This PR gives a simple fix by converting each path to a string before adding it to the ModelCard
> do not save Path objects to model cards

- flair/models/sequence_tagger_model.py
- tests/models/test_sequence_tagger.py
Small fix for https://github.com/flairNLP/flair/issues/3009
> save initial hidden states in sequence tagger

- flair/datasets/sequence_labeling.py
- tests/test_datasets.py
Hi,
this PR adds support for the recently released version 2 of the MasakhaNER dataset!
A new version argument was added and now defaults to "v2" of the dataset. Demo usage:
```python
from flair.datasets import NER_MASAKHANE
v1_all = NER_MASAKHANE(languages="all", version="v1")
v2_all = NER_MASAKHANE(languages="all", version="v2")
```
Closes #2971.
This PR also adds some unittests for v1 and v2 of the dataset. Here's a comparison between the number of sentences, that are mentioned in the paper and the "Parsed" ones with this implementation:
[Version 1](https://arxiv.org/abs/2103.11811) - bold denotes difference:
| Language | Paper (Train, Dev, Test) | Flair (Train, Dev, Test)
| -------- | ------------------------ | ------------------------
| `amh`    | 1750 / 250 / 500         | 1750 / …
> Add support MasakhaNER v2 dataset

- flair/embeddings/transformer.py
When using [layoutlm-base-cased](https://huggingface.co/microsoft/layoutlm-base-cased), the model is initialized with a RobertaTokenizer instead of a LayoutLMTokenizer.
As RobertaTokenizer usually doesn't use ocr boxes, we need to set `embedding.needs_manual_ocr=True`. I just figured out, that that attribute doesn't persist, providing a score drop of about 70% when reloading the model.
This PR fixes the presistence for that attribute.
> persist needs_manual_ocr

- flair/datasets/biomedical.py
This PR fixes links to datasets that are no longer available at their original location. Instead the links now target the newly created hunflair-corpora repository.
> HunFlair: Fix links to datasets that are no longer available

- flair/embeddings/token.py
- flair/models/sequence_tagger_model.py
- resources/docs/TUTORIAL_2_TAGGING.md
- resources/docs/embeddings/FLAIR_EMBEDDINGS.md
Added links for Ukrainian forward and backward Flair embeddings:
```python3
from flair.embeddings import FlairEmbeddings
flair_uk_forward = FlairEmbeddings('uk-forward')
flair_uk_backward = FlairEmbeddings('uk-backward')
```
and two taggers: NER and POS
```python3
ner_tagger = SequenceTagger.load('ner-ukrainian')
pos_tagger = SequenceTagger.load('pos-ukrainian')
sentence = Sentence("Сьогодні в Знам’янці проживають нащадки поета — родина Шкоди.")
ner_tagger.predict(sentence)
pos_tagger.predict(sentence)
```
> Load Ukrainian embeddings and taggers

- flair/datasets/sequence_labeling.py
- flair/embeddings/token.py
- tests/models/test_entity_linker.py
regarding https://github.com/flairNLP/flair/issues/3018
`str.split(text, s)` creates a lsit with up to s+1 entries,
hence to have 2 entries, s needs to be 1.
Besides that, I suppose that the entry doesn't contain valid metadata if it starts with "#"
> fix comment parsing for conllu datasets

- flair/embeddings/transformer.py
- flair/trainers/trainer.py
This PR does 2 little things:
* it makes it easier to clean up the gpu memory, by cleaning gradients and deleting the reference of the optimzier. Hence `torch.cuda.empty_cache()` will be able to clean up more parameters. 
* some (slow) tokenizers like RobertaTokenizer seem to add a [SEP] token at the end, breaking the legacy subword token mapping, which is fixed by allowing that specific token
> Release optimizer memory and fix legacy tokenization

- flair/embeddings/__init__.py
In file: __init__.py, the list named __all__ contains an undefined name which can result in errors when this module is imported. We removed the undefined name from the list. 
This is following the best practices of importing fields from a package (https://docs.python.org/3/tutorial/modules.html#importing-from-a-package).
> Removed a name that is undefined

- flair/models/tars_model.py
- pyproject.toml
- tests/test_hyperparameter.py
Fixes a small error in TARS tagger prediction that in some cases caused tokens to be annotated with multiple tags.
> Change indexing in TARSTagger predict

- flair/data.py
- flair/datasets/ocr.py
- flair/datasets/sequence_labeling.py
- flair/models/lemmatizer_model.py
- flair/models/relation_classifier_model.py
- flair/models/sequence_tagger_model.py
- flair/models/tars_model.py
- flair/models/text_regression_model.py
- flair/nn/model.py
- tests/model_test_utils.py
This PR is fixing https://github.com/flairNLP/flair/issues/3024 and adds the following changes while doing so:
* tars models (classifcation & ner) won't fail on labels with only 1 character.
* models that predict on modified sentences (`TARSClassifier`, `TARSTagger` and `RelationClassifier`) now also make use of the context and therefore can be trained and tested in a flert manner.
* Empty sentences will not be discarded in the context chain, however they won't change the context as they are empty.
* it is possible to disable context, by setting `sentence._has_context = True` without setting `sentence._next_sentence` or `sentence._previous_sentence`. That way, batch prediction on context independent sentences will work.
* context is considered to be set if only "_next_sentence" is set. So …
> Improved Tars Context

- flair/data.py
- flair/embeddings/transformer.py
- tests/embeddings/test_transformer_word_embeddings.py
This PR adds the option of setting a "context separator" to Transformer embeddings.  If set, a new special token is added to the transformer tokenizer dictionary. This token is at the beginning and end of a Sentence to separate it from context. 
To use the example from #3063: 
Assume the current sentence is `Peter Blackburn` and the previous sentence ends with `to boycott British lamb .`, while the next sentence starts with `BRUSSELS 1996-08-22 The European Commission`. 
In this case,
1. if `use_context_separator=False`, the embedding is produced from this string: `to boycott British lamb . Peter Blackburn BRUSSELS 1996-08-22 The European Commission` 
2. if `use_context_separator=True`, the embedding is produced from this string `to boycott British lamb . [KONTEXT] Peter Blackburn …
> Explicit context boundaries in Transformer embeddings

- flair/embeddings/transformer.py
- tests/embeddings/test_transformer_document_embeddings.py
- tests/embeddings/test_transformer_word_embeddings.py
Fixes #3077 and adds a unit test
> GH-3077: fix context loading

- flair/datasets/__init__.py
- flair/datasets/entity_linking.py
Adds the ZELDA dataset for training and evaluating entity linking, introduced in our upcoming EACL paper "ZELDA: A Comprehensive Benchmark for Supervised Entity Disambiguation".  
This snippet shows how to load the corpus and inspect the entity links.
```python
from flair.datasets import ZELDA
corpus = ZELDA()
print(corpus)
sentence = corpus.test[1]
for entity in sentence.get_labels('nel'):
print(entity)
```
> Adds ZELDA Entity Linking dataset

- flair/models/multitask_model.py
The `_label_type` field of the `MultitaskModel` is currently a dict, whereas for all other models it is a string. This PR sets the _label_type to the last predicted label_type in a multitask model.
> Correct label_type of MultitaskModel

- flair/embeddings/base.py
- flair/models/multitask_model.py
- flair/trainers/trainer.py
- flair/training_utils.py
This PR fixes https://github.com/flairNLP/flair/issues/3097 by introducing an `evaluate_all` parameter. That way, users can use `multitask_model.evaluate(corpus.test, gold_label_type="Task_0", evaluate_all=False)` to evaluate the first task. If `evaluate_all` is set to true, the value of `gold_label_type` will be ignored and every task will be evaluated on their respective label type.
While doing this implementation I also noticed, that the evaluation currently evaluates sentences that have multiple tasks annotated to be evaluated for only one random task. -> now the evaluation uses all sentences for all tasks they are assigned to as it should be expected.
I also added the possibilities to compute the loss of a sentence on all assigned tasks during training. Hence Training Knowledge Graph …
> gh-3097: fix multitask model training

- .pre-commit-config.yaml
closes gh-3090. see reference [here](https://github.com/home-assistant/core/issues/86892).
> GH-3090: fix pre-commit bug by upgrading to isort 5.12.0

- flair/models/entity_linker_model.py
- flair/nn/model.py
Entity Linking has been shown to profit from candidate lists that contain for a mention a list of possible disambiguation targets. 
This PR integrates candidate lists as loss masking into the EntityLinker. It also integrates the ZELDA candidate lists for convenience. 
Example for initializing the ZELDA candidate lists and retrieving candidates for a string.
```python
generator = CandidateGenerator(candidates="zelda", lower_case=False)
print(generator.get_candidates("Pence"))
```
Example for initializing an EntityLinker with a candidate generator:
```python
linker = EntityLinker(
embeddings,
label_dictionary=tag_dictionary,
pooling_operation="first",
candidates=CandidateGenerator("zelda") 
)
```
> ZELDA candidate lists in EntityLinker

- .travis.yml
- Pipfile
- README.md
- pyproject.toml
- setup.py
As python 3.6 is no longer supported, we are increasing minimal python version for flair to 3.7.
> Bump python requirement to 3.7

- flair/data.py
- flair/models/tars_model.py
- tests/test_corpus_dictionary.py
This PR enables uniform label noise simulation in any dataset available in Flair via an additional method in the Corpus class.
> Enable uniform label noise generation

- flair/models/__init__.py
- flair/models/entity_linker_model.py
- flair/models/multitask_model.py
- flair/models/relation_classifier_model.py
- flair/models/relation_extractor_model.py
- flair/models/sequence_tagger_model.py
- flair/models/tars_model.py
- flair/models/text_classification_model.py
- flair/models/text_regression_model.py
- flair/models/word_tagger_model.py
- flair/nn/model.py
Add return types to `load()` function so that type hints become possible when loading models: 
```python
from flair.nn import Classifier
model = Classifier.load('ner')
```
It also changes the internal packaging of the hunflair bio NER taggers to use the general `MultitaskModel`. They can now be loaded like all other models with: 
```python
from flair.nn import Classifier
model = Classifier.load('bioner')
```
The `MultiTagger` class, specifically created for the hunflair tagger, is removed.
> Add return types to Model and Classifier

- flair/models/entity_linker_model.py
This PR closes #3122 . Instead of being concatenated before averaging, the entity embeddings should be stacked.
> GH-3122: Fix Avg Pooling in the Entity Linker

- flair/models/lemmatizer_model.py
In `lemmatizer_model.py`, the method `token.get_tag()` is used which does not seem to exist (any more). Suggested fix: Change to `token.get_label()`.
> Change token.get_tag() to token.get_label()

- requirements.txt
`flair/embeddings/transformer.py` has the import statement `from transformers.utils import PaddingStrategy`. That is only available from version 4.18.0 of the transformers library. Up until version 4.17.0 it is called `transformers.file_utils.PaddingStrategy`.
> Update required version of transformers library

- flair/splitter.py
- flair/tokenization.py
- resources/docs/HUNFLAIR.md
- resources/docs/HUNFLAIR_TUTORIAL_1_TAGGING.md
For processing biomedical text we offer special classes for sentence splitting and tokenization based on the SciSpacy library. We used a rather old version of the library. This PR updates the (recommended) version of the library, i.e.
```
pip install scispacy==0.5.1
pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_core_sci_sm-0.5.1.tar.gz 
```
> Update scispacy version

- flair/datasets/sequence_labeling.py
- flair/models/__init__.py
- flair/models/dual_encoder.py
Suggestions for refactoring the DualEncoder (less masking/padding, more comments)
Further suggestions (not covered): 
- the forward is awkward in that it always returns the loss and for inference returns the predictions -> in other classes, we separate loss calculation and prediction from the pure forward pass
- getting Span labels out of BIOES tags is awkward (but then, it also is in SequenceTagger)
> Dual encoder less pad mask

- pyproject.toml
- requirements.txt
Simply moving from == to >= for `huggingface-hub`, since this is creating problems for me to install newer versions of `transformers` that require a minimum `huggingface-hub` version.
Some warnings appear for newer versions, so had to add some config to ignore warnings for `LayoutLMv3FeatureExtractor`, similarly as what was prev done for v2
> unpin huggingface-hub

- flair/data.py
Related to https://github.com/flairNLP/flair/pull/3142. This solution, by taking the difference between the first token start index and the sentence start index, keep the initial whitespace for some special cases while not printing a lot of useless whitespaces because we store the index of the token from a bigger document.
For example for the following text which is split in two Sentence objects in my application:
```python
text = "Amaury et Valentin mangent au 77 boulevard  Perreire.\n\n\n\n Paul  a modifié le tokenizer."
```
It gives before the fix:
```python
[Sentence[9]: "Amaury et Valentin mangent au 77 boulevard  Perreire.",
Sentence[6]: "                                                          Paul  a modifié le tokenizer."]
```
And after the fix:
```python
[Sentence[9]: "Amaury …
```
> Modify Sentence.to_original_text() to take into account Sentence.start_position for whitespace calculation

- flair/embeddings/transformer.py
This PR makes slight modifications to the behavior of context dropout in context expansion in TransformerEmbeddings: 
- the` [FLERT]` token is now always added, even when context is dropped
- context dropout is applied to left and right context independently
- more comments in the code
> GH-3166: add comments and one-sided dropout

- flair/trainers/trainer.py
- requirements.txt
- resources/docs/TUTORIAL_PRODUCTION_FASTER_TRANSFORMERS.md
- resources/docs/TUTORIAL_TRAINING_MORE.md
this PR fixes the usage of the transformer smaller training vocab and improves documentation:
* fix that transformer smaller training vocab are actually used for training and not just temporarily reduce the vocab size before the training starts.
* enforce using a newer version of the library. There are 2 changes:
* embedding-parameters that are not trainable, but present in the optimizer, will now be rightfully kept not trainable. Hence, running `embeddings.model.embeddings.word_embeddings.requires_grad_(False)` before training will work with `reduce=True`.
* The config rightfully sets the vocab size and therefore reduced models can be saved and later loaded as such.
* the transformer smaller training vocab is now documented in the tutorials
* the onnx tutorial is now slightly improved to …
> Fix transformer smaller training vocab

- flair/training_utils.py
Probably not relevant in most use cases, but if the flair log is used with a format containing the file, line number, or function name, the resulting line of log_line refers to the `log_line` function itself. Instead, it should refer to the place in the code where `log_line` is called. This can be fixed using `stacklevel`.
The following code demonstrates the stacklevel behavior (stacklevel <= 1 is in the logging module and will be ignored, stacklevel=2 refers to the log_line function, stacklevel=3 refers to the correct caller).
```python
import logging
def log_line(stacklevel):
logging.info("Stacklevel=%d", stacklevel, stacklevel=stacklevel)
def actual_caller(stacklevel):
log_line(stacklevel)
if __name__ == "__main__":
logging.basicConfig(
format="%(levelname)-8s %(filename)s:%(lineno)d …
```
> Add stacklevel to log_line in order to display correct file and line number

- flair/data.py
This PR closes #3124 . Noise transition matrix hast to be in a format of a dict of lists, in which the keys reflect the target label values.
> GH-3124: Add class-dependent label noise generation

- flair/models/sequence_tagger_model.py
This PR adds a new model for detecting PropBank frame. The model is trained using the "FLERT" approach, so it is much stronger than the previous 'frame' model. We also added some training data from the universal proposition bank to improve multilingual frame detection. 
Use it like this: 
```python
model = Classifier.load('frame-large')
sentence = Sentence("Dirk returned to Berlin to return his hat.")
model.predict(sentence)
sentence_de = Sentence("Dirk trug einen Koffer und trug einen Hut.")
model.predict(sentence_de)
print(sentence_de) 
```
This should print: 
```console
Sentence[9]: "Dirk returned to Berlin to return his hat." → ["returned"/return.01, "return"/return.02]
Sentence[9]: "Dirk trug einen Koffer und trug einen Hut." → ["trug"/carry.01, "trug"/wear.01]
``` …
> Add new semantic frame detection model

- requirements.txt
I don't thing there is a reason why gdown is pinned to a specific version, however the version 4.4.0 imports `pkg_resources` which leads to a deprecation warning.
> unpin gdown dependency

- .github/ISSUE_TEMPLATE/bug_report.yaml
Hi,
for the current description of a bug report, only one line of text is currently possible:
This is very short, so this PR changes the input text to a text area.
> github: bug report description should be textarea

- flair/data.py
In previous flair versions (e.g. 0.10) get_span_from_bio would start a new span if the previous tag was a "S-" token of a different class than the current token, see:
https://github.com/flairNLP/flair/blob/v0.10/flair/data.py#L698
It happens that our production model semi-frequently produces these kinds of (invalid BIOES) prediction, and that the new span extraction performs worse on our data.
This adds back this special check for previous tag "S-", making span calculation more similar to what it was in 0.10, and remaining the same for all 100% valid BIOES tagging.
Also included are some minor code tweaks to the function to make it prettier.
> get_spans_from_bio: Start new span for previous S- if class also changed

- flair/data.py
- flair/models/__init__.py
- flair/models/word_tagger_model.py
- flair/nn/model.py
- tests/models/test_word_tagger.py
- tests/test_corpus_dictionary.py
- tests/test_datasets.py
This PR introduces the `TokenClassifier` class, a renamed and extended version of `WordTagger`. It directly inherits from  `DefaultClassifier` and should be used for all token-level prediction tasks that do not require an LSTM-CRF decoder (for such tasks, the `SequenceTagger` should be used).
The main idea is to offer a model that inherits from `DefaultClassifier` for each label type we predict, i.e.:
- `TokenClassifier` for predicting `Token` labels
- `TextPairClassifier` for predicting `TextPair` labels
- `RelationClassifier` for predicting `Relation` labels
- `SpanClassifier` for predicting `Span` labels (this class is currently called `EntityLinker` and should be renamed)
- `TextClassifier` for predicting `Sentence` labels (might need to be renamed to SentenceClassifier)
An advantage …
> TokenClassifier model

- flair/trainers/trainer.py
This PR introduces a flag (`attach_default_scheduler`) in the methods `fine_tune` and `train` of the trainer in order to allow the user to
1. use no scheduler when training or finetuning, and
2. use a custom scheduler plugin (at the moment, a passed scheduling plugin would be added on top of the default scheduler),
while still using the other defaults of these functions.
> Allow users to use no scheduler and use a custom scheduling plugin

- flair/models/__init__.py
- flair/models/pairwise_regression_model.py
The STS-B task (added in #3201) of the glue benchmark requires a regression model which operates on sentence pairs. The added model can be used to solve this task, e.g. using following training script (this should result in a spearman correlation of ~0.8730):
```python
import sys
from pathlib import Path
import flair
from flair.datasets import GLUE_STSB
from flair.embeddings import TransformerDocumentEmbeddings
from flair.models import TextPairRegressor
def train(device, seed=0):
flair.device = device
flair.set_seed(seed)
corpus = GLUE_STSB()
label_type: str = "similarity"
embeddings = TransformerDocumentEmbeddings("bert-base-uncased", layers="-1", fine_tune=True)
model = TextPairRegressor(embeddings=embeddings, label_type=label_type)
trainer = …
```
> Add TextPair regression model

- flair/embeddings/transformer.py
This MR fixes the loading of models like Zelda,
in general, this affects all models with transformer-embeddings that were created before https://github.com/flairNLP/flair/pull/3178 was merged, but after https://github.com/flairNLP/flair/pull/3011
> Fix loading of (not so) old models

- flair/embeddings/token.py
closes https://github.com/flairNLP/flair/issues/3216 
moves the "add default values for older embeddings" logic to the __setstate__ method and ensures, that the old WordEmbeddings will store the torch weights correctly on resave.
> Fix loading of old models

- flair/embeddings/token.py
Closes https://github.com/flairNLP/flair/issues/3291
> prevent fasttext embeddings to be stored separately

- flair/embeddings/document.py
- flair/embeddings/token.py
- flair/embeddings/transformer.py
- flair/models/sequence_tagger_model.py
- flair/models/sequence_tagger_utils/viterbi.py
- flair/trainers/language_model_trainer.py
- flair/trainers/plugins/functional/linear_scheduler.py
- flair/trainers/trainer.py
- resources/docs/TUTORIAL_TRAINING_MORE.md
[nvidia-apex amp](https://github.com/NVIDIA/apex) is deprecated for some time now, as pytorch has [torch.cuda.amp](https://pytorch.org/docs/stable/amp.html) since pytorch 1.6.
This PR upgrades the usage to the newer version, hence setting `use_amp=True` on `trainer.train` or `trainer.finetune` will work out of the box. 
Also `use_amp` will be used in all tests that train a model, hence the tests should be faster (waiting for the pipeline to finish, to evaluate it)
I did 2 training runs:
Transformer (distilbert) using use_amp reduces the time from 440 s/epoch to 217 s/epoch.
Flair-embeddings + wordembeddings (without a BiLstm layer) using use_amp reduces the time for the first epoch (no embedding storage) from 221 s/epoch to 70s/epoch.
This PR also fixes recreation of the types to be …
> use torch native amp

- flair/data.py
- flair/models/relation_classifier_model.py
Closes https://github.com/flairNLP/flair/issues/3265
partial revert of https://github.com/flairNLP/flair/commit/decd3a656c2bb0a668883ab48355723687de393d
This cleans up the `to_dict()` iterface, giving options to get all labels, entities and relations of a sentence
> recreate `to_dict` and add relations

- flair/trainers/trainer.py
`ModelTrainer` should only save `final-model.pt` if the respective flag is True (regardless of the reason the training ended (see #3250).
> GH-3250: Save final model only if `save_final_model` is True (even if the training is interrupted)

- flair/datasets/sequence_labeling.py
- tests/test_datasets.py
Hi,
recently, proper dataset splits for the German LER Dataset were introduced:
https://github.com/elenanereiss/Legal-Entity-Recognition/commit/eda16d35f2c174845c83005e35d23bab10cd7dad
I updated the `NER_GERMAN_LEGAL` dataset, so these newly introduced splits are used.
A basic unit test was also added that checks if number of instances for all dataset splits are identical with reported numbers (see e.g. [here](https://huggingface.co/datasets/elenanereiss/german-ler#data-splits)).
> Extend German LER Dataset

- flair/trainers/trainer.py
A small fix to enable setting devices by string identifiers (`flair.device = 'cuda:1'`) again.
> Add a convenience conversion for flair.device

- flair/nn/model.py
fixes https://github.com/flairNLP/flair/issues/3367
> fix has unknown label is not always initialized

- flair/nn/model.py
- flair/nn/multitask.py
If the test dataset has no labels, and the model makes no predictions, no evaluation numbers (precision/recall/F1) can be computed. This causes errors in cases such as this: 
```python
import flair
from flair.data import Corpus
from flair.datasets import ColumnCorpus, WNUT_17
from flair.embeddings import TransformerWordEmbeddings
from flair.models import SpanClassifier
flair.set_seed(123)
corpus: Corpus = WNUT_17().downsample(0.01)
label_dictionary = corpus.make_label_dictionary("ner", add_unk=True)
embeddings = TransformerWordEmbeddings(
model="distilbert-base-uncased", layers="-1", subtoken_pooling="first", fine_tune=True, use_context=True
)
tagger = SpanClassifier(embeddings=embeddings, label_dictionary=label_dictionary)
trainer = …
```
> Fix classification report if dataset has no labels

- flair/models/multitask_model.py
- flair/models/pairwise_classification_model.py
- flair/models/pairwise_regression_model.py
- flair/models/relation_classifier_model.py
- flair/models/tars_model.py
- flair/models/text_regression_model.py
- flair/nn/model.py
- flair/trainers/plugins/functional/reduce_transformer_vocab.py
closes https://github.com/flairNLP/flair/issues/3368
> fix flert hidden context breaks reduced vocab

- flair/datasets/__init__.py
- flair/datasets/document_classification.py
This PR extends ```ClassificationCorpus``` to add support for the AGNews dataset (https://github.com/mhjabreel/CharCnn_Keras/tree/555590db4219b1243abb1918effd6a7425a2d75f/data/ag_news_csv).
```
from flair.datasets import AGNEWS
corpus = AGNEWS()
print(corpus)
```
> Add AGNews corpus

- flair/splitter.py
- tests/test_tokenize_sentence.py
This PR fixes the missing linkage of sentences (see issue #3396), i.e., setting the previous and next sentence in the sentence objects, when calling the split method of a sentence splitter.
> Fix linking of sentences in sentence splitter

- flair/tokenization.py
- requirements-dev.txt
This PR updates the version constraint for konoha.
I'm so sorry that I didn't notice the issue https://github.com/flairNLP/flair/issues/3059.
I updated konoha that removed the dependency for `importlib-metadata`, let me update `requirements-dev.txt`.
Now konoha only depends on `requests` with the support for Python3.8+ (https://github.com/himkt/konoha/blob/v5.5.2/pyproject.toml#L27).
So I think it can be safely used with flair and I update the requirements file.
And I have one question for dependency of `janome`. `janome` is only used in `JapaneseTokenizer`, which depends on `konoha`, therefore `janome` should be installed in the same place of `konoha`, I think. There are multiple options:
- (1) move `janome` to `requirements-dev.txt`
- (2) remove `janome` from `requirements.txt` and …
> deps: relax version constraint for konoha

- flair/data.py
- tests/test_tokenize_sentence.py
closes https://github.com/flairNLP/flair/issues/3403
> ignore separator symbols

- requirements-dev.txt
- requirements.txt
Make `janome` optional and install with `konoha` (for `JapaneseTokenizer`).
Based on the discussion https://github.com/flairNLP/flair/pull/3394#issuecomment-1935771503.
> deps: make janome optional

- flair/models/pairwise_regression_model.py
It seems like `batch` should be used in iterations, rather than `pairs`.
I'm not 100% sure about this fix, please feel free to close it if I'm wrong.
> Bugfix in pairwise_regression_model.py

- flair/__init__.py
This PR updates the init to check if `FLAIR_DEVICE="cpu"` and will use the cpu even on a system with cuda available. Currently its not possible to use flair on your cpu if you have a gpu which may be undesirable when managing memory
> feat: allow cpu device even if gpu available

- setup.py
When installing the latest version of flair through PyPI, I noticed that a `tests/` package could be found in my site-packages directory, and traced it back to flair.
In `setup.py`, the exclusion list expects a _list_ of exclusions, not a single excluded path `str`. The end result is that before this PR, the exclusion list seems to be interpreted as an exclusion of `"t", "e", "s"` instead of `"tests"`...
~~Now, for a reason that is beyond my understanding of Python packaging, with that fixed it would _still_ list `tests` under the site package's `top_level.txt`, and `from tests import embedding_test_utils` would locally fail with an "unknown location" error rather than a "module not found" error.  
Not sure if this was some caching issue, but it was annoying nonetheless, thus:  
I figured …
> Fix `tests` package being incorrectly included in builds

- docs/tutorial/index.rst
- docs/tutorial/tutorial-basics/entity-mention-linking.md
- docs/tutorial/tutorial-hunflair2/customize-linking.md
- docs/tutorial/tutorial-hunflair2/index.rst
- docs/tutorial/tutorial-hunflair2/linking.md
- docs/tutorial/tutorial-hunflair2/overview.md
- docs/tutorial/tutorial-hunflair2/tagging.md
- docs/tutorial/tutorial-hunflair2/training-ner-models.md
- flair/models/entity_mention_linking.py
- flair/training_utils.py
- pyproject.toml
- requirements-dev.txt
- resources/docs/HUNFLAIR2.md
- tests/embeddings/test_transformer_word_embeddings.py
This PR adds the new hunflair2 tutorials to our docpage and switches from code that downloads ab3p from bioner to `pyab3p` that not released yet but will follow.
This PR is in draft until `pyab3p` is released on pypi. For testing, you can already use the version from the testing-pypi via `pip install --index-url https://test.pypi.org/simple/ pyab3p`
`pyab3p` got released, hence you can now install it with `pip install pyab3p`
> Incorporate hunflair2 docs to docpage

- requirements.txt
Hi,
due to a recent bugfix release of `bpemb` (see https://github.com/bheinzerling/bpemb/issues/66 ), we should use this version as minimum required one!
In versions < 0.3.5 the download of embeddings is no longer working.
Related to #3467.
> pip: bump min. version of bpemb

- flair/nn/distance/euclidean.py
#3484 
Optimizes the euclidean distance method.
> GH-3484: Refactor euclidean distance calculation

- flair/data.py
- flair/models/lemmatizer_model.py
- flair/models/pairwise_classification_model.py
- flair/models/pairwise_regression_model.py
https://github.com/flairNLP/flair/issues/3487
This addresses the above memory leak by saving a reference to the `TextPair` when the concatenated `Sentence` is created. Its embeddings are explicitly cleared when `clear_embeddings` is called.
This also adds type hints to files relevant to this change.
> Fix GPU memory leak in TextPairRegressor

- docs/tutorial/tutorial-embeddings/transformer-embeddings.md
Fixed typo in ~/docs/tutorial/tutorial-embeddings/transformer-embeddings.md
> Update: Fixed typo transformer-embeddings.md

- docs/tutorial/tutorial-training/how-model-training-works.md
Fixed typo in ~/docs/tutorial/tutorial-training/how-model-training-works.md
> Update: Fixed typo in how-model-training-works.md

- flair/file_utils.py
- flair/nn/model.py
- flair/trainers/trainer.py
- tests/test_datasets.py
> Move error message to main load function

- flair/models/sequence_tagger_model.py
Flair's upcoming v0.14.0 release will remove the gensim dependency from the core package (it can still be additionally installed for gensim-specific features).
This PR updates the following packaged models for compatibility with this release: 
- ar-ner
- ar-pos
- nl-ner-rnn
- negation-speculation
- hunflair-gene
- hunflair-cellline
- hunflair-chemical
- hunflair-disease
- hunflair-species
It also removes support for the "hunflair-paper*" models since all users are advised to use the hunflair2 model from now on.  And it removes the "keyphrase" model since it uses an old serialized version of BERT.
> Update models for v0.14.0

- README.md
- docs/conf.py
- docs/tutorial/tutorial-basics/entity-mention-linking.md
- docs/tutorial/tutorial-basics/other-models.md
- docs/tutorial/tutorial-basics/part-of-speech-tagging.md
- docs/tutorial/tutorial-basics/tagging-entities.md
- docs/tutorial/tutorial-basics/tagging-sentiment.md
- flair/__init__.py
- flair/datasets/treebanks.py
- flair/models/language_model.py
- flair/models/multitask_model.py
- flair/models/prefixed_tagger.py
- flair/models/sequence_tagger_model.py
- flair/models/sequence_tagger_utils/viterbi.py
- flair/trainers/trainer.py
- pyproject.toml
- setup.py
Time for another release! This PR bumps the version numbers, updates the documentation and fixes some mypy issues.
> Bump version numbers for Flair release 0.14.0

- flair/embeddings/transformer.py
- requirements.txt
Use version parsing from `packaging` to support all valid python version identifiers instead of the external `semver` library.
> Use built-in version parsing from packaging

- pyproject.toml
- tests/test_datasets.py
Current builds are failing due to a new FutureWarning regarding the default behavior of tokenizer.cleanup_tokenization_spaces (see https://github.com/huggingface/transformers/issues/31884). 
This PR simply ignores these warnings since our code is unaffected by it.
> Ignore FutureWarning

- flair/datasets/sequence_labeling.py
This PR adds `use_tokenizer` argument to the `SequenceTagger` JSONL datasets. This allows use of non-default tokenization with taggers trained using JSONL datasets.
Closes https://github.com/flairNLP/flair/issues/3476
> Add use_tokenizer to JsonlDataset

- flair/models/entity_mention_linking.py
- flair/models/pairwise_regression_model.py
- flair/models/relation_classifier_model.py
- flair/models/text_regression_model.py
- flair/nn/model.py
- flair/trainers/trainer.py
- flair/training_utils.py
Addresses https://github.com/flairNLP/flair/issues/3509
Also adds more type hinting and fixes mutable default arguments.
> GH-3509: fix support metric

- flair/models/pairwise_regression_model.py
The `TextPairRegressor` model uses the wrong default evaluation metric for a regression. This changes it from micro avg f1 score to pearson correlation coefficient
> fix: use proper eval default main eval metrics for text pair regressor

- flair/file_utils.py
request.head  also require use url_proxies variable
I have been working using this library with a proxy configuration, and I found that this change is necessary to achieve the download of the files
> Add proxies information to requests.head

- flair/embeddings/transformer.py
Closes https://github.com/flairNLP/flair/issues/3543
The T5 tokenizer fast is required to load from the slow tokenizer when `add_prefix_space` is True. See [the code](https://github.com/huggingface/transformers/blob/673440d073d5f534a6d6bedeeca94869afd8d0a7/src/transformers/models/t5/tokenization_t5_fast.py#L113)
I am not sure why exactly this is implemented that way, as the traces do not show a specific reasoning, but with a small exception on our side, we can easily support all T5 tokenizers.
> fix T5 tokenizer loading

- SECURITY.md
This PR removes the old Zalando address for reporting vulnerabilities. 
A second PR will add a list (currently being created) where vulnerabilities can be reported. 
Closes #3561
> GH-3561: Update SECURITY.md with current contact

- flair/data.py
- flair/models/lemmatizer_model.py
- flair/nn/model.py
- tests/test_corpus_dictionary.py
perf: optimize dictionary items by providing function to check for presence of label in constant time, rather than requiring the creation of a list to be checked. update slow uses of get_items() to use this new function.
> perf: optimize dictionary items check

- flair/models/sequence_tagger_model.py
- tests/models/test_sequence_tagger.py
This PR fixes the issue #3448 . Previously, due to incorrect length calculation for each sentence in the batch, the returned tag probability distribution for each token was incorrect (from the _all_scores_for_token() function in sequence_tagger_model.py). This PR makes a small change in _all_scores_for_token() function to correctly compute the length.
> Fixes the incorrect token prediction distribution from _all_scores_for_token() in sequence_tagger_model.py

- docs/conf.py
- docs/tutorial/tutorial-basics/basic-types.md
- docs/tutorial/tutorial-basics/entity-linking.md
- docs/tutorial/tutorial-basics/entity-mention-linking.md
- docs/tutorial/tutorial-basics/how-predictions-work.md
- docs/tutorial/tutorial-basics/how-to-tag-corpus.md
- docs/tutorial/tutorial-basics/other-models.md
- docs/tutorial/tutorial-basics/part-of-speech-tagging.md
- docs/tutorial/tutorial-basics/tagging-entities.md
- docs/tutorial/tutorial-basics/tagging-sentiment.md
- flair/data.py
- flair/nn/model.py
- flair/splitter.py
- flair/trainers/plugins/base.py
- flair/trainers/trainer.py
Adds docstrings to the `get_label` method and tests whether the "Returns:" description in the docstrings is correctly displayed.
> Test new docstrings and apidocs deployment

- flair/trainers/plugins/functional/checkpoints.py
- flair/trainers/trainer.py
Hi! This PR fixes 3 bugs with multi-gpu training:
- When using gradient accumulation (mini_batch_chunk_size), this PR disables gradient syncing for allforward/backward passes except the last one before the step. These intermediate syncs are unnecessary and add communication that decreases efficiency. In my experience, this effect was significant enough to go from multi_gpu not giving any speedup, to a 80%-of-linear speedup (mini_batch_chunk_size ~= 4, sentence_length ~= 500, model=xlm-roberta-base, gpu_memory ~= 24g). This is similar to what's done [here](https://discuss.pytorch.org/t/gradient-accumulation-with-ddp-no-sync-interface/169593).
- Sums rather than averages gradients from multiple processes. Flair tracks losses / grads as the sum of the whole batch. However, Torch DDP averages …
> Multigpu: Fix gradient accumulation and learning rate aggregation

- flair/models/relation_classifier_model.py
The `RelationClassifier `works by internally creating a sentence representation for each possible entity pair in a sentence. The number of such sentence representations can be quite large if there are several entities in a sentence.  Most of these are not involved in any relation.
This PR removes unlabeled entity pairs from the evaluation printout to remove clutter.
> Modify printouts in RelationClassifier evaluation to remove clutter

- flair/tokenization.py
This PR adds an option to pass additional characters to `SegtokTokenizer `that always must be split. 
For instance, instantiate with `tokenizer = SegtokTokenizer(additional_split_symbols=['§"])` to ensure that paragraph symbols are always split into their own token.
> Add option to customize SegtokTokenizer

- flair/datasets/sequence_labeling.py
- tests/resources/tasks/trivial/trivial_bioes_with_boundaries/dev.txt
- tests/resources/tasks/trivial/trivial_bioes_with_boundaries/test.txt
- tests/resources/tasks/trivial/trivial_bioes_with_boundaries/train.txt
- tests/test_datasets.py
This PR adds two new parameters to `ColumnCorpus `and `ColumnDataset `to enable more customization in handling document boundaries. 
`documents_as_sentences`: If set to `True` and a `document_separator_token `is also set, the corpus will create one sentence object not for each sentence, but for each document in the corpus. 
`every_sentence_is_independent`: If set to `True`, the corpus will consider each sentence independent. This means that loaded sentences cannot expand their context beyond the sentence boundary. This is useful for corpora that store independent sentences, like tweets.
> Add options to load full documents as Sentence objects

- docs/conf.py
- flair/data.py
- flair/datasets/document_classification.py
- flair/distributed_utils.py
- flair/models/regexp_tagger.py
- flair/models/sequence_tagger_model.py
- flair/nn/model.py
- flair/splitter.py
- flair/trainers/plugins/functional/checkpoints.py
- tests/models/test_regexp_tagger.py
Currently, the RegexpTagger only matches the full given regular expression in a sentence. Sometimes, you may want to match only a part of the given expression instead. 
This PR extends the RegexpTagger such that you can optionally specify a matching group, i.e.: 
```python
from flair.models import RegexpTagger
tagger = RegexpTagger(
mapping=[
(r'["„»]((?:(?=(\\?))\2.)*?)[”"“«]', "quote"),
(r'["„»]((?:(?=(\\?))\2.)*?)[”"“«]', "quote_part", 1),
]
)
sentence = Sentence('He said: "this is interesting"')
print(sentence.get_spans("quote_part"))
print(sentence.get_spans("quote"))
```
> Add option to define matching groups to RegexpTagger

- flair/models/pairwise_regression_model.py
- flair/models/text_regression_model.py
This fixes the default metrics used in the text regression model to be more appropriate for regression, rather than the classification default. There are "correlation" and "pearson" metrics.
This is mostly a copy of https://github.com/flairNLP/flair/pull/3538 but for the `TextRegressor` model
> fix: use proper eval default main eval metrics for text regression model

- flair/nn/model.py
This fixes a bug where `index_select` is expecting an int type:
`scores = torch.index_select(scores, 0, torch.tensor(filtered_indices, device=flair.device))`
`RuntimeError: index_select(): Expected dtype int32 or int64 for index`
> fix: cast indices tensor to int to fix bug

- flair/embeddings/document.py
scipy has removed support for the .A method in sparse arrays (https://github.com/scipy/scipy/issues/21049). Replaced this with .toarray().
> fix: update scipy .A to toarray()

- flair/embeddings/document.py
- flair/embeddings/token.py
- flair/file_utils.py
- flair/models/sequence_tagger_model.py
- requirements.txt
fixes https://github.com/flairNLP/flair/issues/3607
> add compatibility to torch 2.6

- flair/datasets/biomedical.py
The newest mypy error noted a problem in one of the deprecated datasets (`ANAT_EM`) that are now provided through BigBio.
This PR removes the old implementation, adds the option of trusting remote code to BIGBIO_NER_CORPUS, and updates the deprecation method with the exact command to load this dataset. 
So, instead of calling 
```python
corpus = ANAT_EM() 
```
you should instantiate this corpus like this: 
```python
corpus = BIGBIO_NER_CORPUS("bigbio/anat_em", trust_remote_code=True)
```
> Remove deprecated dataset implementation due to mypy error

- flair/models/entity_mention_linking.py
- flair/models/multitask_model.py
- flair/models/prefixed_tagger.py
- flair/models/relation_extractor_model.py
- flair/models/sequence_tagger_model.py
- flair/models/tars_model.py
- flair/models/text_classification_model.py
- flair/nn/model.py
Some minor changes that were made in the course of fixing #3634, affecting the fetch_model method and the naming of its parameter, as well as its docstring.
> Rename fetch_model parameter and add better code comments

- flair/training_utils.py
> GH-3603: Refactor Result class to make scores argument non-optional

- flair/data.py
- flair/datasets/base.py
- flair/datasets/document_classification.py
- flair/datasets/text_text.py
- flair/embeddings/transformer.py
- flair/models/relation_classifier_model.py
- flair/nn/model.py
- tests/test_tokenize_sentence.py
Closes #3635
Flair previously always tokenized sentences. However, for some tasks, such as text classification using transformers, tokenization is not necessary, causing memory overheads and speed bottlenecks. 
This PR implements lazy tokenization for Flair sentences to improve efficiency, particularly for long texts. Sentences are now only tokenized when necessary, rather than immediately upon creation. 
Key Changes:
- Added `_is_tokenized()` method to check tokenization state
- Modified transformer embeddings to preserve lazy tokenization state
- Added tests to verify tokenization behavior
- Improved code clarity around tokenization states
- Adds a new `.truncate()` method to `Sentence` that allows an existing sentence to be shortened to a maximum number of tokens.
Example to illustrate …
> Lazy Tokenization in Flair

- flair/data.py
- flair/datasets/sequence_labeling.py
- flair/tokenization.py
- tests/test_labels.py
- tests/test_tokenize_sentence.py
This PR adds a new tokenizer following the ideas outlined in #3631. 
The tokenizer works like any other, but is intended to give a reasonable, if somewhat trigger-happy tokenization of any language. Some illustration of how this works for different languages: 
```python
print("Testing English with numbers and punctuation:")
sentence = Sentence("It's 03-16-2025", use_tokenizer=StaccatoTokenizer())
desired_tokenization = ["It", "'", "s", "03", "-", "16", "-", "2025"]
for token, desired_token in zip(sentence, desired_tokenization):
print(f"Got: '{token.text}', Expected: '{desired_token}'")
assert token.text == desired_token
print("✓ English test passed")
print("\nTesting Cyrillic (Russian):")
russian_sentence = Sentence("Привет, мир! Это тест 123.", use_tokenizer=StaccatoTokenizer()) …
```
> Add Staccato tokenizer and retokenize method

- flair/models/sequence_tagger_model.py
- flair/nn/model.py
This PR adds the ability to set and retrieve license information for Flair models. License information is stored in the model card and is automatically displayed when loading a model.
- Added `license_info` property to Model class with getter and setter methods
- License information is stored in the model's model_card
- Added automatic display of license information when loading models
- Improved model loading messages to show model type and predicted tags
- Added unit test for license functionality
```python
model = Model.load('ner')
model.license_info = "MIT License - Copyright (c) 2024"
model.save('model.pt')
loaded_model = Model.load('model.pt')
```
Added test case that verifies:
- Setting and getting license information
- License persistence through save/load cycles
- Default …
> GH-3633: add option to add license information to Flair models

- flair/embeddings/transformer.py
There is a bug that can arise from the assumption of `float32` when casting mask tensors to float when calling `scatter_add`, causing the error
`RuntimeError: scatter(): Expected self.dtype to be equal to src.dtype`
This fix casts them to the float type according to the caller of the function.
> fix: cast src to the correct type in scatter_add call

- flair/tokenization.py
- tests/test_tokenize_sentence.py
This pull request addresses issues in the `StaccatoTokenizer` related to the handling of certain non-printing Unicode characters, specifically zero-width characters like variation selectors (e.g., U+FE0F) and the Byte Order Mark (BOM, U+FEFF).
**Problem:**
The previous implementation could incorrectly split tokens or generate spurious empty/single-character tokens when encountering:
1.  Zero-width variation selectors often used with emojis (e.g., `❤` + `️` U+FE0F).
2.  The Byte Order Mark (U+FEFF), which is sometimes present at the beginning of files or incorrectly used as a zero-width space within text.
This resulted in unexpected tokenization outputs like `['norm', '❤', '️', 'enjoyed']` instead of `['norm', '❤', 'enjoyed']` or adding an empty token at the end of a sentence if it …
> Fix StaccatoTokenizer Handling of Zero-Width Characters and BOM

- flair/data.py
- flair/datasets/sequence_labeling.py
- tests/test_datasets.py
- tests/test_tokenize_sentence.py
Closes #3654  
This PR adds an option to retokenize any `ColumnCorpus` with a new tokenizer. In order to do this, you need to pass `use_tokenizer` when creating the corpus. 
Example: 
```python
corpus = CLEANCONLL(use_tokenizer=StaccatoTokenizer())
```
The PR also fixes some issues in the retokenize method of the Sentence object, in particular adding support for Relation labels.
> Add option to retokenize ColumnCorpus

- flair/data.py
- flair/training_utils.py
- tests/test_training_utils.py
Closes #3614
This PR fixes an issue where `identify_dynamic_embeddings` did not correctly detect dynamic embeddings (those with `requires_grad=True`) within composite `DataPoint` types like `DataPair` or `Sentence` with token embeddings.
The logic has been refactored by:
1.  Adding internal helper methods (`_get_dynamic_embedding_names` and `_get_all_embedding_names`) to the `DataPoint` base class with default implementations.
2.  Overriding these methods in composite classes (`Sentence`, `Span`, `DataPair`, `DataTriple`) to recursively check their constituent parts.
3.  Simplifying the `identify_dynamic_embeddings` function in `training_utils.py` to use these helpers.
This ensures all relevant dynamic embeddings are correctly identified across different `DataPoint` structures. Unit tests …
> GH-3614: Fix `identify_dynamic_embeddings` for composite DataPoints

- flair/data.py
- tests/test_sentence_serialization.py
This pull request introduces a comprehensive solution for serializing and deep-copying Flair's Sentence objects, addressing a long-standing issue where standard methods like copy.deepcopy() and pickle would fail.
Closes #3245 
This PR implements two key mechanisms to solve this problem:
1.  **JSON Serialization (`to_dict` / `from_dict`):**
-   A new `sentence.to_dict()` method serializes the entire `Sentence` object—including its text, tokenizer, and all annotations (spans, relations, and labels at all levels)—into a clean, JSON-compatible dictionary.
-   A corresponding class method, `Sentence.from_dict()`, fully reconstructs the `Sentence` object from this dictionary, correctly restoring all annotations and the original tokenizer.
-   The core logic is encapsulated in two powerful …
> Add JSON-based serialization logic and deepcopy implementation for Sentence object
