flairNLP/flair

flair/data.py
flair/embeddings.py
flair/file_utils.py
resources/docs/TUTORIAL_BASICS.md
resources/docs/TUTORIAL_TAGGING.md
resources/docs/TUTORIAL_TRAINING_A_MODEL.md
resources/docs/TUTORIAL_WORD_EMBEDDING.md

GH-8: fix typos, added method docs

---

README.md
flair/data.py
flair/embeddings.py
resources/docs/CONTRIBUTING.md
resources/docs/EXPERIMENTS.md
resources/docs/TUTORIAL_BASICS.md
resources/docs/TUTORIAL_TEXT_EMBEDDINGS.md
resources/docs/TUTORIAL_TRAINING_A_MODEL.md
resources/docs/TUTORIAL_WORD_EMBEDDING.md

GH-8: Documentation

---

flair/models/sequence_tagger_model.py
setup.py
tests/test_sequence_tagger.py

fixed retagging error #23 
added test case for this bug
incremented version for bugfix release

GH-23: retagging error

---

flair/data_fetcher.py
flair/embeddings.py
flair/trainers/language_model_trainer.py
resources/docs/TUTORIAL_TRAINING_A_MODEL.md

Hi,
some documentation fixes are included in this PR :)

Minor (documentation) fixes

---

.travis.yml
tests/test_embeddings.py

GH-56: Travis CI

---

.travis.yml
build.sh
tests/test_sequence_tagger.py

GH-56: Travis CI - Build successful

---

.travis.yml

GH-56: Build master on push.

---

flair/embeddings.py
flair/models/text_classification_model.py
tests/test_text_classifier_trainer.py

GH-109: Fix single label training

---

requirements.txt

GH-106: Update torch version to 0.4.1

---

flair/data.py
flair/data_fetcher.py
flair/trainers/sequence_tagger_trainer.py
flair/training_utils.py
requirements.txt
setup.py
tests/test_data.py
tests/test_utils.py

Adds methods to retrieve BIO/BIOES annotated spans from sentences and evaluate using F1 score. 
Specifically: 
- An initial simple Span class in data.py that holds a Token span. This class may be expanded in future commits.
- A method in Sentence to extract spans of a tag type, such as NER spans.
- Test methods to check if span extraction handles BIO/BIOES and other formats and irregularities (#97)
- Change of evaluation method in SequenceTaggerTrainer to use our own evaluation routine instead of perl script (#79 )
- A new ItemWeigher helper class to count weighted strings

GH 75 spans

---

flair/models/sequence_tagger_model.py
flair/nn.py

- added word dropout 
- moved dropouts into new flair.nn module
closes #48

GH-48: added word dropout | moved dropouts into new flair.nn module

---

setup.py

Add encoding variable to fix setup on Windows #114

GH-114: Update setup.py

---

flair/data.py
flair/models/text_classification_model.py
flair/trainers/text_classification_trainer.py
flair/training_utils.py
tests/test_data.py
tests/test_utils.py

GH-108: Refactoring of text classifier

---

flair/embeddings.py
flair/models/language_model.py
flair/trainers/text_classification_trainer.py

GH-108: Use torch.no_grad in evaluation method

---

flair/data.py
tests/test_data.py

GH-54: Add method to convert sentence to dict.

---

README.md
flair/__init__.py
flair/data.py
flair/embeddings.py
flair/trainers/language_model_trainer.py
flair/trainers/text_classification_trainer.py
flair/training_utils.py
flair/visual/training_curves.py
requirements.txt
resources/docs/EXPERIMENTS.md
resources/docs/TUTORIAL_TAGGING.md
resources/docs/TUTORIAL_TEXT_EMBEDDINGS.md
resources/docs/TUTORIAL_TRAINING_A_MODEL.md
resources/docs/TUTORIAL_WORD_EMBEDDING.md

Preparatoring changes and fixes for release 0.3

Gh 139 release 0.3

---

flair/models/text_classification_model.py

GH-149: Always clear embeddings in predict

---

flair/embeddings.py

GH-150: Update DocumentLSTMEmbeddings

---

flair/trainers/sequence_tagger_trainer.py
flair/trainers/text_classification_trainer.py

GH-148: Align TextClassificationTrainer and SquenceTaggerTrainer

---

flair/models/sequence_tagger_model.py
flair/models/text_classification_model.py
flair/training_utils.py

GH-152: Don't predict empty sentences

---

flair/embeddings.py
tests/test_model_integration.py

- added integration tests for training / loading / applying models
- minor serialization fixes in embeddings classes
- minor harmonization fixes in embeddings classes

GH-162: integration tests

---

flair/__init__.py
flair/models/sequence_tagger_model.py
flair/models/text_classification_model.py

Suppress torch warnings according to [warnings manual](https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings) to resolve the issue https://github.com/zalandoresearch/flair/issues/82

Correct suppression of torch warnings

---

flair/embeddings.py
requirements.txt
tests/test_embeddings.py

GH-192: Mark DocumentMeanEmbeddings as deprecated

---

flair/models/sequence_tagger_model.py
flair/models/text_classification_model.py
flair/trainers/language_model_trainer.py
flair/trainers/sequence_tagger_trainer.py

- Disable autograd in Sequence Tagger & Language Model
- Update logging in Sequence Tagger: Only log class metrics at the end of training instead of every epoch.
Performance improvements in Sequence Tagger: up to 10% faster for prediction
closes #175

GH-175: Disable autograd in Sequence Tagger & Language Model

---

.gitignore
README.md
flair/embeddings.py
resources/docs/TUTORIAL_WORD_EMBEDDING.md
resources/tasks/ud_english/en_ewt-ud-dev.conllu
resources/tasks/ud_english/en_ewt-ud-test.conllu
resources/tasks/ud_english/en_ewt-ud-train.conllu
tests/test_embeddings.py
train.py

- Add possibility to load custom embeddings
- Add example data to train the sequence tagger in `train.py`
closes #170

GH-170: Add possibility to load custom embeddings

---

flair/trainers/language_model_trainer.py

Test language model on test data after training or if training was interrupted.
closes #178

GH-178: Test language model as last step

---

flair/models/language_model.py

GH-167: Ad method to generate text to language model

---

flair/embeddings.py
resources/docs/TUTORIAL_WORD_EMBEDDING.md

Added option to download these models.

GH-203: add bulgarian and slovenian LM models

---

flair/models/language_model.py
tests/test_model_integration.py

GH-210: Add torch.no_grad to generate_text

---

flair/models/language_model.py
flair/trainers/language_model_trainer.py
tests/test_model_integration.py

GH-200: Remember best score of language model

---

flair/optim.py
flair/trainers/language_model_trainer.py
flair/trainers/trainer.py
resources/docs/TUTORIAL_TRAINING_A_MODEL.md
tests/test_model_integration.py

added AdamW and SGDW and corresponding schedular

---

flair/data_fetcher.py

addresses #243 
Since there is a lot of interest in the Flair community (#199 #248), added one more dataset to the downloader, namely the WNUT-17 shared task on emerging entity detection. 
Just load with: 
```python
corpus = NLPTaskDataFetcher.load_corpus(NLPTask.WNUT_17)
```
Dataset will get downloaded automatically.

GH-243: add WNUT-17 dataset to downloader

---

flair/hyperparameter/param_selection.py
flair/trainers/trainer.py
flair/training_utils.py

related to #242 
- Don't save models when selecting parameters
- Save results of parameter selection to `param_selection.txt` file

GH-242: Improve parameter selection.

---

flair/trainers/language_model_trainer.py

Hi,
this PR adjusts the learning rate output information during language model training (now four digits are displayed for learning rate in output).

GH-257: adjust learning rate output information 

---

flair/embeddings.py
flair/models/sequence_tagger_model.py
flair/trainers/trainer.py

addresses #249  
- Refactor CharLMEmbeddings caching mechanism to address bug #249 
- Relax some PathLib signatures to also take string

GH-249: refactor caching in CharLMEmbeddings

---

requirements.txt
setup.py

[WIP] add bert embeddings

---

flair/embeddings.py

Adds a new `ELMoEmbeddings` class which calls the allennlp ELMoEmbedder. This class can be used like any other embeddings class in the Flair framework, so: 
```python
from flair.embeddings import ELMoEmbeddings
elmo_embeddings = ELMoEmbeddings()
sentence = Sentence('I love Berlin.', use_tokenizer=True)
elmo_embeddings.embed(sentence)
for token in sentence:
print(token)
print(token.embedding)
```
We package several pre-trained ELMo models: The large model used in the ELMo paper is used by default. You can also instantiate smaller models with: 
```python
elmo_embeddings_small = ELMoEmbeddings('small')
elmo_embeddings_medium = ELMoEmbeddings('medium')
```
We also include the Portuguese model: 
```python
elmo_embeddings_portuguese = ELMoEmbeddings('portuguese')
```
HOWEVER, in order to use …

GH-260: elmo embeddings

---

flair/models/language_model.py
flair/models/sequence_tagger_model.py
flair/models/text_classification_model.py
flair/trainers/language_model_trainer.py
flair/trainers/trainer.py
tests/test_model_integration.py

closes #217 
To be able to resume training you need to train with `checkpoint` set to `True`. 
If `checkpoint=True` the model plus the training parameters (e.g. loss, epoch, optimizer state dict) are saved to disk after every epoch. 
To continue training, for example for a `SequenceTagger`, you need to execute:
```
trainer = ModelTrainer.load_from_checkpoint('checkpoint.pt', 'SequenceTagger', corpus)
trainer.train(out_path)
```

GH-217: Resume training

---

flair/hyperparameter/param_selection.py
flair/trainers/trainer.py

related to #242 
To overcome the issues of random noise in the training, we average the last three scores of the training. Additionally, you can run one parameter combination x times and take the average over the x runs as score.

GH-242: Take average over training runs as score

---

flair/data_fetcher.py

GH-266: Filter sentences with no tokens

---

flair/__init__.py
flair/hyperparameter/param_selection.py
flair/trainers/language_model_trainer.py
flair/trainers/trainer.py
flair/training_utils.py

GH-212: Write training log to file in experiment directory

---

flair/hyperparameter/param_selection.py
flair/models/sequence_tagger_model.py
flair/models/text_classification_model.py
flair/trainers/language_model_trainer.py

GH-70: Add pretrained model for germ-eval-2018 task-1

---

flair/embeddings.py

[WIP] initial BertWordEmbeddings helper

---

flair/hyperparameter/param_selection.py
flair/trainers/trainer.py
flair/training_utils.py

GH-242: Specify optimization value for parameter selection

---

requirements.txt
setup.py

0.3.0 adds new models and bug fixes

Update bert 

---

flair/trainers/trainer.py
flair/visual/training_curves.py

improve find_learning_rate API

---

flair/trainers/language_model_trainer.py
tests/test_language_model.py

GH-280: Fix language model training.

---

flair/embeddings.py
flair/hyperparameter/param_selection.py
flair/trainers/trainer.py

Two small changes: 
- added back in pre-computed twitter embeddings (closes #291 )
- returns test score in hyperparameter optimization

GH-276: return test score and add twitter embeddings

---

requirements.txt
setup.py

GH-299: Update torch version to 1.0.0

---

flair/embeddings.py

related to #241 
Thanks to @stefan-it for providing the models!

GH-241: Add czech models.

---

flair/models/sequence_tagger_model.py

Thanks to @stefan-it for providing the model!
closes #224

GH-224: Add nl-ner model

---

flair/embeddings.py

related to #2 
Thanks to @ericlief for providing the models!

GH-2: Add protuguese models.

---

flair/embeddings.py

GH-251: Raise ValueError if BertModel does not exist.

---

.travis.yml

GH-310: Add env BOTO_CONFIG to travis.yml

---

flair/models/sequence_tagger_model.py
resources/docs/TUTORIAL_2_TAGGING.md
tests/test_model_integration.py

Thanks @stefan-it for providing the model!
closes #51

GH-51: Add fine-grained POS Tagger for German Tweets

---

flair/models/language_model.py
flair/models/sequence_tagger_model.py
flair/trainers/language_model_trainer.py
tests/test_language_model.py

closes #322 
This PR fixes the overflow problem and cleans up the LM code a bit. Also adds a unit test for the issue.

GH-322: generate text

---

resources/docs/TUTORIAL_6_CORPUS.md

```
columns = {0: 'text', 1: 'pos', 2: 'ner'}
```
```
print(corpus.train[0].to_tagged_string('ner'))
```
```
2019-01-02 15:05:41,178 Reading data from data
2019-01-02 15:05:41,178 Train: data/train.txt
2019-01-02 15:05:41,178 Dev: None
2019-01-02 15:05:41,178 Test: None
George <N> Washington <N> went <V> to <P> Washington <N>
George <B-PER> Washington <I-PER> went to Washington <B-LOC>
```

i think this line should match each other

---

flair/models/sequence_tagger_model.py

Changes in the predict() function:
- Faster inferencing by presorting sequences. Also, let's the user figure out the optimal batch size early on.
- Token embeddings are cleared after processing each batch, thereby saving a lot of RAM.
- Progress bar that can be toggled by setting the argument `verbose = True`, useful when processing a large number of sequences.

Gh 347 sequence tagging enhancement

---

tests/test_model_integration.py

closes #356 
Add another integration test over English UD data.

GH-356: integration test with English UD data

---

README.md

File was moved in https://github.com/zalandoresearch/flair/pull/354

Fix link to contributor guidelines

---

resources/docs/TUTORIAL_8_MODEL_OPTIMIZATION.md

GH-371: Update reference to AGNews corpus in documentation

---

README.md

If you like it, feel free to merge it :)

Added a visualisation of code evolution

---

flair/file_utils.py
flair/models/sequence_tagger_model.py
flair/models/text_classification_model.py

Closes #351 with the fix proposed by @highway11git  
Since we could not reproduce the error on our setups (only affects certain windows / mac setups) we could not yet verify from our side if this indeed fixes the error.

GH-351: deserialize

---

resources/docs/TUTORIAL_3_WORD_EMBEDDING.md

I didn't open an issue for this as this is just 2 quick typos I notices while reading the documentation tonight.
Let me know if I need to improve something.

Hotfix for 2 typos in tutorial 3

---

flair/data_fetcher.py

Hi,
this PR introduces a new dataset loader that downloads and preprocesses the Basque Named Entities Corpus (EIEC).
Here's a short example of how to use the new dataset loader:
```python
from typing import List
from flair.data import TaggedCorpus
from flair.data_fetcher import NLPTaskDataFetcher, NLPTask
from flair.embeddings import FlairEmbeddings, TokenEmbeddings, WordEmbeddings, StackedEmbeddings
NLPTaskDataFetcher.download_dataset(NLPTask.NER_BASQUE)
corpus: TaggedCorpus = NLPTaskDataFetcher.load_corpus(NLPTask.NER_BASQUE)
tag_type = 'ner'
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
print(corpus.obtain_statistics())
embedding_types: List[TokenEmbeddings] = [
WordEmbeddings('eu'),
FlairEmbeddings('eu-forward'),
FlairEmbeddings('eu-backward')
]
embeddings: …
```

GH-383: add Basque NER dataset loader

---

flair/training_utils.py
tests/test_utils.py

GH-417: Fix bug in macro avg f-score

---

flair/__init__.py
tests/test_embeddings.py
tests/test_visual.py

GH-415: Enable existing loggers.

---

requirements.txt
setup.py

Loosen version constraints of dependencies

---

flair/embeddings.py

closes #421 
When initializing `CharacterEmbeddings`, the object now automatically gets put on CUDA if available

Gh 421 character embeddings

---

flair/training_utils.py

add default class name parameter as same as in get_tp method

add default class_name parameter to metric getters

---

flair/data_fetcher.py

Hi,
this PR adds support for TREC-6 and TREC-50 datasets. Training and testdata is downloaded from the same source, as e.g. [PyTorch-NLP](https://pytorchnlp.readthedocs.io/en/latest/_modules/torchnlp/datasets/trec.html?highlight=trec-6) is using it.
Example usage:
```python
from typing import List
from flair.data import TaggedCorpus
from flair.data_fetcher import NLPTaskDataFetcher, NLPTask
from flair.embeddings import DocumentLSTMEmbeddings, WordEmbeddings, FlairEmbeddings
from flair.models import TextClassifier
from flair.training_utils import EvaluationMetric
NLPTaskDataFetcher.download_dataset(NLPTask.TREC_6)
corpus: TaggedCorpus = NLPTaskDataFetcher.load_corpus(NLPTask.TREC_6)
label_dict = corpus.make_label_dictionary() …
```

GH-449: add support for trec-6 and trec-50 datasets

---

README.md

Fixed some typos and removed some broken links in README.md

Fixed typos and removed broken links in README.md

---

flair/trainers/trainer.py

Sometimes it would be good to see confidence score for each token.

Output confidence score in test.tsv

---

flair/trainers/trainer.py

Similar to sequence tagger, output evaluation results to file for text classification.

Output evaluation results to file for text classification.

---

flair/trainers/language_model_trainer.py
tests/test_model_integration.py

Small optimizations for memory management when training a language model.

GH-406: LM memory tweaks

---

flair/data_fetcher.py
flair/file_utils.py
flair/trainers/language_model_trainer.py
tests/resources/tasks/multi_class/dev.txt
tests/resources/tasks/multi_class/test.txt
tests/resources/tasks/multi_class/train.txt
tests/test_model_integration.py

added a data set and a simple prediction problem for integration testing of multi label classification

GH-483: added unit test for multi label classification

---

.travis.yml
flair/embeddings.py
flair/hyperparameter/param_selection.py
flair/training_utils.py
requirements.txt
setup.py
tests/test_embeddings.py
tests/test_hyperparameter.py
tests/test_model_integration.py
tests/test_text_classifier.py
tests/test_utils.py
tests/test_visual.py

GH-486: Macro f-score computation

---

flair/embeddings.py

Add custom Bert model support

---

flair/embeddings.py

closes #527 
Thank you @frtacoa and @minh-agent for contributing these models!

GH-527: added Japanese FlairEmbeddings

---

resources/docs/TUTORIAL_3_WORD_EMBEDDING.md
resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md
resources/docs/TUTORIAL_5_DOCUMENT_EMBEDDINGS.md
resources/docs/TUTORIAL_6_CORPUS.md
resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md

Update documentation with new classes, models and datasets of 0.4.1.

GM-481: documentation release 0.4.1

---

flair/embeddings.py

Hi,
this PR adds a new embedding class for *Transformer-XL* model.

GH-522: Transformer-XL embeddings

---

flair/models/language_model.py

Hi,
this PR fixes the lm perplexity calculation for a sentence when running the code on GPU.
Closes #534 .

GH-534: Fix calculation of lm perplexity when running on GPU

---

README.md

Update the version number in release 0.4.1, seems like PR #533 (GM-481) has missed.

Update version number in release 0.4.1

---

resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md

Corrected small typo in tutorial 7

Corrected typo in "labelling"

---

resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md

Test pull request to correct typo

correct typo

---

resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md

Gh test michal

---

flair/training_utils.py
resources/docs/TUTORIAL_6_CORPUS.md
tests/test_utils.py

changes the accuracy calculation as to be consistent with scikit-learn. See discussion in #483

GH-483: accuracy calculation

---

resources/docs/TUTORIAL_3_WORD_EMBEDDING.md

Fixing a small typo CroatBulgarianian -> Bulgarian.

Fix typo CroatBulgarianian.

---

flair/models/text_classification_model.py

Fix #584 by removing the redundant line of code in TextClassifier class

Fix #584 by removing redundant line of code

---

flair/data.py
flair/data_fetcher.py
flair/embeddings.py
flair/models/sequence_tagger_model.py
flair/trainers/trainer.py

All the 18 major bugs have been fixed, and the total remaining bugs detected in code quality tool ( SonarQube-7.6) are 0. Highest code quality i.e. Grade A is achieved.

removed unused variables via SonarQube-7.6: Improving code quality from grade C to A.

---

resources/docs/TUTORIAL_5_DOCUMENT_EMBEDDINGS.md
resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md

Improving documentation on Document RNN embeddings based on #590.

Document Embeddings tutorial updates

---

resources/docs/EXPERIMENTS.md

Hi,
this PR fixes the CoNLL-2003 NER experiment section with `PooledFlairEmbeddings`.

Small fix for experiment section

---

resources/docs/TUTORIAL_8_MODEL_OPTIMIZATION.md

Closes #577 
This PR corrects an error in the hyperparameter optimization tutorial.

GH-577: correct tutorial

---

flair/__init__.py
flair/datasets.py
flair/embeddings.py
resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md
resources/docs/TUTORIAL_5_DOCUMENT_EMBEDDINGS.md
resources/docs/TUTORIAL_6_CORPUS.md
resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md
resources/docs/TUTORIAL_8_MODEL_OPTIMIZATION.md
setup.py

Version and documentation changes to prepare for release 0.4.2.

GH-563: prepare 0.4.2 release

---

flair/embeddings.py
resources/docs/TUTORIAL_3_WORD_EMBEDDING.md
resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md

Hi,
this PR addresses the unification issues raised in #722 for Persian :)

GH-772: unification for Persian (fa)

---

flair/trainers/trainer.py
flair/training_utils.py

closes 788 
This PR fixes the open log file handler issue when training multiple models in a loop. We also add more log output such as the model and training parameters.

GH-788: fix training log

---

flair/trainers/trainer.py

Hi,
this PR allows to specify the minimum learning rate for training, as discussed in #864 - and replaces a magic number :)

GH-864: allow configuration of minimum learning rate

---

resources/docs/TUTORIAL_6_CORPUS.md

Edited tutorial 6 to include easy loading of a custom CSV dataset with CSVClassificationCorpus as an alternate method to formatting custom data to FastText.

GH 904: Update tutorial 6 to include use of CSVClassificationCorpus

---

flair/embeddings.py

Added XLMEmbeddings class based on #873

GH-873: Add new type of embeddings: XLMEmbeddings

---

flair/trainers/trainer.py

Hi,
PyTorch 1.1.0 has native support for TensorBoard 🎉
This PR adds support for writing a TensorBoard compatible output, that looks like:
In order to use TensorBoard during training a model, just use:
```python
trainer: ModelTrainer = ModelTrainer(tagger, corpus, use_tensorboard=True)
```
All logs will be written to a local `./runs` folder.
Just install the latest `tensorboard` version (required to workaround [this refreshing bug](https://github.com/pytorch/pytorch/issues/20477)):
```bash
$ pip3 install tb-nightly
```
Then you can start TensorBoard with:
```bash
$ tensorboard --logdir runs
```
Finally, open `http://localhost:6006` in your webbrowser.

GH-923: add support for PyTorch's TensorBoard (ModelTrainer)

---

flair/datasets.py
flair/file_utils.py

Adds a parallel corpus object and download routine for multilingual similarity learning.

Added Tatoeba parallel corpus

---

flair/visual/training_curves.py
requirements.txt

1 enable plots to be displayed when running in both .py and .ipynb
2 display text to notify user the path of the saved plots

Enhancement to Plotter() visualization

---

flair/models/sequence_tagger_model.py

Fixing inconsistency between the couple (best_path, best_scores) and scores in the SequenceTagger model using the CRF for predictions. 
Indeed, what is happening sometimes is that the tag with the highest score is not the same between *scores* and the pair (*best_path*, *best_scores*). This PR should fix this behavior.

Fix inconsistency between best_path, best score and scores

---

flair/trainers/language_model_trainer.py
flair/trainers/trainer.py

Renames `apex` variable to `use_amp` in the trainer classes.

GH-934: renamed amp variable

---

resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md

Hi,
this PR adds a documentation for all new embeddings that comes from the brilliant [PyTorch-Transformers library](https://github.com/huggingface/pytorch-transformers).

WIP: GH-971: documentation for new PyTorch-Transformers embeddings

---

flair/datasets.py

GH-979: fixed UD_GERMAN_HDT paths

---

flair/datasets.py
resources/docs/TUTORIAL_6_CORPUS.md

This will hopefully help some people learn how reading a ColumnCorpus from file works

GH-953: Simplify ColumnDataset sentence split rule, improve tutorial

---

flair/datasets.py
tests/test_data_fetchers.py

GH-981: fix max_tokens_per_doc in ClassificationCorpus

---

README.md

Hi Guys,
I made a small visualization tool for highlighting the extracted entities with the flask backend serving the Flair and frontend using Angular. (https://github.com/lunayach/visNER)
I added its link in the Readme so that people may find it easily.

Adding a link of visualizer tool in the Readme

---

flair/models/sequence_tagger_model.py

Closes #1012 
Increases `SequenceTagger` prediction speed by making it optional (and by default not activated) to predict all tags instead of only the most likely one. Adds the new boolean argument `all_tag_prob` to the `predict()` method to control this behavior (if set to `True`, predict all).

GH-1012: make all tag prediction optional to increase speed

---

flair/datasets.py
flair/models/sequence_tagger_model.py
flair/models/text_classification_model.py
flair/visual/training_curves.py

This PR updates all pretrained models that used embeddings that are now deprecated. 
Closes #974

GH-974: update pretrained models

---

flair/datasets.py

fixed [issue#1054](https://github.com/zalandoresearch/flair/issues/1054)

fixed CSVClassificationDataset loading file encoding error

---

flair/embeddings.py
flair/models/language_model.py
flair/visual/manifold.py
tests/test_visual.py

Some cleaning to prepare a large refactoring
Simply share padding code between Flair embeddings and character embeddings

[refactoring] move padding to LM class

---

flair/embeddings.py

GH-1141: fix onehot initialization on cuda

---

flair/embeddings.py
flair/models/sequence_tagger_model.py
flair/models/text_classification_model.py

2 operations adapted from NER inference:
- smart padding (long first)
- large decrease of concat (lazy approach)
Can infer classification from String directly too.
As IMDB is huge, measures have been performed on CONLL 2003 on a custom model trained on IMDB.
master: 12mn56s
this PR: 5mn34s
On Nvidia 2080TI, usage rate between 70 and 80%

[classification] Decrease of inference time of 57%

---

flair/datasets.py

Added Feidegger corpus, as described in #1197.

GH-1197: Feidegger corpus

---

flair/models/similarity_learning_model.py

GH-1212: added interleaving modality option

---

flair/trainers/trainer.py
requirements.txt

GH-1216: changed the default initializer for minibatch size in trainer

---

resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md

Fix tutorial to follow change in interface

---

flair/embeddings.py
flair/models/language_model.py
flair/trainers/language_model_trainer.py

Some small bug fixes: 
- Add a warning if validation data is too small (closes #1115) 
- Remove leftover printline (closes #1224) 
- Correct generate_text() UTF-8 conversion

GH-1115: Add warning if validation data too small

---

flair/embeddings.py

Hi,
this PR fixes the usage of GPT-2 and RoBERTa embeddings.

GH-1181: use correct subtoken mapping function for GPT-2 and RoBERTa

---

resources/docs/TUTORIAL_3_WORD_EMBEDDING.md

The links to tutorial 6/7 were mentioned twice.

Remove duplicate sentence from tutorial 3

---

requirements.txt

Change the sklearn dependency to scikit-learn (as suggested in the description of sklearn)

Replace sklearn by scikit-learn

---

README.md

I request you to add Medium article about Flair NER

Added article about Flair NER practical approach

---

flair/embeddings.py

Actually, the code does not support list of sentences.

Fix typo and annotation

---

flair/data.py
flair/datasets.py
flair/models/language_model.py
flair/models/sequence_tagger_model.py
flair/models/similarity_learning_model.py
flair/models/text_classification_model.py
flair/optim.py
flair/samplers.py
flair/trainers/language_model_trainer.py
flair/trainers/trainer.py
flair/training_utils.py
flair/visual/activations.py

I've added some trivial modifications.
- modify a mismatch between an actual argument name and its corresponding docstring
- delete an unused local variable
- delete unused import statements
- change to use a non-deprecated function
- simplify chained comparisons
- use "not in" for membership test
- modify some instance methods to static methods
I would be happy if my commits would be accepted.

Add some modifications

---

flair/visual/training_curves.py

GH-1371: make test loss plotting optional

---

flair/data.py

Closes #1374  by adding a pretty print function for Dictionary class.

GH-1374: add pretty print function for Dictionary

---

README.md
setup.py

GH-1378: bump version numbers

---

flair/embeddings.py

GH-1377: fix torch 1.4.0 error

---

flair/data.py

Add more information to string output of Sentence.

GH-1449: extend string output of Sentence

---

flair/inference_utils.py

New lmdb backend added, this requires a new dependency to lmdb in requirements.txt
Please review and decide if it deserves to be merged
Olivier Terrier
http://www.kairntech.com

GH-1514: WordEmbeddingsStore: add an alternative backend to sqlite based on lmdb

---

flair/models/sequence_tagger_model.py

This pull request add Malayalam UPOS and XPOS models.
The models are trained with more than 30000 sentences and have the average accuracy as follows:
* UPOS Model - 87%
* XPOS Model - 83%

GH-1521: Add Malayalam POS and XPOS tagger model

---

flair/datasets/sequence_labeling.py

Addresses #1269 by adding the possibility to set a different column delimite for `ColumnCorpus`, i.e. 
```python
corpus = ColumnCorpus(
Path("/path/to/corpus/"),
column_format={0: 'text', 1: 'ner'},
column_delimiter='\t', # set a different delimiter
)
```
if you want to read a tab-separated column corpus.

GH-1269: make column delimiter a property that can be set

---

flair/inference_utils.py

GH-1535: Robustify WordEmbeddingsStore

---

flair/training_utils.py

Fix minor accuracy bug

---

flair/models/sequence_tagger_model.py

GH-1562: add start and stop tags to dictionary

---

flair/datasets/document_classification.py

Adds the possibility to define "skip labels" when loading a ClassificationCorpus. All data points with this label are skipped and do not become read into dataset. 
Also, adds the possibility to downsample 5 star reviews, which make the vast majority of data points in the Amazon Reviews dataset. 
The following code loads a review dataset with labels 3.0 and 4.0 skipped and 5.0 reviews downsampled:
```python
corpus = AMAZON_REVIEWS(skip_labels=['3.0', '4.0'], fraction_of_5_star_reviews=12)
```

GH-1569: add filtering and downsampling options to AmazonReviews dataset

---

flair/datasets/document_classification.py

Add the option of passing different tokenizers when loading classification datasets.

GH-1503: add tokenization presets to ClassificationCorpus

---

flair/data.py
flair/embeddings/token.py
flair/trainers/trainer.py

This PR fixes a number of transformer-related errors reported in #1518 and #1590.

Transformer errors

---

flair/data.py
tests/test_data.py

Add some unit tests for sentences containing problematic symbols.

Add unit tests

---

flair/datasets/sequence_labeling.py
flair/embeddings/base.py

add required attributes to base Embedding class; improve documentation for conll03 corpus

missing Embedding attributes; conll03 doc

---

flair/data_fetcher.py
flair/datasets/document_classification.py
flair/datasets/sequence_labeling.py
flair/datasets/treebanks.py
flair/file_utils.py
flair/inference_utils.py
flair/models/language_model.py
flair/trainers/language_model_trainer.py
flair/trainers/trainer.py
flair/training_utils.py
flair/visual/training_curves.py

this should fix issue #1622. additionally in a bunch of places it is now possible to give file paths as strings instead of only Path instances. besides that some minor formatting things where flake8 in my text editor was being annoying.

fix figsize issue; allow for str in addition to Path

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py
resources/docs/TUTORIAL_6_CORPUS.md

#3 created corpus for swedish NER using dataset https://github.com/klintan/swedish-ner-corpus/ 
a function is added that adds IOB2 tags to the dataset since they are missing.

Ner corpus swedish

---

flair/data.py
tests/test_data.py

Fixes a tokenization error for some sentences. Closes #1651

GH-1651: tokenization

---

flair/embeddings/token.py
tests/test_embeddings.py

This PR fixes some subtokenization issues that affect the `TransformerWordEmbeddings`. It adds handling for tokens that are skipped by BERT tokenization and so closes #1672

GH-1672: token mismatches between transformer and flair

---

flair/embeddings/token.py

Fix serialization error in PooledFlairEmbeddings (see #1593)

GH-1593: fix serialization error

---

flair/embeddings/token.py

Fixes mean pooling as described in #1593

GH-1660: fix mean pooling in PooledFlairEmbeddings

---

flair/embeddings/__init__.py
flair/embeddings/document.py
requirements.txt
resources/docs/TUTORIAL_5_DOCUMENT_EMBEDDINGS.md

gh-1660 added new class for SentenceTransformers

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py
resources/docs/TUTORIAL_6_CORPUS.md

Added the Legal Entity Recognition Corpus for usage in FlairNLP.

LER_GERMAN addition to FlairNLP

---

flair/datasets/sequence_labeling.py

Adds encoding information to fix #1291

GH-1291: fix WIKINER encoding for windows

---

flair/embeddings/token.py
tests/test_embeddings.py

Fixes #1703 by detecting and ignoring "empty" sentences.

Gh 1703 subtokenization

---

flair/models/text_classification_model.py
requirements.txt

Fix error in TextClassifier caused by not passing a label_type.

Classfier error

---

README.md
flair/__init__.py
flair/embeddings/document.py
flair/embeddings/token.py
flair/models/sequence_tagger_model.py
flair/models/text_classification_model.py
resources/docs/TUTORIAL_2_TAGGING.md
resources/docs/TUTORIAL_5_DOCUMENT_EMBEDDINGS.md
resources/docs/TUTORIAL_6_CORPUS.md
setup.py

- Bump Flair version number
- Update documentation
- Fix logging errors (closes #1736) 
- Update serialized transformer models

GH-1739: prepare release 0.5.1

---

resources/docs/TUTORIAL_6_CORPUS.md

The was a code block missing in Tutorial 6.

Add missing code example to tutorial

---

flair/datasets/document_classification.py

Suggestion to fix the issue outlined in: #1765

Added encoding specification for WASSA files

---

flair/datasets/sequence_labeling.py

This PR will fix the URL to DaNE dataset URL. 
- Reference issue: https://github.com/flairNLP/flair/issues/1782
- Resolved in the main danlp: https://github.com/alexandrainst/danlp/issues/55

Update DaNE dataset URL

---

flair/embeddings/token.py
flair/training_utils.py

GH-1690: fix weight extraction error for empty sentences

---

README.md
flair/__init__.py
flair/data.py
flair/embeddings/token.py
flair/models/sequence_tagger_model.py
flair/trainers/trainer.py
resources/docs/HUNFLAIR.md
resources/docs/HUNFLAIR_CORPORA.md
resources/docs/HUNFLAIR_EXPERIMENTS.md
resources/docs/HUNFLAIR_TUTORIAL_1_TAGGING.md
resources/docs/HUNFLAIR_TUTORIAL_2_TRAINING.md
resources/docs/TUTORIAL_1_BASICS.md
resources/docs/TUTORIAL_2_TAGGING.md
resources/docs/TUTORIAL_5_DOCUMENT_EMBEDDINGS.md
resources/docs/TUTORIAL_6_CORPUS.md
setup.py

Prepare biomed release

---

resources/docs/HUNFLAIR.md
resources/docs/HUNFLAIR_EXPERIMENTS.md
resources/docs/HUNFLAIR_TUTORIAL_2_TRAINING.md

Gh 1817 fix paper ref

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py

I took this assignment as a chance to test how Flair interacts with some sentences in Arabic and summed it up in this Jupyter Notebook:  [ExposéTutorial.ipynb.zip](https://github.com/flairNLP/flair/files/5171526/ExposeTutorial.ipynb.zip)
The standard tutorial code has been hence slightly modified. Some inline comments start with 'MM:'
A more elaborate discussion on that via Email. 
Modified Dataset attached in #1847 
test the task via: [FlairTask.py.zip](https://github.com/flairNLP/flair/files/5171498/FlairTask.py.zip)
-----
*Task Description as received on 20200901*
In this task, you will use the Flair library to train a simple sequence labeling model to perform named entity recognition (NER). In NER, we want to find the names of certain entities (such as people, organizations, or genes) …

GH-1847: Add MIT Restaurant NER Dataset

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py

Added the twitter-ner corpus for sequence labeling, using the dataset:
https://raw.githubusercontent.com/aritter/twitter_nlp/master/data/annotated/ner.txt

Added twitter-ner to sequence labeling

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py
requirements.txt

Xtreme wikiann corpus

---

flair/models/sequence_tagger_model.py

GH-1868: correct variable names

---

flair/datasets/sequence_labeling.py

GH-1861: fix problem with custom delimiters in ColumnDataset

---

flair/models/text_classification_model.py

GH-1272: fix offensive language detection model

---

flair/__init__.py
flair/datasets/treebanks.py
resources/docs/TUTORIAL_2_TAGGING.md
resources/docs/TUTORIAL_6_CORPUS.md
setup.py

Prepare Release 0.6.1

---

flair/datasets/biomedical.py

This fixes encoding issues under Windows and should close #1874

Biomedical: Explicit encodings for Windows Support

---

requirements.txt

pytest is not an install dependency.
It should be in another requirements file maybe requirements_dev.txt

Remove pytest from the requirements.txt

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py
resources/docs/TUTORIAL_6_CORPUS.md

Created two different corpus classes to maintain the original separation

Added Simple and Complex MIT Movie Corpus with automatic download

---

flair/datasets/__init__.py
flair/datasets/document_classification.py
resources/docs/TUTORIAL_6_CORPUS.md

Added GoEmotions corpus for textclassification

added GoEmotions text classification corpus

---

flair/datasets/base.py
flair/datasets/sequence_labeling.py

Test PyTest error that occurs in Travis.

Test PyTest error that occurs in Travis

---

README.md
flair/models/text_classification_model.py

Fixed an [issue](https://github.com/flairNLP/flair/issues/1925) with sampling negative labels. Added "TARS" with the shortcut link on the homepage.

GH-1925: fixed a bug, added TARS on homepage

---

flair/datasets/__init__.py
flair/datasets/treebanks.py

Integrate Greek language in flair using the Greek Universal Dependency Treebank

Add Greek UD Treebank

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py

Added dataset about NER for Chinese Social Media (Weibo).
The original data comes from https://github.com/hltcoe/golden-horse 
The formatted data is stored at https://github.com/87302380/WEIBO_NER

Adding WEIBO_NER dataset support 

---

flair/embeddings/token.py

Add instance parameters to word embedding object upon creation

---

flair/datasets/treebanks.py

GH-1945: optional dev and test splits in treebanks

---

flair/datasets/treebanks.py

Added support for UD_BURYAT

---

.travis.yml
requirements.txt

`sentencepiece==0.1.91` instead of `sentencepiece!=0.1.92`

Change requirement to sentencepiece<=0.1.91 so that travis can install all required packages

---

flair/data.py
flair/models/__init__.py
flair/models/text_classification_model.py
flair/trainers/trainer.py

Distance classifier

---

flair/embeddings/token.py

Currently, TransformerWordEmbeddings does not support Transformer-XL because the forward method from the model does not have `attention_mask` which ends up raising an unexpected keyword argument exception.
closes #2008

GH-2008: add support to Transformer-XL in TransformerWordEmbeddings

---

flair/datasets/sequence_labeling.py

It wasn't possible yet, to specify a dev_file for the WSD_UFSAC corpus. This PR adds this possibility.

Add dev_file support for WSD_UFSAC corpus

---

flair/hyperparameter/budget.py
flair/hyperparameter/downstream_task_models.py
flair/hyperparameter/orchestrator.py
flair/hyperparameter/parameter_collections.py
flair/hyperparameter/search_spaces.py
flair/hyperparameter/search_strategies.py

Small changes as a suggestion: 
- Added some return types to method signatures
- Made some object methods static
- Some object methods are no longer protected since they are accessed in other classes
- minor formatting

Small formatting and variable declaration changes

---

flair/datasets/sequence_labeling.py

GH-2060: fix document boundary offsets for Dutch CoNLL-03

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py

Hungarian NER Business Corpus has been added. There are two assumptions which , above all , need to be reviewed. These assumptions are commented in sequence_labeling.py

HUN_NER_EXTENSION

---

resources/docs/TUTORIAL_6_CORPUS.md

anercorp extra '/' leads to deadlink

typo in link

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py

Added the Stackoverflow_Ner Object for usage in FlairNLP.

Stackoverflow_Ner Object added to FlairNLP

---

flair/data.py
flair/datasets/sequence_labeling.py
flair/models/__init__.py
flair/models/tars_sequence_tagger_model.py
flair/models/tars_sequence_tagger_model2.py
flair/nn.py
tests/test_tars_sequence_tagger.py

This PR contains:
- class for tars sequence tagging, using boolean classes to predict
- class for tars sequence tagging, using BIO2 classes to predict
- option for dropout tensors to also have 4 dimensions
- option for ColumnCorpus to format the corpus to BIO2 format

Tars sequence tagger

---

README.md

I just realized that I never added a url to the interpret-flair repo. 
The contributions are discussed in #1504 , but I never a link to the repo in the readme. 
I hope that by adding a url to the repo that this will spark interest from the community to contribute to improving this solution.

Added a link to the interpret-flair repo.

---

flair/datasets/sequence_labeling.py
flair/embeddings/token.py

Add the possibility to set context dropout for FLERT.

Random context length

---

flair/datasets/__init__.py
flair/datasets/document_classification.py

Added GermEval 2018 data for binary text classification of German tweets. The dataset was taken from https://github.com/uds-lsv/GermEval-2018-Data.

Added GermEval 18 Offensive Language dataset

---

resources/docs/embeddings/ELMO_EMBEDDINGS.md

Added version 0.9.0 of allennlp in docs for easier debugging of allennlp issues. Referenced at  https://github.com/flairNLP/flair/issues/1729 and https://github.com/flairNLP/flair/pull/1734

Add allennlp version for elmo embedding doc

---

flair/models/text_classification_model.py

GH-2126: Update TARS model for bugfixes

---

requirements.txt

GH-2105: update sentencepiece version

---

README.md
flair/__init__.py
flair/datasets/__init__.py
resources/docs/TUTORIAL_2_TAGGING.md
resources/docs/TUTORIAL_6_CORPUS.md
resources/docs/embeddings/TRANSFORMER_EMBEDDINGS.md
setup.py

GH-2132: prepare 0.8 release

---

flair/trainers/trainer.py

Solution for https://github.com/flairNLP/flair/issues/2145

GH-2145: Added new param to save model each k epochs

---

flair/embeddings/document.py
flair/embeddings/token.py
flair/models/text_classification_model.py

This PR fixes the serialization of RNNs in the DocumentRNNEmbeddings class. Also updates the pre-trained "sentiment-fast" model. 
In addition, this PR fixes the serialization of some transformer models like GBert. Also adds a newly trained model for offensive language detection in German.

GH-2137: Fix serialization of DocumentRNNEmbeddings

---

flair/models/text_classification_model.py

This PR improves the `TextPairClassifier` by using the document separator token of the respective transformer model used.

Fix separator in cross-attention mode

---

flair/datasets/document_classification.py

Fixes a bug in IMDB dataset that caused the dataset to grow each time the object is called. Thanks @kishaloyhalder for spotting this!

Fix bug in IMDB dataset

---

flair/datasets/document_classification.py

Fixed a bug described [here](https://github.com/flairNLP/flair/issues/2174).

GH-2174: fixed IMDB data splitting logic

---

flair/models/sequence_tagger_model.py
flair/models/similarity_learning_model.py
flair/models/text_classification_model.py
flair/models/text_regression_model.py
flair/trainers/trainer.py
flair/training_utils.py

Save the best model seen so far (based on dev data) also if the cyclic learning rate scheduler is used

Gh 2119 saving best model for cyclic lr

---

flair/embeddings/document.py

Added 'mean', 'max' pooling strategy for `TransformerDocumentEmbeddings` class.

Gh 2179 transformer pooling

---

flair/datasets/__init__.py
flair/datasets/document_classification.py
resources/docs/TUTORIAL_6_CORPUS.md

I added the Yahoo_Answers corpus for text classification.

Added Yahoo_Answers text classification corpus

---

flair/datasets/__init__.py
flair/datasets/treebanks.py

I have added the faroese language from the UD-data*, the dataset works and is usable for training on my computer. :) 
* see here: https://github.com/UniversalDependencies/UD_Faroese-FarPaHC

Added UD-data for the faroese language

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py

Kinyarwanda dataset for NER added from
https://github.com/masakhane-io/masakhane-ner/tree/main/data/kin

Support for Kinyarwanda language dataset (NER) added

---

flair/datasets/__init__.py
flair/datasets/treebanks.py

Estonian language dataset from https://github.com/UniversalDependencies/UD_Estonian-EDT/tree/master is added to Flair for PoS.

Support for UD Estonian (PoS) added

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py

Added African Luo language dataset from https://github.com/masakhane-io/masakhane-ner/tree/main/data/luo for NER.

Support for Luo language dataset (NER) added

---

flair/datasets/__init__.py
flair/datasets/treebanks.py

add coptic POS model

---

flair/datasets/__init__.py
flair/datasets/treebanks.py

Added OLD CHURCH SLAVONIC for POS

Added Old Church Slavonic language for Part-Of-Speech tagging

---

flair/datasets/__init__.py
flair/datasets/treebanks.py

Context: add support for a new dataset UD_BELARUSIAN-HSE (POST)
Summary:
Belarusian is an East Slavic language spoken by the Belarusians. 
Part-of-speech tagging (POS tagging, POST) is the process of marking up a word in a text (corpus) as  corresponding to a particular part of speech based on both its definition and its context.

Add support for UD_BELARUSIAN-HSE dataset (POS)

---

flair/datasets/__init__.py
flair/datasets/treebanks.py

Added the Modern Eastern Armenian Universal Dependencies treebank. (https://github.com/UniversalDependencies/UD_Armenian-ArmTDP)

UD_ARMENIAN (for module Introduction to NLP @ HU Berlin)

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py

Adds the Naija Pidgin dataset for NER from https://github.com/masakhane-io/masakhane-ner/tree/main/data/pcm

Added Naija Pidgin NER dataset (Introduction to NLP @ HU Berlin)

---

flair/data.py

fixes https://github.com/flairNLP/flair/issues/2224

remove unk token from Ner labeling

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py

Adding support for the African language Hausa as part of the NLP lecture.

Added NEW support for the Hausa language 

---

flair/datasets/__init__.py
flair/datasets/treebanks.py

Kazakh is a Turkic language spoken in Central Asia.

added kazakh as new language for pos

---

flair/datasets/__init__.py
flair/datasets/treebanks.py

Added the UD_Ancient_Greek-PROIEL Corpus for usage in FlairNLP.

UD_Ancient_Greek-PROIEL addition to FlairNLP

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py
resources/docs/TUTORIAL_6_CORPUS.md

Luganda or the Ganda language is a Bantu language spoken in the African Great Lakes region. It is one of the major languages in Uganda and is spoken by more than eight million Baganda and other people. ~Source Wikipedia (https://en.wikipedia.org/wiki/Luganda)

Add Luganda_NER Support

---

flair/datasets/__init__.py
flair/datasets/treebanks.py

Support for POS model Lithuanian

---

flair/datasets/treebanks.py

I rewrite Lithuanian to LITHUANIAN.

Capitalizing

---

flair/datasets/__init__.py
flair/datasets/treebanks.py

Added support for the Galician language. Galician is an Indo-European language spoken mainly in northwestern Spain.

Added Galician POS support to treebanks

---

flair/datasets/document_classification.py

fixed typo in property name

---

flair/models/sequence_tagger_model.py

This implementation of the MFS baseline picks the first sense annotated in WordNet for the prediction when the model would otherwise make no prediction.

Adds most frequent sense (MFS) baseline for WSD evaluation

---

flair/models/language_model.py

Fix for de-serializing old models (closes #2279)

GH-2279: fix loading of old serialized models

---

flair/datasets/biomedical.py
resources/docs/HUNFLAIR_CORPORA.md

Update url for BioSemantics corpus

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py

Added NER_GERMAN_POLITICS to sequence_labeling.py

Add dataset NER_GERMAN_POLITICS

---

requirements.txt

Update to newest torch version which fixes #2137 
I believe this also addresses #2339

GH-2137: update requirements

---

flair/models/tars_model.py
flair/nn/model.py
tests/test_tars.py

This PR fixes a number of small errors in the refactoring, mostly pertaining to multi-label classification. 
- fixes the calculation of evaluation metrics for multi label (thanks @marcelmmm for noticing the error)
- fixes handling of empty tensors for multi-label
- a number of sequence TARS fixes pertaining to issues caused by the new Dictionary logic (no default return for unknown words)

Multi task corrections

---

flair/nn/model.py

Remove some unused methods left over from the refactoring (thanks @yosipk for pointing this out!)

Remove redundant methods

---

tests/resources/tasks/trivial/trivial_bioes/dev.txt
tests/resources/tasks/trivial/trivial_bioes/test.txt
tests/resources/tasks/trivial/trivial_bioes/train.txt
tests/resources/tasks/trivial/trivial_text_classification_multi/dev.txt
tests/resources/tasks/trivial/trivial_text_classification_multi/test.txt
tests/resources/tasks/trivial/trivial_text_classification_multi/train.txt
tests/resources/tasks/trivial/trivial_text_classification_single/dev.txt
tests/resources/tasks/trivial/trivial_text_classification_single/test.txt
tests/resources/tasks/trivial/trivial_text_classification_single/train.txt
tests/test_models.py

Add integration tests or training/fine-tuning sequence tagger and text classification models to test if they can fit trivial training data.

Add model fit tests

---

flair/nn/model.py
tests/test_text_classifier.py

Bugfix to correct scores when using multi_class_prob flag

---

flair/data.py
flair/nn/model.py

The refactorings introduced some deep copy operations that were causing trouble.

Remove deep copy operations

---

flair/nn/model.py

Small fix to increase prediction speed if label set is large.

Fix prediction speed for single label predictions

---

flair/trainers/language_model_trainer.py
tests/test_language_model.py

GH-2371: rename load_from_checkpoint to load_checkpoint

---

flair/embeddings/token.py

Hi,
this PR introduces a new `is_lower` option for the Flair Embeddings class, that allows to use Flair Embeddings, that are trained on lower-cased text.
This option is e.g. needed for the CLEF HIPE Flair Embeddings (that were trained on lower-cased historic corpora):
```python
from flair.embeddings import FlairEmbeddings
embeddings_historic = FlairEmbeddings("de-impresso-hipe-v1-forward")
embeddings_historic.is_lower  # returns True
embeddings_german = FlairEmbeddings("de-forward")
embeddings_german.is_lower  # returns False
```

Allow lower-cased Flair Embeddings

---

flair/models/tars_model.py

This PR does some minor refactorings on the TARSClassifier class.

Minor refactorings in TARS classifier

---

flair/data.py
flair/models/tars_model.py

- Fix small bug in Dictionary creation
- Make task specification in TARS tagger optional

Small fies for v0.9

---

flair/models/lemmatizer_model.py

Minor formatting and code style.

minor formatting

---

flair/embeddings/token.py
resources/docs/embeddings/FLAIR_EMBEDDINGS.md

This PR adds the FLAIR EMBEDDING for the Amharic language.﻿﻿

Adding the am-forward FLAIR embedding model for Amharic

---

flair/datasets/__init__.py
flair/datasets/sequence_labeling.py

Add a loader for the new Dataset of SemEval2022 Task 11: https://multiconer.github.io/competition
notice, that the dataset has to be manually applied for and downloaded here: https://multiconer.github.io/dataset
after setting it up, the corpus can be loaded for any of the tasks, e.g.
`corpus: Corpus = MultiCoNer("en")` for english monolingual, or `corpus: Corpus = MultiCoNer("multi")` for multilingual of all datasets

add MultiCoNer Dataset

---

flair/trainers/trainer.py
requirements.txt

Fix error in trainer caused by leftover from refactoring.

Fix result object in ModelTrainer

---

flair/datasets/entity_linking.py

Fixed little bug in wsd_ufsac_corpus

fix bug in wsd_ufsac corpus

---

CONTRIBUTING.md
README.md
flair/__init__.py
resources/docs/TUTORIAL_2_TAGGING.md
resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md
setup.py

Update documentation for Flair 0.10 and bump version numbers

Flair release 0.10

---

README.md

This PR introduces minor fixes in the sota models section :)

readme: minor fixes in sota models section

---

flair/data.py

Sensible addtition to Dictionary. Closes GH-2504

GH-2504 add equality method to Dictionary class

---

flair/models/dependency_parser_model.py

Fixes computation of the LAS in DependencyParser

Fixes LAS in Dependency Parser

---

flair/models/lemmatizer_model.py

Fixes small error in Lemmatizer

Fix encoding error in lemmatizer

---

flair/data.py
flair/models/sequence_tagger_model.py

Sequence tagger speedups

---

flair/models/diagnosis/distance_prediction_model.py
flair/nn/model.py
flair/trainers/trainer.py
tests/test_trainer.py

As https://github.com/flairNLP/flair/issues/2555 is a bug introduced by https://github.com/flairNLP/flair/pull/2537 I created a fix and added a test to ensure that mistake won't be done again

Gh 2555/bf/fix training log file

---

flair/models/sequence_tagger_model.py
flair/models/sequence_tagger_utils/viterbi.py

closes GH-2559 and closes GH-2560

GH-2559: Return all tag probabilities + GH-2560: predict() method can handle flair datasets

---

flair/models/tars_model.py

TARS Tagger fixes

---

flair/data.py
flair/models/sequence_tagger_model.py
flair/models/tars_model.py

Fixes two errors: 
- Creation of IOBES Tags when tag names contain a minus
- Forward pass in SequenceTagger if empty list passed

Tars fixes

---

flair/datasets/sequence_labeling.py
tests/test_datasets.py

This is supposed to fix https://github.com/flairNLP/flair/issues/2434
besides that, it removes the whitespacing for japanese tokenisation, as there is no space between words

set token positions on column corpus

---

flair/embeddings/token.py

TransformerWordEmbeddings to process long sequences by default

---

flair/embeddings/token.py

fix typo in TransformerEmbeddings constructor

---

flair/models/sequence_tagger_model.py
flair/models/sequence_tagger_utils/viterbi.py

Black code formatter for sequence_tagger_model.py and viterbi.py.

---

flair/models/language_model.py
flair/nn/recurrent.py
flair/trainers/__init__.py
flair/trainers/language_model_trainer.py
flair/trainers/trainer.py

fix lm training (fix https://github.com/flairNLP/flair/issues/2577 )
nice output in lm training
allow usage of lstm and gru in flair lm
remove unnecessary imports in flair/__init__.py
@alanakbik this is basically some modifications I did while training the SRU, however the SRU itself was not sucessfull enough to be merged (not only that it is a bit more complicated to install it due to special cuda requirements)

small lm training improvements

---

flair/models/__init__.py
flair/models/lemmatizer_model.py
flair/models/sequence_tagger_model.py
flair/nn/recurrent.py

Directories flair.models.diagnosis and flair.models.sequence_tagger_utils were not imported due to missing __init__.py
Solution: Add (empty) init file in both directories.

Bug import

---

flair/__init__.py
flair/datasets/__init__.py
flair/datasets/document_classification.py
flair/models/__init__.py
flair/models/clustering.py
requirements-dev.txt

A small PR to (hopefully) pass formatting unit tests.

Reformat clustering classes

---

resources/docs/TUTORIAL_6_CORPUS.md

Documentation updated. Duplicate word handled.

Sentence update.

---

examples/ner/README.md

#2655 I have updated the broken link. @

updated broken link

---

flair/embeddings/base.py
tests/test_embeddings.py

tests and fixes the issue with https://github.com/flairNLP/flair/issues/2713

GH-2713: make transformer offset calculation more robust

---

flair/__init__.py
setup.py

Bump numbers for bugfix release.

GH-2689: bump version numbers to 0.11.1

---

flair/datasets/sequence_labeling.py
tests/resources/tasks/span_labels/span_first.txt
tests/resources/tasks/span_labels/span_second.txt
tests/resources/tasks/span_labels/span_third.txt
tests/resources/tasks/up_english/en_ewt-up-dev.conllu
tests/resources/tasks/up_english/en_ewt-up-test.conllu
tests/resources/tasks/up_english/en_ewt-up-train.conllu
tests/test_datasets.py

This PR addresses #2722 to make Span detection more robust + adds some unit tests.

GH-2722: Make Span detection more robust

---

flair/__init__.py
setup.py

Bump version number to 0.11.3 for impending release.

GH-2770: bump version numbers

---

flair/models/sequence_tagger_model.py

fixes https://github.com/flairNLP/flair/issues/2784

allow BIO evaulation on sequence tagger

---

flair/embeddings/transformer.py
resources/docs/TUTORIAL_13_TRANSFORMERS_PRODUCTION.md
tests/test_embeddings.py

add the example as test and fixes the issue

GH-2882: fix trainling comma at the end of the sentence

---

flair/trainers/trainer.py

Following the comment in #2888, experiment with alternative heuristic that distinguishes between embeddings and all other parts of the model.

GH-2888: Experiment with alternative heuristic

---

resources/docs/TUTORIAL_5_DOCUMENT_EMBEDDINGS.md

GH-2901: Add Missing Import to Tutorial 5

---

README.md

Adds a few pointers to documentation to the landing page.

GH-2921: Documentation pointers

---

flair/trainers/trainer.py

fix for #2848 
it's a small change but pretty annoying when using tensorboard

GH-2848 add missing tab

---

flair/trainers/trainer.py
pyproject.toml
requirements-dev.txt

Do not print out BAD_EPOCHS unless using AnnealOnPlateau scheduler, which has this variable.

GH-609: Remove BAD_EPOCHS printout for most schedulers

---

flair/models/tars_model.py

GH-2982: Fix problem in loading TARSClassifier

---

flair/embeddings/transformer.py
requirements.txt

Fix unit tests by correcting formatting and pinning the huggingface_hub version.

Fix unit tests

---

flair/models/text_classification_model.py

Suggestion for fixes in prediction_depth branch.

Fix tensor shape

---

flair/datasets/biomedical.py

Revert "HunFlair: switched dead links for new ones and adjusted parser if nec…"

---

flair/embeddings/transformer.py
pyproject.toml
tests/embeddings/test_transformer_word_embeddings.py

fixes https://github.com/flairNLP/flair/issues/3035
And adds a test that is run when onnx-runtime is installed for local testing.

Fix onnx export

---

flair/embeddings/token.py

added weighted sum layer

---

flair/trainers/trainer.py

Adds the option not to shuffle the first epoch when training.

Add option not to shuffle the first epoch

---

flair/embeddings/transformer.py
tests/conftest.py
tests/embeddings/test_transformer_word_embeddings.py

fixes https://github.com/flairNLP/flair/issues/3072
also fixes the `--force-cpu` flag for tests

Gh 3072/transformer mean pooling

---

.pre-commit-config.yaml
flair/trainers/trainer.py

- Reverts isort version mistakenly set in #3090
- Fixes shuffling broken in #3076 (thanks @plonerma for noticing this)

Two small bugfixes

---

flair/models/entity_linker_model.py

Adapts the Entity Linking candidate generator to remove punctuation and excess whitespaces for hopefully better backoff.

Better candidate backoff

---

flair/models/multitask_model.py

This PR pushes a new version of the Zelda entity linking model, with improved prediction scores.

Improve ZELDA entity linking model

---

README.md
flair/__init__.py
setup.py

Another version bump for the hotfix release.

Bump Flair version to 0.12.1

---

flair/__init__.py

Settting device through environment variable

---

README.md
flair/__init__.py
flair/data.py
flair/training_utils.py
setup.py

This PR makes final fixes for the next incremental Flair release.

Small fixes for release 0.12.2

---

flair/embeddings/transformer.py

I noticed that transformer embeddings download the config from the hub whenever they are loaded.
This PR fixes that.
Example to run on master:
```
tagger = SequenceTagger.load("ner-large")
tagger.save("ner-large.pt")
reloaded_tagger = SequenceTagger.load("ner-large.pt")
```

fix seralization of config in transformers

---

flair/trainers/trainer.py

We need to update `best_epoch_score` correctly after each epoch.

Fix best epoch score update

---

flair/embeddings/transformer.py
tests/embedding_test_utils.py

closes https://github.com/flairNLP/flair/issues/3218

fix bug with sentences that do not contain a single valid transformer token

---

flair/embeddings/token.py

Closes https://github.com/flairNLP/flair/issues/3266

fix multiple arguments destination

---

flair/nn/model.py
resources/docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md

Closes https://github.com/flairNLP/flair/issues/3298

fix embedding finetuning tutorial

---

docs/requirements.txt

this PR fixes the buttons on the new docpage being purple instead of orange

orange secondary color

---

flair/trainers/plugins/__init__.py
flair/trainers/plugins/loggers/clearml_logger.py
flair/trainers/trainer.py

add https://clear.ml/ as potential logger.

Clearml logger

---

flair/datasets/sequence_labeling.py
tests/resources/tasks/jsonl/testa.jsonl
tests/test_datasets.py

based on https://github.com/flairNLP/flair/pull/3334 but fixes a small bug and updates the docstring to google docstring
cc @wh5938316
closes https://github.com/flairNLP/flair/issues/3332

Feature jsonldataset metadata

---

flair/trainers/trainer.py

closes #3373 
this makes the logs look more smoothly:

use batch count instead of total training samples for logging metrics

---

flair/embeddings/transformer.py

closes https://github.com/flairNLP/flair/issues/3517

make onnx export work again

---

flair/nn/model.py

GH-3585: Fix DefaultClassifier deserialization
